### ISSUE TITLE
support for git svn

### ISSUE THREAD

**Issue by cvmocanu** [zielu/GitToolBox#10]
There are a few small changes to be made to support git svn (git as an svn client):
- the remote branch is not correctly found. This is a bit weird, since command line git doesn't see any difference from a normal tracking branch (e.g. `git prompt`, `git branch -vv`, and `git rev-parse --abbrev-ref --symbolic-full-name @{u}` all work fine)
- auto fetch needs to be changed to do `git svn fetch` instead of `git fetch`.

**Comment by zielu** [comment]
I'll look into this. As to the first point - I think that remotes are stored a bit differently for svn tracking branches. I only hope IntelliJ Git API parses them right now ;)

**Comment by jesuswasrasta** [comment]
Is this solved, perhaps?
Using a SVN remote, I'm experiencing the "fetch problem" in Version Control tool window.
In the console I see this:
```
08:41:57.033: [DR-pdl] git -c core.quotepath=false fetch svn --progress --prune
fatal: 'svn' does not appear to be a git repository
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.

```
Thanks for your work :)

**Comment by zielu** [comment]
Hi, I never finished this, as it would require copying some portion of intellij git plugin - some APIs are just not public :/

**Comment by albfan** [comment]
I use git-svn for old projects (from command line msys2) 

@zielu Can you describe what are the problems to integrate git-svn into this plugin? I think I can provide a PR about that, testing and feedback

**Comment by albfan** [comment]
nvm. Just installed the plugin and see the mentioned error. Forking now!

**Comment by zielu** [comment]
@albfan Hi, there's some work done already in GtConfig, GtRepositoryManager to detect git-svn remotes but I never got around to finishing it :/

**Comment by albfan** [comment]
@zielu Yes I see that part, I think that would help to do correct fetch for them. I think fixing that and adding a dcommit would be enough for a basic support of git-svn

**Comment by albfan** [comment]
intellij is hidding svn remotes into normal remotes https://intellij-support.jetbrains.com/hc/en-us/community/posts/206161679-Using-git-svn-with-IDEA?page=1#community_comment_360000034770

By now let's assume that svn is the only remote that is a git-svn bridge. I think I can provide a PR to intellij to fix that, but is not important right now

**Comment by albfan** [comment]
The autofetch of GitToolBox finally invokes a fetchAll from git4idea. 

https://github.com/JetBrains/intellij-community/blob/master/plugins/git4idea/src/git4idea/update/GitFetcher.java#L168

it just need to ignore those remotes which are svn bridges, and we need to add another task to fetch with 
git svn fetch all for those remotes

As error is not really important, I think implement that in GitToolBox could fix this first issue. Then we only need to add to menu actions (`git svn fetch` and `git svn dcommit`) which seems to be easily done with a new GitCommand.SVN_DCOMMIT and GitCommand.SVN_FETCH and using a GitLineHandler like:

https://github.com/JetBrains/intellij-community/blob/master/plugins/git4idea/src/git4idea/commands/GitImpl.java#L502

I'm not skilled on intellij plugins, so any help with boilerplate code (like how to add a menu action, or how to code a GitSvnFetchExecutor is appreciated) maybe a wip/git-svn would be enough

**Comment by zielu** [comment]
Sample action is here: https://github.com/zielu/GitToolBox/blob/master/GitToolBox/src/main/java/zielu/gittoolbox/actions/GitPushTagsAction.java
It needs to be registered in https://github.com/zielu/GitToolBox/blob/master/GitToolBox/src/main/resources/META-INF/plugin.xml in actions section.

If we have ```git svn fetch``` implemented then it also be possible to run it in auto-fetch but this will need more thought.

I'll look into running custom Git commands and try to come up out some approach.

I read briefly https://git-scm.com/docs/git-svn and we will also need `git svn rebase`.

**Comment by albfan** [comment]
Yes. I want to launch a `git svn fetch` for autoFetch

Thanks for those links I think I can came out with something using that

`git svn rebase` is not strictly needed. As many porcelain git commands it is a `git svn fetch` followed by a `git rebase`. In my experience that command is confusing, but hey there's even a `git svn branch` and other avaliable commands, let's see how far we get

**Comment by albfan** [comment]
I tried to rewrite only git svn fetch but the IoC in intellij makes me get more and more code. I think is better to fork intellij and add there. But don't know what od these two approach to choose:

- Fork all the intellij sdk. I tried with idea/173.4635 but get two errors:

```
Error:(61, 30) java: incompatible types: inferred type does not conform to upper bound(s)
    inferred: com.intellij.util.Query<? extends java.lang.Object>
    upper bound(s): com.intellij.util.Query<com.intellij.psi.PsiFunctionalExpression>,java.lang.Object
Error:(146, 76) java: unreported exception E; must be caught or declared to be thrown
/home/alberto/projects/java/idea/java/java-indexing-api/src/com/intellij/psi/search/searches/FunctionalExpressionSearch.java
/home/alberto/projects/java/idea/java/java-indexing-api/src/com/intellij/psi/search/searches/ClassInheritorsSearch.java
```

- Fork only git4idea:
Really don't know if that is possible, I here the recommended way is to hack entire sdk

Wether approach taken, how GitToolBox is linked to that fork? I suppose is some local repo, but can't see how

**Comment by albfan** [comment]
Ok, it was only a matter of using jdk 1.8.0_161 (something relatedwith kotlin) I will update comments to reduce noise

**Comment by albfan** [comment]
git svn fetch should be transparent to GitToolBox

https://github.com/JetBrains/intellij-community/pull/725

if any of you want to test it, just build my fork from Intellij or from command line:

    git clone https://github.com/albfan/intellij-community
    cd intellij-community
    ./getPlugins.sh
    export JDK_HOME=/path/to/jdk8
    ant build

installer will be in `out/idea-ce/`


NOTE: to build on linux: Use this ant command

    ant -Dintellij.build.incremental.compilation=true -Dintellij.build.skip.build.steps=windows_exe_installer build

Let's continue with `git svn dcommit`

**Comment by albfan** [comment]
Seems no one cares about that PR.  Anyway I think all implementation should be provided by git4idea. I would close this issue. (and try to make some noise to give traction on [IDEA-26427](https://youtrack.jetbrains.com/issue/IDEA-26427)

**Comment by zielu** [comment]
Closed as wont implement - it's not possible to add new commands to git4idea and going with full blown implementation would be too much effort.

**Comment by albfan** [comment]
The dragon is awakening: https://github.com/JetBrains/intellij-community/pull/725#issuecomment-370487477
