### ISSUE TITLE
Auto fetch from remote on local checkout?

### ISSUE THREAD

**Issue by poisonborz** [zielu/GitToolBox#101]
In addition to fixed interval, could the plugin also feature auto fetch from remote when a local branch is checked out? This is the most annoying thing that sometimes gets forgotten on branch switching, leading to push rejects.

**Comment by zielu** [comment]
@poisonborz Are you on 2018.2 or 2018.3 EAP ?

**Comment by poisonborz** [comment]
2018.1

**Comment by poisonborz** [comment]
@zielu 2018.1

**Comment by zielu** [comment]
Done in 191.0.7
