### ISSUE TITLE
Compatibility with 2018.3 EAP?

### ISSUE THREAD

**Issue by murbanowicz** [zielu/GitToolBox#102]
Can you by any chance build version which 2018.3  will allow installing? I've tried to install from eap file, but Webstorm won't allow installing, as recognizing it as not compatible.

**Comment by zielu** [comment]
To install manually the EAP version you need one starting with 183: https://plugins.jetbrains.com/plugin/download?rel=true&updateId=49765
Alternatively you can add EAP channel as repository: 
https://github.com/zielu/GitToolBox#eap-builds
