### ISSUE TITLE
Vscode's gitlens like git blame? (editor inlined)

### ISSUE THREAD

**Issue by xahon** [zielu/GitToolBox#104]
It would be cool to see a message with custom format that can show blame of the line where cursor is like in vscode with gitlens

**Comment by zielu** [comment]
Cool idea ! Things that I would like to do:
- [ ] Git blame in status bar
- [ ] blame for selected line
- [ ] repository view - ahead, behind commit details

**Comment by zielu** [comment]
It's slowly coming. I started with #105

**Comment by zielu** [comment]
In scope of this blame inlined into editor should be shown

**Comment by meganero** [comment]
How about showing with git log or providing custom format? It would be helpful for understanding intention of a line of codes.

**Comment by zielu** [comment]
@meganero there are two additional features already done related to this (#125, #124) - if you open blame popup for line (alt+shift+B or click on widget in status bar) you can jump to commit in Log view or show files affected by that commit.

**Comment by zielu** [comment]
Done in 183.3.0

**Comment by meganero** [comment]
Okay, I meant actually showing the git log in the editor inlined feature. Thank you for the considering.

**Comment by zielu** [comment]
@meganero you meant having more detailed information about the line commit not only author + date?

**Comment by meganero** [comment]
@zielu Yes, exactly.

**Comment by zielu** [comment]
I created enhancement request our of this #126
