### ISSUE TITLE
Hide status bar items if disabled

### ISSUE THREAD

**Issue by wutsch0** [zielu/GitToolBox#108]
Hi Łukasz,
could you hide the `Git status` and `Blame` items from the status bar if they are disabled in settings instead of showing them with a `disabled` label?

![bildschirmfoto_2018-10-30_14-56-40](https://user-images.githubusercontent.com/5646364/47723405-bcefdd00-dc54-11e8-82da-500a4c05b5ab.png)

**Comment by zielu** [comment]
Implemented in 182.7.0
