### ISSUE TITLE
Blame - bad performance on Class Renaming

### ISSUE THREAD

**Issue by codengine** [zielu/GitToolBox#109]
Hi,
I'm using version 182.6.1 of GitToolBox. So far it works great except for one thing that I noticed.

When I rename a class inside the Editor window (SHIFT + F6) and type the new class name, the performance is really bad and the IDE is very laggy.

However, when I disable the new Blame-Feature everything works as smoothly as expected.

EDIT: Only applies to files that are already staged (-> added) or have been already committed. It also only applies to in-editor edition without the Rename Dialog.

Regards

**Comment by codengine** [comment]
![gittoolbox](https://user-images.githubusercontent.com/498798/47757691-da9a6200-dca7-11e8-9e2a-4aa5a22d0ae6.gif)

**Comment by zielu** [comment]
Fixed in 182.6.2
