### ISSUE TITLE
Project Tree/Branch Name: Improper branch name trimming

### ISSUE THREAD

**Issue by anas-qa** [zielu/GitToolBox#111]
***Description:***
In case you are on `master` and then you want to switch to another branch called `ABC-123`as example, the branch name will be trimmed as the space for the branch name is not dynamic.

This can be fixed by refreshing the project tree (Collapse the project root and open again).

Not clear? 

***Here's some STR:***
1- Open you project on Intellij IDEA and make sure that you are on `master`.
![master](https://user-images.githubusercontent.com/16471809/47993540-27979180-e109-11e8-8ba8-a61e0d990330.png)

2- Through terminal switch to any other branch you have

3- Checkthe IDE project tree
![screen shot 2018-11-05 at 2 54 09 pm](https://user-images.githubusercontent.com/16471809/47994054-b22cc080-e10a-11e8-930f-e89a58bab157.png)

4- Observe from the above snapshot that the branch name is trimmed 

***Actual Result:***
Branch name is trimmed 

***Expected Result:***
Branch name should display properly (my example should be `MQA-145`)

***How to fix (workaround)***
Click twice (collapse and open again) on the parent directory for the respective directories showing this issue and the trimming will be addressed properly.

***Note(s):***
I faced this issue for some branches and couldn't stand for a one scenario.
This occurs on branched aligned/ahead/behind `master`

***Intellij***
![screen shot 2018-11-05 at 9 20 14 am](https://user-images.githubusercontent.com/16471809/47994435-a7bef680-e10b-11e8-8465-67cac5d9a8c2.png)

**Comment by zielu** [comment]
Cannot reproduce anymore
