### ISSUE TITLE
Question: is it possible to auto-fetch parent branch?

### ISSUE THREAD

**Issue by sabat24** [zielu/GitToolBox#113]
When using gitflow or feature branch approach the most important thing I want to know is that if the parent branch is update or how many commits I'm behind on my feature branch. It allows me to make a decision about rebasing current branch or pull parent branch before I merge my branch into it. What's more in such approach feature branches are almost never tracked so there is nothing to fetch from remote. 
So is it or will it be possible to auto-fetch parent branch and receive information about it's status instead of or additionally to current branch?

**Comment by zielu** [comment]
Auto-fetch already updates all branches. What is needed here is to display status of more than one branch.

**Comment by sabat24** [comment]
Yes, displaying the status of another branch was my proposal. In my use case selecting a branch which status I want to display will be enough. I'm not sure what is easier to do and better to display. For example Jetbrains VCS plugin allows you to select which branch is shown in log: HEAD or selected by you. So after checkout you can still see the pre-selected branch.

**Comment by zielu** [comment]
In "selected mode" let's assume that master in 2 commits ahead from point you pulled out feature branch and you have 3 commits on feature branch. 

In such scenario you would like to see something like 2 commits behind / 3 commits ahead ?
Also for visual indication that you are in this mode project view should show instead of [feature] 2 // 3 [feature > master] 2 // 3

**Comment by sabat24** [comment]
Yes. It would solve my case perfectly.

**Comment by zielu** [comment]
Note to self: It will be pretty easy with current approach to ahead / behind calculation:
`git rev-list <ref/hash on current branch>...<ref/hash on parent remote branch> --left-right`
Example:
` git rev-list HEAD...origin/master --left-right`

**Comment by zielu** [comment]
Done in 183.3.0
