### ISSUE TITLE
GitToolBox shows way too many password prompts for SSH pubkey passphrases

### ISSUE THREAD

**Issue by rulatir** [zielu/GitToolBox#120]
I am receiving way too many password prompts from GitToolBox regarding SSH pubkey passphrases. I am using a pubkey with a passphrase to authenticate to GitHub. When I launch the IDE, I eventually receive password prompts from GitToolBox when it tries to fetch repositories, which are several, as I am using a multi-module project (btw. plugin developers, PLEASE test your plugins in multi-module projects!).

I expect to receive only ONE password prompt per pubkey, and I use the same pubkey for all GitHub repos, so effectively I only expect one prompt.

What actually happens: GitToolBox simultaneously pops up password prompts for every repository connection that uses the pubkey. After I fill the passphrase in the first prompt, a yet additional prompt for the master password of the IDE's password store is shown because GitToolBox tries to store the pubkey passphrase I just entered. However other prompts that are already shown and waiting for my interaction will not benefit from the passphrase being stored in the IDE's password store; I must still enter the passphrase in every last one of them!

Ideally I would expect GitToolBox to try to open the IDE's password store the first time it *needs* a passphrase. This would cause the password store's master password prompt to be shown first. Should then GitToolBox be successful in retrieving the required passphrase from the password store, it shouldn't show any prompts of its own whatsoever.

**Comment by zielu** [comment]
This is side-effect of custom concurrent fetch implementation. It should go away when I switch to using new IntelliJ's implementation

**Comment by zielu** [comment]
Fixed in 183.1.1 required IntelliJ 2018.3.3
