### ISSUE TITLE
Support for 2019.1 EAP

### ISSUE THREAD

**Issue by zielu** [zielu/GitToolBox#122]

**Comment by aaronols** [comment]
I am using IntelliJ 2019.1 EAP actively now and I kindly wanted to ask when the 191.* version line of the plugin will be released on the JetBrains Plugin Portal.

**Comment by zielu** [comment]
@aaronols It's already available in EAP channel. You can switch by following this steps: https://github.com/zielu/GitToolBox#eap-builds
