### ISSUE TITLE
Darken inline blame foreground for Darkula theme

### ISSUE THREAD

**Issue by zielu** [zielu/GitToolBox#127]
`#707070` looks much better

**Comment by aaronols** [comment]
I agree that the color `#707070` looks better.
However the color `#666D75` used by IntelliJ for Debugger Inline Values in Darcula theme is very similar to this one.
Is it necessary to make the two inlined information types distinguishable by color? The inline debugger variables are always to the left of the inline blame.
One could also make the argument that when debugging, inline values are the more important information and therefore the inline blame appearing behind all inline debugger variables in (almost) the same color is acceptable.

**Comment by zielu** [comment]
I don't have preference whatever is easier on the eyes - let's go with `#666D75` and it's up the user to configure it however he likes

**Comment by zielu** [comment]
Done in 183.4.0
