### ISSUE TITLE
my not be an issue

### ISSUE THREAD

**Issue by burkeallen** [zielu/GitToolBox#128]
this may not be an issue just, but rather just not a full understanding of the tool.

sometimes in the IDE, instead of up and down arrows next to a repository directory name,  I get a bunch of what looks like commit timestamps or some other number possibly related to commits?

![gittoolbox](https://user-images.githubusercontent.com/6885075/52871422-04bd4600-3118-11e9-85fb-1f399023b04e.png)

can you shed some light as to what this is or why this is happening?

thank you.

**Comment by zielu** [comment]
Hi, those are tags on current commit.

**Comment by burkeallen** [comment]
thanks for the explanation, when do they go away and the arrows return?

**Comment by zielu** [comment]
Arrows are on extreme far and right. You can reorder/hide elements in Settings > GitToolbox Global > Project View tab

**Comment by zielu** [comment]
@burkeallen have you tried changing setting I mentioned?

**Comment by zielu** [comment]
No response from reporter
