### ISSUE TITLE
Globally disable commit dialog completion

### ISSUE THREAD

**Issue by fxnn** [zielu/GitToolBox#129]
As a (very happy) user of IntelliJ's `Insert selected suggestion by pressing space, dot, or other context-dependent keys` setting, the commit dialog completion s super enerving for me. 

I cannot type a regular commit message like `update to Maven 3.6.0`, because afterwards the message reads `update to Maven 3master.6master.0`. Instead, I must type `3`, then `ESC` to close the completion window, then `.` to close the completion window, then `6` to close the completion window...

Now, this wouldn't bother me, as I don't need that feature anyways, I'd be happy if it wasn't activated at all. Unfortunately, it _is_ activated by default for every new project I checkout. As I happen to work on quite a few different projects, that's opening Settings and disabling that option every time again.

Therefore, I suggest to add a global switch to enable/disable the commit dialog completion.

Besides, thank you for this great plugin!

**Comment by zielu** [comment]
You can disable for new projects in default project settings.

**Comment by fxnn** [comment]
@zielu Oh cool, thanks a lot, that helps immediately! I didn't new that part of IntelliJ.

From my point of view, we can close the ticket.

However, a minor issue is: if I wanted to use commit dialog completion, I still couldn't. Here, it would help if the completion wouldn't open automatically while typing, but only on demand, when pressing `[Ctrl]+[Space]`. I can file a separate issue for this, but as it's no real issue to me, I leave the decision to you.

**Comment by zielu** [comment]
Activating on demand makes lots of sense. If you can create issue it would be great.

**Comment by fxnn** [comment]
Created #130, thus closing this issue.
