### ISSUE TITLE
Activate commit dialog completion on demand

### ISSUE THREAD

**Issue by fxnn** [zielu/GitToolBox#130]
As a (very happy) user of IntelliJ's `Insert selected suggestion by pressing space, dot, or other context-dependent keys` setting, the commit dialog completion is quite enerving for me. 

I cannot type a regular commit message like `update to Maven 3.6.0`, because afterwards the message reads `update to Maven 3master.6master.0`. Instead, I must type `3`, then `ESC` to close the completion window, then `.`, then `ESC` to close the completion window, then `6`, then `ESC` to close the completion window...

This wouldn't be an issue if the completion wouldn't be triggered automatically when typing, but only after pressing `[Ctrl]+[Space]` (or whatever shortcut is assigend to `Code > Completion > Basic`).

Therefore I suggest adding an option to switch between automatic and on-demand completion. In IntelliJ, that's a checkbox called `Show suggestions as you type`. Without knowing the APIs I guess we talk about overriding this behaviour.

**Comment by zielu** [comment]
Done in 183.4.0

**Comment by fxnn** [comment]
Thanks, works like a charm!
