### ISSUE TITLE
Change how we see author's name inline and also on PHPStorm's  annotate panel

### ISSUE THREAD

**Issue by phiter** [zielu/GitToolBox#131]
I've installed the extension and I've noticed that the author name on the inline editor is showing the second name. Like mine, it's showing Fernandes

![image](https://user-images.githubusercontent.com/12252332/53955559-17dc8980-40b8-11e9-9c1a-19b0be9df5e5.png)

Here in Brazil it's uncommon to call people by their surnames, we use the first name more often. 

So my request would be to allow us to choose how we show the author's name. Perhaps three options:

- First name
- Second name
- Full name

That would make it easier for us :)

**Comment by zielu** [comment]
Hi, in plugin version that will come with 2019.1 there are options for author and date. Back-porting them should be relatively easy.

Unfortunately there is nothing I can do about annotate panel.

**Comment by zielu** [comment]
Done in 183.5.0
