### ISSUE TITLE
Incompatible with Intellij Ultimate 2018.3.5

### ISSUE THREAD

**Issue by gw212** [zielu/GitToolBox#136]
I've been getting this for a few versions now and it doesn't seem to go away.  I'm using Intellij Ultimate 2018.3.5, build # IU-183.5912.21.  When I go to install the plugin (which I uninstalled when it said it was incompatible to try and reinstall it), it tells me that it is Incompatible with the current IntelliJ IDEA version.  Any thoughts on what I can do to try and resolve this or what other info you might need.

**Comment by zielu** [comment]
I can install latest 183.5.0 from Settings> Plugins without any issues on 2018.3.5
Which version did you try to install? 191.x ? If so it is compatible with 2019.1

**Comment by gw212** [comment]
I have tried v183.5.0 from the plugin marketplace and tried installing from the zip files for versions 183.1.1, 183.3.0, 183.4.0, 183.5.0, and 191.0.10.

The only thing I'm seeing in my idea.log file is the following:

> 2019-03-27 14:16:41,801 [601546094]   INFO - Settings.impl.PluginDownloader - Plugin zielu.gittoolbox is incompatible with current installation (since:183.5153.8 until:183.*)

**Comment by zielu** [comment]
Which OS are you on?

**Comment by gw212** [comment]
Windows 10 Pro Version 10.0.17134 Build 17134

**Comment by zielu** [comment]
I cannot reproduce it neither on Windows nor on macOS. You could consider trying with fresh install.
Rename <User_Home>/.IntelliJIdea2018.3 to something else, go through setup and try installing from Marketplace. If it works then your install is somehow broken :/

**Comment by gw212** [comment]
I updated to 2019.1, ran into a lot of issues immediately, and downgraded back to 2018.3 (without having to remove files).  Was able to get the plugin to install now.  Thank you for taking the time out to try and troubleshoot with me.
