### ISSUE TITLE
Turn off inline blame?

### ISSUE THREAD

**Issue by rulatir** [zielu/GitToolBox#137]
How do I turn off inline blame altogether? I find text appearing and disappearing right next to my visual focus as I navigate a file EXTREMELY distracting.

If there is a setting for this, please expose it in the editor context menu.

**Comment by zielu** [comment]
Settings > Other settings > GitToolbox Global

**Comment by rulatir** [comment]
Thanks, I was looking in what seems to be built-in Git support settings instead of GitToolbox.

**Comment by rulatir** [comment]
I might find this feature useful when investigating regressions, but not all the time. I think it would be nice to have a key-bindable menu command for toggling it. Should I post a separate FR?

**Comment by zielu** [comment]
I like that idea, please open one :smile:

**Comment by zielu** [comment]
@rulatir FR tracked under #138
