### ISSUE TITLE
Git stat icons are not shown correctly

### ISSUE THREAD

**Issue by wdlb** [zielu/GitToolBox#14]
My setup:
- Ubuntu 14.04
- Webstorm 16.01
- GitToolBox 16.0.1

My issue:
The icons next to the git stat information that indicate the number of commits you are behind or ahead are not shown correctly. This is the case both in the status bar in the bottom as next to the project root folder in the project tab. I attached a screenshot indicating the issue.

It would be great if you would be able to help me out, thanks in advance!

![icons not shown correctly](https://cloud.githubusercontent.com/assets/3765473/14139309/89d8ea6c-f672-11e5-8b92-92a262a7130b.png)

**Comment by zielu** [comment]
It's a problem with your current font used in IDE. Either:
- change it: Settings > Appearance > Override default fonts
- use other presentation mode: Settings > Git ToolBox > Arrow heads or Text

**Comment by wdlb** [comment]
I switched to Presentation mode: Text, because I didn't find a font that had the arrows and that was aesthetically pleasing enough.

Thanks a lot for your fast help!
