### ISSUE TITLE
GitToolBox interferes with IntelliJs annotation sidebar when Relative Line Numbers Plugin is installed

### ISSUE THREAD

**Issue by aaronols** [zielu/GitToolBox#140]
IntelliJ itself has an "Annotate" feature for version-controlled files which can be accessed by right-clicking the line number column and selecting "Annotate".
IntelliJ then displays a colored column with the Commit Author and relative date for each line (as well as other configurable information) to the right of the line numbers.
When the feature is enabled, a checkmark is displayed besides its name in the context menu.
Since updating to Version 191.0.12 of this plugin, The "Annotate" feature is enabled by default as soon as any inline blame has been displayed.
To view the "Annotate" column it is necessary to first disable the Annotate feature (which results in no change to the visible elements on screen, only the checkmark beside the feature name is no longer visible in the context menu.
Only then can the "Annotate feature" be enabled again and actually displays the annotation column.
The column is hidden again as soon as any line in the editor is selected (probably because painting the inline blame for the selected line then interferes with IntelliJs Annotation).

It is not desirable for me to have this plugin interfere with IntelliJs Annotate feature.
I would like to use IntelliJs Annotate feature and the inline blame both independently of each other.

To my knowledge IntelliJs "Annotate" and the inline blame from this plugin have worked independent of each other before so I assume that this behaviour has been introduced recently.

I can provide a screen-recording gif for clarification if that helps.

**Comment by zielu** [comment]
Hi, 

Please provide the recording because I cannot reproduce this and it works as you would expect.

What is interesting is that in 191.012 (which is EAP) they are truly independent because custom annotation implementation is used.

**Comment by aaronols** [comment]
Maybe the fact that the inline blame renderer is an custom annotation is why IntelliJ treats an editor with inline blame as "having Annotations enabled".

The recording is attached as a zipped mp4 to save space.

[gittoolbox-issue-140-demo.zip](https://github.com/zielu/GitToolBox/files/3044017/gittoolbox-issue-140-demo.zip)

**Comment by zielu** [comment]
In the meantime two things: does disabling inline blame or disabling plugin help?

**Comment by aaronols** [comment]
I was able to identify the culprit in this case: The [Relative Line Numbers Plugin](https://plugins.jetbrains.com/plugin/7414-relative-line-numbers). I've used it on some occasions together with the IdeaVim plugin.

When fully enabled, the relative line numbers plugin replaces the IntelliJ Annotation bar with its own relative line numbers and the behaviour displayed in the screen recording is present.

The plugin has its own "Enable" switch. So for the screen recording, the following two options were set:
- Settings -> Plugins -> Relative Line Numbers -> checked/loaded = true
- Tools -> Relative line numbers plugin -> Enabled = false


With the relative line numbers plugin fully enabled, the behaviour seen in the screen recording occurs (even without GitToolBox).

With GitToolbox 191.0.10 and the relative line numbers plugin loaded but disabled, this results in the desired separation between IntelliJs annotation bar and the inline blame functionality.

With GitToolbox 191.0.12 and the relative line numbers plugin loaded but disabled, the behaviour in the screen recording occurs.

As a workaround, the relative line numbers plugin can be disabled.
GitToolBox is more important and useful to me than the relative line numbers so disabling said plugin is an acceptable solution for me.

**Comment by zielu** [comment]
I looked at Relative Line Numbers code and it's doing strange things to annotations. 191.0.12 no longer calls intellijs annotation apis so it seems in 191.0.10 some interference actually fixed what Relative Line was breaking.
I do not plan to go back to intellij annotations because they are 3x slower than current implementation optimized for inline case.

**Comment by aaronols** [comment]
I agree with your decision. Thanks for looking into this issue.
