### ISSUE TITLE
Enabling 'blame' features cause UI to freeze on loading PHP file

### ISSUE THREAD

**Issue by magus424** [zielu/GitToolBox#142]
Enabling blame display either inline or in status bar results in a freeze on "Computing annotations for <filename>.php" any time I open a file; even if said file contains absolutely nothing but "<?php"

All other 3rd party plugins are disabled; only GitToolbox enabled.

Plugin version: v191.0.10
PHPStorm version:
```
PhpStorm 2019.1
Build #PS-191.6183.95, built on March 27, 2019
JRE: 1.8.0_202-release-1483-b39 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
```

**Comment by zielu** [comment]
Please try newly released 191.1.0. It has customized blame implementation.

**Comment by magus424** [comment]
I don't see any such update in the plugin marketplace; is there a way for me to manually update?

**Comment by zielu** [comment]
Should be up, but you can download from https://plugins.jetbrains.com/plugin/7499-gittoolbox/versions and use Settings > Plugins > Cog icon > Install from disk

**Comment by magus424** [comment]
Restarted PHPStorm and it picked up the new version, and the new version does not present the freeze behavior! :)

**Comment by zielu** [comment]
Glad to hear that !

**Comment by magus424** [comment]
Update: it fixed most smaller files, but some larger files still freeze the UI; I also received a long pause when closing about a dozen tabs at one with Ctrl+Shift+W

**Comment by zielu** [comment]
Plugin has extensive metrics available over JMX. Could you connect to IDE with for example VisualVM, open zielu.gittoolbox.<project name> group and get values from following metrics:
- blame-cache.get
- blame-cache.load
- blame-document-line
- blame-editor-painter
- blame-file

**Comment by magus424** [comment]
I managed to get the JDK installed and VisuamVM open and connected to PHPStorm, but I don't see anywhere to pull arbitrary metrics like that; do I need some sort of plugin?

**Comment by zielu** [comment]
Hmm, maybe you need VisualVM-MBeans - I don't remember if it was included or not.

![image](https://user-images.githubusercontent.com/464103/55991761-4c40f800-5cab-11e9-901c-a9dda7f3278f.png)

**Comment by magus424** [comment]
Yep, I just found that and installed it, and I see the metrics now.

> * blame-cache.get

![image](https://user-images.githubusercontent.com/384053/55991965-483bb880-5c60-11e9-8e61-41c6e43f6a97.png)

> * blame-cache.load

![image](https://user-images.githubusercontent.com/384053/55991979-54277a80-5c60-11e9-95cf-0f1c6ded68e3.png)

> * blame-document-line

![image](https://user-images.githubusercontent.com/384053/55992019-66091d80-5c60-11e9-9a46-36a1b695eb7b.png)

> * blame-editor-painter

![image](https://user-images.githubusercontent.com/384053/55992025-6d302b80-5c60-11e9-9481-ec03814ee9df.png)

> * blame-editor-painter-get-info

![image](https://user-images.githubusercontent.com/384053/55992042-74efd000-5c60-11e9-86b5-514e51e36171.png)

> * blame-file

![image](https://user-images.githubusercontent.com/384053/55992059-7caf7480-5c60-11e9-91cd-d985b2a1be93.png)

**Comment by zielu** [comment]
I think I know what is wrong. blame-file should have count 0 unless you have statusbar blame enabled, however calls occur even with disabled statusbar.

Even then statusbar does not use async loading like editor blame there are things to fix...

**Comment by magus424** [comment]
I may have turned both forms of blame on when checking the previous slowdown.

I can't check right this second as I've entered a meeting.

**Comment by magus424** [comment]
Nope, I did not leave both on; only have inline blame enabled.

**Comment by zielu** [comment]
Could you switch to EAP channel as described here: https://github.com/zielu/GitToolBox#eap-builds

I made some changes that should prevent costly calls being made when statusbar is disabled so it should improve situation a lot.

**Comment by zielu** [comment]
@magus424 does 191.1.2 help with the freezes?

**Comment by magus424** [comment]
@zielu sorry, I was unable to find time to try it on Friday :)

Switched to EAP today and re-enabled the inline blame and it does seem significantly better. There was some pausing when I first enabled the plugin, but after that, opening/closing large files never seemed to freeze the UI anymore.
