### ISSUE TITLE
Asks for creds constantly

### ISSUE THREAD

**Issue by bbakermmc** [zielu/GitToolBox#143]
Can you please fix the plugin so it doesn't keep asking for creds every application/project opening.  It keeps generating access tokens for no reason.

**Comment by zielu** [comment]
@bbakermmc I'm using IDE apis to do auto-fetch so you can check if it also asks if you run VCS > Git > Fetch.

**Comment by bbakermmc** [comment]
@zielu I think the issue is on the VSTS plugin, doesn't appear to be caching the access token.
