### ISSUE TITLE
Git blame history for selected lines

### ISSUE THREAD

**Issue by gberche-orange** [zielu/GitToolBox#144]
It is often useful to navigate to many git commits that affected the current line in editor and not just the last one. 

See https://stackoverflow.com/a/32396682 which mentions

> git log -L 15,23:filename.txt
> means "trace the evolution of lines 15 to 23 in the file named filename.txt".

Such suport in GitToolBox would open the version control tab and would display the related gitblame subset of git commits (and other unrelated git commits would be filtered out)

I did not find a way to use gittoolbox for such use-case. Did I missed it ?

Is this rather something I should suggest onto intellij idea core git support ?

**Comment by zielu** [comment]
Afair there should be IntelliJ built-in action in context menu when you select range of text.

**Comment by zielu** [comment]
What I will add in future is some form of highlight of all lines changed in commit currently under caret.
