### ISSUE TITLE
Branch name completion displaying when editing database fields

### ISSUE THREAD

**Issue by Perturbatio** [zielu/GitToolBox#147]
Using the database browser in PHPStorm, the branch name auto-complete keeps showing when editing fields.

This is unlikely to ever be a helpful feature in this context.  AFAIK, It's only started happening recently.

![image](https://user-images.githubusercontent.com/1007702/57857197-86d80c00-77e6-11e9-9b98-ab5a716a126a.png)

**Comment by zielu** [comment]
Done in 191.2.1

**Comment by Perturbatio** [comment]
Thank you for the speedy fix :)
