### ISSUE TITLE
android studio 3.4.1

### ISSUE THREAD

**Issue by Nothing-Works** [zielu/GitToolBox#152]
For some reason, I do not get the latest version on android studio 3.4.1 Windows.
![111](https://user-images.githubusercontent.com/18606648/58615729-e8809600-830f-11e9-8d5c-0b59b35cc6aa.png)

Is this my PC problem? Can I have it without going to the website to manually download it?

## Update
it's same for mac
<img width="1108" alt="Screen Shot 2019-05-30 at 21 59 01" src="https://user-images.githubusercontent.com/18606648/58625363-723b5e00-8326-11e9-91a6-2a44dd36ca74.png">

**Comment by zielu** [comment]
Looks like Android Studio is based on Idea 2018.3. Newer versions require Idea 2019.1, I'll take a look how hard it would be to rebuild latest release with older one.

**Comment by Nothing-Works** [comment]
@zielu thank you for your help, it's an amazing tool !!! let us know if you have any update, please.

**Comment by zielu** [comment]
@Nothing-Works you can try test release by switching to EAP plugin channel, see https://github.com/zielu/GitToolBox#eap-builds

**Comment by Nothing-Works** [comment]
@zielu it works perfect !!!
![Untitled](https://user-images.githubusercontent.com/18606648/58680659-d872c000-83bc-11e9-8bc1-2963b5c03b1a.png)

hoping to see it in non-EAP version soon, again thank you so much for your hard work.

**Comment by zielu** [comment]
Stable 183.6.1 released
