### ISSUE TITLE
fetch hangs up idea

### ISSUE THREAD

**Issue by saaadel** [zielu/GitToolBox#154]
I often run the "fetch" operation manually, from GitToolbox's dropdown menu on bottom.
This hangs up the Intellij IDEA, if I have large remote changes (large chunks and maybe not best bandwidth).
Could you change it, do it in async mode maybe?

**Comment by zielu** [comment]
Which plugin version you are on ?

**Comment by saaadel** [comment]
v191.2.2

**Comment by zielu** [comment]
Done in 191.2.7
