### ISSUE TITLE
"Git Stat" in status bar shows ahead of remote branch, but local and remote in sync

### ISSUE THREAD

**Issue by ksilz** [zielu/GitToolBox#155]
I'm using GitToolBox v191.2.7 in IntelliJ Ultimate 2019.1.3 on macOS 10.14.5. The GitToolBox "Git Stat" in the status bar shows me wrongfully that I'm 94 commits ahead of the remote branch &mdash; my local is actually in sync with my remote branch. No matter what I try (switching branches, refreshing the status or fetching in the "Git Stat"), the number of commits in "Git Stat" stays there and increases with every commit.

Here is a little video of this issue. Please see the "94 ahead" in "Git Stat" in the status bar.

![2019-06-13_13-52-29 (2)](https://user-images.githubusercontent.com/1061209/59430841-92b5ee80-8de3-11e9-832e-2ca0da79ef24.gif)

**Comment by zielu** [comment]
From what I see besides Git: it looks like you are on feature branch.
There is a feature that shows ahead commit counts relative to "parent" branch. In essence how many commits your branch is ahead relative to branch from which it was created and how many commit it's is behind from remote.
You can tell that by branch name being displayed like: phase-2-sprint-7 > master 

By default it's in Auto mode, but you can change that in Settings > Git ToolBox Project > Parent branch mode: Tracked remote

**Comment by ksilz** [comment]
Yep, that was exactly it. Maybe make _Tracked remote_ the default?
