### ISSUE TITLE
Configuratble date format

### ISSUE THREAD

**Issue by timdingo** [zielu/GitToolBox#160]
Please make the date format configurable in the git blame output.
Context: mm/dd/yyyy is only used in the USA. The SI standard for date is yyyy-mm-dd but lots of other different notations are used around the world. A formatted date without explanation can be highly confusing.

**Comment by zielu** [comment]
Hi, which plugin version are you on ? I use built-in IntelliJ formatters so just to confirm - if you invoke Annotate action do dates also look confusing ?

**Comment by timdingo** [comment]
Hi, I'm using v191.2.7 in PyCharm. I've taken screenshots to show you how it tools on my end, perhaps that'll make it easier on you.
![image](https://user-images.githubusercontent.com/6596818/62352049-7e4ec200-b507-11e9-9344-3cba9d0b54b3.png)
![image](https://user-images.githubusercontent.com/6596818/62352136-b6560500-b507-11e9-9033-20d8189797d4.png)

**Comment by zielu** [comment]
According to https://en.wikipedia.org/wiki/Date_format_by_country there are 3 widely used formats.
There will be 4 options available DMY, YMD, MDY all will include time in 24 and forth one 'auto' that will work as it does now (based on locale).

**Comment by zielu** [comment]
Done in 192.2.2, requires 2019.2 IDE release
