### ISSUE TITLE
Add non-commited files dialog and status

### ISSUE THREAD

**Issue by s3r6** [zielu/GitToolBox#161]
Please add feature to check if there are any changed files.

- Display status near branch stats in status bar like `1 modified, up-to-date` where `N modified` is the counter of changed files staged for commit. `No changes, up-to-date` if there are no such files.
- Add round indicator to status bar before status message like :large_blue_circle: `1 modified, up-to-date` which helps to detect if any files left for commit faster before reading status. Colors: gray (off) for no files staged / commits not pushed, blue if any files staged / commits not pushed.
- On project close open dialog `You have N uncommited files / not pushed commits left, proceed with project closing?` : `OK`,`Do not close` if there are any commits not pushed to remote or any files staged but not commited.
- Allow this checks to be disabled in settings for those who don't want it.

**Comment by zielu** [comment]
Released EAP channel in 193.3.0. Still missing project closed dialog

**Comment by zielu** [comment]
Released to Stable in 193.3.2

**Comment by zielu** [comment]
Project close notification will be tracked in #190

**Comment by s3r6** [comment]
Tested, works OK. Thanks a lot, you saved me from hundreds of Local changes tab openings.
