### ISSUE TITLE
Support for blame.ignoreRevsFile

### ISSUE THREAD

**Issue by terrdavis** [zielu/GitToolBox#163]
I'm using the new (git 2.23) blame.ignoreRevsFile feature, and it looks like the inline blame doesn't ignore the rev like the command line blame does.  

Can you support this/is there something I'm missing?

https://git-scm.com/docs/git-blame#Documentation/git-blame.txt---ignore-revs-fileltfilegt

**Comment by zielu** [comment]
@terrdavis so it does not seem to work when you specify blame.ignoreRevsFile in git config file ?

**Comment by terrdavis** [comment]
I just checked again. It worked, and once I removed the revision from the file, closing and opening the project (not restarting pycharm) forced it to update.

This was with a second project, but with the first, inline blame does not show up at all anymore. I tried to Invalidate Caches and Restart, but that didn't work. 
Re-cloning the repo worked, but I'd prefer not to have to shuffle my workspace around. Is there anything else I can do for this?

**Comment by zielu** [comment]
I'll need to check if there are any logs that could lead to cause.
Besides that support can be implemented in a way to force inline blame update when repository-local rev files change.
Implementing monitoring for higher configuration levels is too much effort but statusbar Git Stat -> Refresh action can be extended to force cache invalidation and to not make project reopen mandatory

**Comment by zielu** [comment]
@terrdavis there is minimal support present now. When you edit revs file you can use VCS > GitToolBox > Refresh blame to force inline blame recalculation.
