### ISSUE TITLE
GitToolBox vs Git ToolBox causes confusion when accessing settings through Actions search

### ISSUE THREAD

**Issue by terrdavis** [zielu/GitToolBox#164]
Also created issue for jetbrains: https://youtrack.jetbrains.com/issue/PY-37776

Making this selection:
![Actions Search](https://user-images.githubusercontent.com/16829776/64037557-ba774180-cb0a-11e9-8b2e-69835c2c7b17.png)

ends up here
![Selection Result](https://user-images.githubusercontent.com/16829776/64037591-d4188900-cb0a-11e9-947b-ed8f47345e95.png)

**Comment by zielu** [comment]
Good catch - it needs to be consistent everywhere

**Comment by zielu** [comment]
Done in 192.2.2
