### ISSUE TITLE
How to set parent branch from another repo?d

### ISSUE THREAD

**Issue by hu6360567** [zielu/GitToolBox#165]
I have 2 repos in my local git.
One is `origin` where my codes pushed to, the other one is `upstream` where the team repo is.

My normal workflow is 
1. fetch from upstream/dev_branch
2. merge into my local dev_branch
3. push to origin/dev_branch
4. make a Merge Request from origin to upstream

I trie to set parent branch to `upstream/dev_branch` which shows `no remote` in statusbar.

**Comment by zielu** [comment]
Hi @hu6360567 do I understand correctly you have one repo with two remotes ?
If you have 2 separate repos then that is not something I will implement at this moment.

For two remotes in one repo case code assumes right now that parent branch is in the same origin as current remote.

**Comment by zielu** [comment]
Done in 192.3.0
