### ISSUE TITLE
 Auto fetch failed; cannot open .git/FETCH_HEAD: Invalid argument

### ISSUE THREAD

**Issue by thilina-esoft** [zielu/GitToolBox#169]
`cannot open .git/FETCH_HEAD: Invalid argument`

I get above error message when i try to pull the repository.
I'm on windows 10 machine with PHPSTORM 2018.3.

Workaround - I deleted `FETCH_HEAD` file under the `.git` directory and works fine. But again when i trying to pull, the same error displays thus preventing me form pulling.

This case as same as any git operations, such as commit, merge and etc. 
Only difference is the file. As for example when committing it shows an error as below

`cannot open .git/COMMIT_EDITMSG: Invalid argument`

**Comment by zielu** [comment]
@thilina-esoft what about if you run git fetch from command line

**Comment by thilina-esoft** [comment]
Also same,
![image](https://user-images.githubusercontent.com/52784334/66016450-5b835e80-e4f4-11e9-9233-c7420026d463.png)

**Comment by zielu** [comment]
Looks like some general issue with your setup then, nothing plugin-specific

**Comment by thilina-esoft** [comment]
Alright, I'll check with git then. Thank you for your support. (y)
