### ISSUE TITLE
Please provide binary releases too

### ISSUE THREAD

**Issue by gdubicki** [zielu/GitToolBox#17]
I have just found this nice plugin: https://plugins.jetbrains.com/plugin/7802?pr=idea ..but I can't install it without installing your plugin first but it's troublesome as you don't provide a binary JAR in release zips/targzips. Please provide them, at least for the current version.

**Comment by zielu** [comment]
Hi,
 IDE should also install my plugin, but I've already included the same features and do not have refresh problem.
