### ISSUE TITLE
Git blame doesn't display the full username

### ISSUE THREAD

**Issue by C0D3-M4513R** [zielu/GitToolBox#170]
Behavior:
Git blame doesn't display the Username properly, when it has a space in the middle.
If the username is for example "Test Name" it will only display "Test" in the editor and status bar.
If you click on the status bar component though it shows the author correctly as "Test Name".
Expected Behavior:
It should display the full author's name like "Test Name" everywhere.
Steps to reproduce:
Commit something with a username, that has a space in it.

**Comment by zielu** [comment]
@C0D3-M4513R please check Preferences > GitToolBox Global > Blame. There are 2 settings how author name is displayed and default is Last Name.
For "Test Name" you should have "Name" unless it's changed to First Name then it would show "Test".

Also plugin version could be useful.

**Comment by C0D3-M4513R** [comment]
The version is 192.3.0 , but as you stated under that Setting you can set it to everything, so thanks!

**Comment by pulatnazarov** [comment]
> @C0D3-M4513R please check Preferences > GitToolBox Global > Blame. There are 2 settings how author name is displayed and default is Last Name. For "Test Name" you should have "Name" unless it's changed to First Name then it would show "Test".
> 
> Also plugin version could be useful.

i could not find 2 setting in goland intellij, how can i change and set full name not only last name or name

**Comment by zielu** [comment]
@pulatnazarov all options are there in current version of plugin
<img width="485" alt="image" src="https://user-images.githubusercontent.com/464103/194232253-da8970b5-cd69-45d4-a8e4-334b1352c1ca.png">
