### ISSUE TITLE
[Question] Is it possible to disabled the blame?

### ISSUE THREAD

**Issue by tomasnorre** [zielu/GitToolBox#172]
Hi,

Thanks for a really great plugin. 

Is it possible to disabled the git blame part? Don't like to have the git-blame on every single line that I click, if I needed I'll use the "normal" git-blame.

![Screenshot 2019-10-14 at 12 53 22](https://user-images.githubusercontent.com/1212481/66746373-f2033880-ee81-11e9-9f4d-bb5d82e56ed3.png)

**Comment by zielu** [comment]
Hi, you can disable it in Settings > GitToolbox Global
