### ISSUE TITLE
Git branch switcher (switch among recent branches)

### ISSUE THREAD

**Issue by gberche-orange** [zielu/GitToolBox#173]
As a user, in order to switch between the 2 or 3 recent branches I'm working on, I need the "git branch dialog" to focus keyboard on a "recent branch" section, or to the favorite section.

This would be similar to the great [frame switcher plugin](https://plugins.jetbrains.com/plugin/7138-frame-switcher)

> Switch or reopen a project - ALT + F2 (repeat for selecting a next item) 

Currently, the dialog focuses on the middle of the screen, requiring use of the mouse or branch keyword

![image](https://user-images.githubusercontent.com/4748380/67017631-55979b00-f0fa-11e9-8902-533974dd97fc.png)

**Comment by zielu** [comment]
Done in 193.7.0

**Comment by gberche-orange** [comment]
this great, thanks a lot @zielu!

As a note for readers of this issue, the default shortcut for MacOs is `shift meta R` (did not trigger on my Ubuntu box)

**Comment by zielu** [comment]
I actually removed default shortcuts because they were conflicting with built-in ones :/
