### ISSUE TITLE
Extra file "git_toolbox_prj.xml" being created

### ISSUE THREAD

**Issue by eegeeZA** [zielu/GitToolBox#174]
After updating to v192.4.0, I have started seeing a file called `git_toolbox_prj.xml` created with the following contents:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="GitToolBoxProjectSettings">
    <option name="version" value="2" />
  </component>
</project>
```

I have traced it down to the recent migration to Kotlin. I cannot see a menu option to configure the location of the config file, nor prevent the config file from being created.
https://github.com/zielu/GitToolBox/blob/aeeb2f10e97885b90a4b89ec75009b02205f4bcf/GitToolBox/src/main/kotlin/zielu/gittoolbox/config/GitToolBoxConfigPrj.kt#L13

Is the intention for this file to be committed to the Git repo? If not, it might be good to add it to the exclusion list on [http://gitignore.io/api/intellij](http://gitignore.io/api/intellij).

**Comment by zielu** [comment]
This is regular config file that is created under .idea. If you did not have it previously you were using default settings. 
It is created because as side effect of data format migration I added.
If you commit your .idea directory to repository (which I for example never do) then it should be there along with other config files from .idea

**Comment by zielu** [comment]
Fixed in 192.4.1

**Comment by zielu** [comment]
You can just delete that file before opening project and it will no be created anymore.

**Comment by eegeeZA** [comment]
Thanks for the quick response! I received the plugin update notification and installed it. The file is no longer being created.

**Comment by zielu** [comment]
One more release because there was a bug in migration code. 192.4.2 is the proper one.
