### ISSUE TITLE
WSL: System Errors referencing git-remote-https.exe

### ISSUE THREAD

**Issue by k3n** [zielu/GitToolBox#175]
Win10 1809 (17763.832)
GitToolBox v192.4.2

WebStorm 2019.2.3
Build #WS-192.6817.13, built on September 23, 2019
Runtime version: 11.0.4+10-b304.69 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1960M
Cores: 12
Registry: 
Non-Bundled Plugins: com.arcticicestudio.nord.jetbrains

---

Upon installation and restart, there's a series of 4 system-modal dialogs presented, each mentioning `git-remote-https.exe` and a DLL.

Example from event viewer:

```
Application popup: git-remote-https.exe - System Error : The code execution cannot proceed because libcurl-4.dll was not found. Reinstalling the program may fix this problem. 
```
DLL's:

* libcurl-4.dll
* libiconv-2.dll 
* libintl-8.dll 
* libintl-8.dll

After dismissing them, this appears in the IDEA event log:

```
Auto fetch failed
```

I'm not very familiar with the features yet, but at least some of them appear to work still; namely, the inline blame info is present.

**Comment by zielu** [comment]
Hi, what happens when you run 'git fetch' from cmd or when you execute Git / Repositories / Fetch ?
Plugin is using internal IDE support for calling Git commands so I would expect that regular fetch is also broken.

**Comment by k3n** [comment]
Why yes, you're very much correct. This is a new install and I typically use Git CLI, but wanted to add some enjoy using GUI tools for merge conflicts, blame, etc. I see now that this is a problem elsewhere -- sorry for the bother!
