### ISSUE TITLE
Support for 2019.3 EAP

### ISSUE THREAD

**Issue by jordyvandomselaar** [zielu/GitToolBox#178]
Hi! Thanks a lot for the plugin, I absolutely love it =) -- Would it be possible to get it to work on 2019.3 EAP? for PhpStorm?

**Comment by zielu** [comment]
Hi there is a release in plugin EAP channel. You can find how to switch to it  in main readme. I will however release new version to stable after the weekend.

**Comment by jordyvandomselaar** [comment]
Thank you!

**Comment by zielu** [comment]
193.0.3 released
