### ISSUE TITLE
inline blame color setting

### ISSUE THREAD

**Issue by transtone** [zielu/GitToolBox#184]
when I open inline blame, a highlight will come on the blame message, how can I get rid of the colors?

![image](https://user-images.githubusercontent.com/46688/69849454-b4cefa80-12b7-11ea-8466-8dba4b885851.png)
![f68bdcfdd595cc967c05cb6dafccee5](https://user-images.githubusercontent.com/46688/69849459-b7315480-12b7-11ea-8ae2-aafc86d42414.png)

**Comment by zielu** [comment]
@transtone which plugin version are you on ?

**Comment by transtone** [comment]
It since March, I start use it .

maybe the color theme done this.  I use [Dracula Theme](https://plugins.jetbrains.com/plugin/12275-dracula-theme/)  This is my settings:
[settings.zip](https://github.com/zielu/GitToolBox/files/3906693/settings.zip)

**Comment by zielu** [comment]
Cannot reproduce. Indeed must be some other plugin interfering because there is nothing in my code that could produce such result.

**Comment by transtone** [comment]
> Cannot reproduce. Indeed must be some other plugin interfering because there is nothing in my code that could produce such result.

thanks for care. I'll find the real problem and feedback it.

**Comment by atbeta** [comment]
I met the same problem:
I'm using Material UI theme and I found the problem happens only with Chinese character and  font ligature on.

**Comment by transtone** [comment]
> I met the same problem:
> I'm using Material UI theme and I found the problem happens only with Chinese character and font ligature on.

when disable `font ligature` ,   no more the colorful blames.

**Comment by zielu** [comment]
Hi, there is nothing to fix on my plugin's side. Seems like Material UI does not handle property line extensions rendering

**Comment by transtone** [comment]
There is not use Material UI at all.

**Comment by zielu** [comment]
Please create a new issue then with IDE and plugin version I don't want to resurrect old tickets

**Comment by transtone** [comment]
https://github.com/zielu/GitToolBox/issues/277
