### ISSUE TITLE
Feature Request: Cleanup of old local branches

### ISSUE THREAD

**Issue by zielu** [zielu/GitToolBox#185]
Run periodical task to check for outdates local branches that can be removed.
Check should take into account following cases:
- local branch was merged into master (or other configurable branch e.g. develop)
- local branch was inactive for configurable number of days

Check should run every X configurable number of hours (min. 4) and with small delay after project is opened (configurable option).

If check finds any branches to cleanup it will display notification in Notifications area with number of found branches and link to open cleanup dialog.

Cleanup dialog will show a list of branches with reason for cleanup (merged or inactive) and date when activity that triggered branch being marked occurred. User can selected which branches should be deleted, by default all found branches are selected.

**Comment by trailsnail** [comment]
Until solution available, you can use https://plugins.jetbrains.com/plugin/10059-git-branch-cleaner

**Comment by zielu** [comment]
Released to EAP channel https://github.com/zielu/GitToolBox#eap-builds in 203.5.9

**Comment by zielu** [comment]
TODO:
- [ ] branch inactivity period configuration
- [ ] project-level config overrides

**Comment by zielu** [comment]
Done in 203.5.10
