### ISSUE TITLE
ADD Absolute date-time style: ISO date (ISO date YYYY-MM-DD HH:MM:SS)

### ISSUE THREAD

**Issue by allanlaal** [zielu/GitToolBox#189]
the Absolute date-time style dropdown is missing the ISO date style of YYYY-MM-DD HH:MM:SS (i.e. 2019-12-17 22:52:21) commonly used in Europe and Down Under

this seems to have been missed by #160

**Comment by zielu** [comment]
Hi, styles with 3 letter months were chosen on purpose to avoid any confusion between MM-DD and DD-MM.
It's relatively easy to add ISO style though.

**Comment by zielu** [comment]
Released to EAP channel in 193.3.1

**Comment by zielu** [comment]
Released to Stable in 193.3.2
