### ISSUE TITLE
Allow to force fetching (e.g. with double click on the status)

### ISSUE THREAD

**Issue by amal** [zielu/GitToolBox#19]
Please allow forcing fetching.  For example with double click on the status or with context menu option (opened from status). Would be awesome if customizable.

**Comment by zielu** [comment]
Do you mean running `git fetch --force` or just invoking fetch at any time regardless of auto-fetch ?

**Comment by amal** [comment]
I mean just invoking fetch at any time :)

**Comment by zielu** [comment]
Np :) This seems a bit redundant as you can always assign keyboard shortcut to Git > Fetch action or even place it in main toolbar.

**Comment by amal** [comment]
Yeah. But it would be a really convenient way to use this feature.
