### ISSUE TITLE
Non-commited files status bugs on move to other changelist

### ISSUE THREAD

**Issue by s3r6** [zielu/GitToolBox#191]
1. Open a project with no local changes
2. Make some changes in Default changelist, status displays them OK
3. Move one file from Default changelist to Some new changelist, refresh VCS

Expected: status shows summary amount of the files no matter how many changelists
Instead: status shows 1 file

![2019-12-28-09:56](https://user-images.githubusercontent.com/4716175/71539767-a0cff480-295a-11ea-85d7-5815bd11ca08.png)

**Comment by zielu** [comment]
Done in 193.3.3
