### ISSUE TITLE
What's the blue ball in the status display?

### ISSUE THREAD

**Issue by robertocaldas** [zielu/GitToolBox#195]
The manual doesn't say...

**Comment by zielu** [comment]
Hi, indeed I have to update the manual. The ball is linked to changed files trackings. Blue means there are uncommitted changes, gray means repo is clean.

**Comment by zielu** [comment]
Manual is updated: https://github.com/zielu/GitToolBox/wiki/Manual#not-committed-changes-tracker

**Comment by robertocaldas** [comment]
Thank you!
