### ISSUE TITLE
Doesn't show in Intellij 2019.2

### ISSUE THREAD

**Issue by geryit** [zielu/GitToolBox#196]
<img width="1507" alt="Screen Shot 2020-01-21 at 7 00 18 PM" src="https://user-images.githubusercontent.com/514149/72861958-40de1c80-3c80-11ea-9069-0bc31206986b.png">
<img width="1340" alt="Screen Shot 2020-01-21 at 7 00 39 PM" src="https://user-images.githubusercontent.com/514149/72861959-40de1c80-3c80-11ea-9eac-188e2c2c285d.png">

**Comment by zielu** [comment]
Hi, this is related to my release strategy. Usually when new middle version is released I move development to that one only backporting critical fixes to previous. At this point there new apis in 2019.3 that make latest plugin incompatible. If you want latest you should move to 2019.3.

**Comment by geryit** [comment]
thanks. will use latest
