### ISSUE TITLE
NoClassDefFoundError: com/codahale/metrics/MetricRegistry

### ISSUE THREAD

**Issue by yuxh** [zielu/GitToolBox#199]
java.lang.NoClassDefFoundError: com/codahale/metrics/MetricRegistry
GitToolBox: 193.4.4
Intellij: 2019.3.2 
OS: centos 8

**Comment by zielu** [comment]
Hi, cannot reproduce. All jars are in place in release artefact. 
Two questions:
- where did you get the build from
- full stack trace is appreciated

**Comment by yuxh** [comment]
I downloaded from jetbrain official site and install from disk. I don't known why I downloaded a jar for mistake yesterday. I redo installation and work fine, thanks
