### ISSUE TITLE
Override the gitmoji commit completion 

### ISSUE THREAD

**Issue by SettingDust** [zielu/GitToolBox#200]
https://plugins.jetbrains.com/plugin/10315-gitmoji

Cannot display the English completion. Is there a option to disable it?

**Comment by zielu** [comment]
First give this one a try: 
Settings > Other Settings > GitToolBox Global > Commit dialog completion: On demand


You can disable per-project in Settings > Other Settings > GitToolBox Project > Commit dialog completion

**Comment by SettingDust** [comment]
> First give this one a try:
> Settings > Other Settings > GitToolBox Global > Commit dialog completion: On demand
> 
> You can disable per-project in Settings > Other Settings > GitToolBox Project > Commit dialog completion

It's ok. But is a bug?

**Comment by zielu** [comment]
I think it is but in gitmoji. Consider branch named `fixing`, you type fix:
my plugin will contribute `fixing` which is a prefix match, while gitmoji will contribute number of items which are not prefix matched but only in "description" part.

Completion is also influenced by Editor > General > Code completion > Show suggestions as you type.

**Comment by zielu** [comment]
@SettingDust I decided to add gitmoji as part of my plugin. Completion will be done in slightly different way than in plugin you refer to so that it works without issues.

It is tracked here:  #202
