### ISSUE TITLE
[Feature] Gitmoji completion for commit messages

### ISSUE THREAD

**Issue by zielu** [zielu/GitToolBox#202]
https://plugins.jetbrains.com/plugin/10315-gitmoji

Completion can be enabled on per-project basis (same as branch one)
Completion is disabled by default.

Key difference from that plugin is how LookupElementBuilder are registered. 
- to be able to complete on "description" part that said part should be added to lookupStrings
- item itself is `:abc:` description is added as typeText

**Comment by SettingDust** [comment]
BTW, the `Version Control -> Log` can't display the emoji normally (`:bug:` not 🐛 )

**Comment by zielu** [comment]
Done in 193.5.0
