### ISSUE TITLE
Git blame not working

### ISSUE THREAD

**Issue by justclint** [zielu/GitToolBox#203]
Hi, Ive installed the GitToolBox plugin and have gone through the settings but can not seem to get the blame feature working neither inline or in the status bar.

GitToolBox version: 193.4.5

Heres my intellij system info:
```
IntelliJ IDEA 2019.3.3 (Ultimate Edition)
Build #IU-193.6494.35, built on February 10, 2020
***
Runtime version: 11.0.5+10-b520.38 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.3
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: com.chrisrm.idea.MaterialThemeUI, com.intellij.apacheConfig, com.intellij.plugins.html.instantEditing, com.jetbrains.php, com.jetbrains.php.behat, com.jetbrains.plugins.ini4idea, com.jetbrains.php.drupal, com.jetbrains.twig, com.jsonjuri.phpSyntaxColorHighlighter, com.markskelton.one-dark-theme, com.sensiolabs.insight, com.thvardhan.gradianto, com.vermouthx.idea, de.espend.idea.php.toolbox, de.espend.idea.php.annotation, fr.adrienbrault.idea.symfony2plugin, de.espend.idea.php.drupal, org.masamotod.idea.Drupal8NamespaceDetector, zielu.gittoolbox
```

Heres my GitToolBox settings re: git blame:

<img width="825" alt="Screen Shot 2020-02-14 at 8 18 42 AM" src="https://user-images.githubusercontent.com/466984/74548459-c3b26a00-4f02-11ea-868a-ca04c526ddf4.png">

<img width="651" alt="Screen Shot 2020-02-14 at 8 18 49 AM" src="https://user-images.githubusercontent.com/466984/74548460-c3b26a00-4f02-11ea-988a-3ee41fc43a7d.png">

If theres any additional info I could provide that helps, please just let me know. Thanks!

**Comment by zielu** [comment]
Please enable following categories in logging https://github.com/zielu/GitToolBox#debug-logging
```
#zielu.gittoolbox.blame
#zielu.gittoolbox.ui.blame
```
And check if you see any lines from BlameCacheImpl

**Comment by justclint** [comment]
I dont see any references to `BlameCacheImpl`. 

I do see the log categories added:
```
2020-02-17 09:21:59,559 [263944671]   INFO - lij.diagnostic.DebugLogManager - Set DEBUG for the following categories: #zielu.gittoolbox.blame, #zielu.gittoolbox.ui.blame 
2020-02-17 09:22:26,720 [263971832]   INFO - lij.diagnostic.DebugLogManager - Set DEBUG for the following categories: #zielu.gittoolbox.blame, #zielu.gittoolbox.ui.blame 
```

**Comment by zielu** [comment]
Did you try opening new files ?

**Comment by justclint** [comment]
Just got it working. Apparently I had not activated git integration.

Thanks!

**Comment by zielu** [comment]
Well that would explain a log :) no problem.
