### ISSUE TITLE
Crash in IntelliJ EAP

### ISSUE THREAD

**Issue by AlexCzar** [zielu/GitToolBox#204]
When I have GitToolBox enabled, IntelliJ 2020.1 EAP crashes on opening gradle composite project with two repositories. I think something bad is happening with trying to communicate with two repositories at once. The issue is not 100% reproducible on minimal projects, but for my actively developed work project it is 100%, it won't with GTB installed.
Interestingly there are no crash logs anywhere, not in ~/java_error_*, not in idea.log

**Comment by zielu** [comment]
Hmm, does it look similar to this one ? #198

**Comment by AlexCzar** [comment]
Somewhat, except in #198 there is exception stack trace from somewhere, whereas in my case, logs are empty - there are normal messages and then crash doesn't add anything to any log.

**Comment by zielu** [comment]
Please try 201.0.1

**Comment by zielu** [comment]
I'm using 2020 EAP with multi root project and did not encounter this yet.

**Comment by AlexCzar** [comment]
Turns out this is not GitToolBox related, GTB is just a surefire way to trigger the crash, but it happens without GTB too, as it turns out.
https://youtrack.jetbrains.com/issue/IDEA-232644
