### ISSUE TITLE
Behind blue arrow still displayed after update project/pull

### ISSUE THREAD

**Issue by RoEngel** [zielu/GitToolBox#209]
When opening the VCS window, the blue arrow indicating that local is behind remote still remains after successfully update/pulling.

![image](https://user-images.githubusercontent.com/60978745/75188046-6fd12d80-5719-11ea-97a6-efcd9ccfaa37.png)

Android Studio version: Android Studio 3.6
Build #AI-192.7142.36.36.6200805, built on February 12, 2020

Plugin version: 192.6.3

**Comment by zielu** [comment]
Hi, this arrow is not provided by my plugin, but by IDE itself.

**Comment by RoEngel** [comment]
Your completely right sorry for wasting your time...
