### ISSUE TITLE
Ability to choose a color based on remote branch name

### ISSUE THREAD

**Issue by Redhunt2013** [zielu/GitToolBox#210]
I would like to see `master`, which is our default remote branch, in a different color than other remote branches.  Currently, plugin always applies the same color for all remote branches.  
We work on different remote branches from time to time.  It will be really helpful to see if I am on a remote branch other than `master`.

In this screenshot here, I have two repositories open.  One on remote/master, other on remote/dev branch.  I would like to see the master's label in a different color setting, if possible.

![Screen Shot 2020-02-25 at 4 33 37 PM](https://user-images.githubusercontent.com/5237704/75297348-dffcb380-57ec-11ea-9e91-b341984e05c1.png)

**Comment by zielu** [comment]
Hi, I will add different colors for master with remote and local only master.

**Comment by zielu** [comment]
Done in 193.6.0
