### ISSUE TITLE
Disable inline blame when debugging

### ISSUE THREAD

**Issue by vineus** [zielu/GitToolBox#214]
I love inline blame when writing code but the inline blame message currently takes precedence over the very useful `Show Values Inline` builtin functionality (showing the values of the variables inline when debuggging).

Would it be possible to disable inline blame only when a debug session is in progress or is it something not really supported by intellij ?

Thanks a lot for your help!

**Comment by zielu** [comment]
Hi, I will investigate this. I think I saw some apis inside intellij that should allow do implement such behavior.

**Comment by zielu** [comment]
Done in 193.7.0

**Comment by vineus** [comment]
Thank you so much!

**Comment by aaronols** [comment]
Just wanted to say thank you for making this configurable. I turned it off because I tend to debug one process and write code for another in the same project. So the ability to configure this feature is working and appreciated 😃

**Comment by zielu** [comment]
@aaronols your are welcome 😀. I try to follow policy of making all features configurable.
