### ISSUE TITLE
Add auto-fetch configuration for new projects 

### ISSUE THREAD

**Issue by nanoander** [zielu/GitToolBox#222]
I like this plugin, but I want auto fetch to be disabled by default in new projects.
Please add that to the setup options.

Thanks!

**Comment by zielu** [comment]
https://github.com/zielu/GitToolBox/wiki/Manual#defaults-for-new-project

**Comment by nanoander** [comment]
Sure, the case is that although I unchecked `Auto fetch` and `Auto fetch on branch switch` in there, auto fetch is still happening. It seems that this should be a Global option that per project setup can overwrite.

**Comment by zielu** [comment]
Ok I'll check why it does not work but I will no change it - there are default for new projects and overrides for existing ones. 
Other mechanisms are not needed.

**Comment by zielu** [comment]
Did you uncheck before project import or after it was opened once ? If already after open you have to go with overrides.

**Comment by zielu** [comment]
Btw it seems to work as expected.

**Comment by nanoander** [comment]
Not for me unfortunately... I'll uninstall it, thank you!

**Comment by zielu** [comment]
You did not provide much details though version, id etc...
