### ISSUE TITLE
Git fetching and pulling takes forever

### ISSUE THREAD

**Issue by thibaut38410** [zielu/GitToolBox#223]
![image](https://user-images.githubusercontent.com/18270808/77048280-75dbc680-69c6-11ea-8f9c-450037bb9885.png)
Hi,

Using GitToolBox 193.7.2 (problem also occur on previous versions), all git fetching and pulling operations are very slow and consume a lot of system ressources (see attached image). Pulling several repositories (around 5) will sometimes takes 3 minutes or more as well as automatic or manual fetching takes several minutes and slows down the entire IDE during this time. I belive this might be due to the high number of tags there are in the commits in these directories. Is there a way to disable the fetching of tags or better, improve the performance of the plugin regarding tags ?

Thanks in advance.

**Comment by zielu** [comment]
Hi, for fetch I'm using classes provided but IDE Git Integration. My plugin does not do pull.
Could you check if it behaves the same with toolbox disabled ? 
If so it's something to report to Jetbrains.

**Comment by zielu** [comment]
No response, closing
