### ISSUE TITLE
code vision conflicts with editor inline blame

### ISSUE THREAD

**Issue by pixsrv** [zielu/GitToolBox#224]
i'm not sure if this is IDE issue or plugin
[RIDER-41353 code vision conflicts with editor inline blame](https://youtrack.jetbrains.com/issue/RIDER-41353)

**Comment by zielu** [comment]
Hi, I think it's because they use different approaches to rendering information. This issue is similar to #194.
There other plugin is painting directly on editor and I use EditorLinePainter API

**Comment by zielu** [comment]
I could try to accommodate it by shifting blame more to the right

**Comment by pixsrv** [comment]
but "shifting to the right" feature should definitely depends on this settings
![image](https://user-images.githubusercontent.com/10224591/77066516-9b2afd80-69e3-11ea-81e3-4af5b9fe9e58.png)

**Comment by zielu** [comment]
Indeed, in that other issue it would be also conditional.

I I'm worried about is that code vision can have variable length and it will be hard to come up with one "correct" amount ;)

**Comment by pixsrv** [comment]
it really is
especially when ...More appears

i understand the code-vision width it's not well-known dimension ;)

good thing is that blame conflicts only on the line where vision appears
so not that often

kinda workaround is to inform user about this conflict
next to the blame checkbox in your plugin settings
so user could decide

is it possible to drive "app settings" from your plugin?
if yes
then you could add a code vision control "in" your plugin settings
so user could change these 2 settings in one place
if not
then maybe you can add a-link or a-button which could switch settings pages directly to code vision
so user can change it without sniffing where this little tick has been hidden ;)

**Comment by zielu** [comment]
Fixed by #268 in (203/212).7.4
