### ISSUE TITLE
Ghost commits (status widget is broken?)

### ISSUE THREAD

**Issue by St-Permiakov** [zielu/GitToolBox#225]
Maybe I don't get it, but how is this possible?

https://prnt.sc/rjgqr1

I have no real commits ahead or behind. That's what git is telling and that's what I'm sure of.
But status widget still shows enormous commit count.
According to description, it should show commits for current branch.
But it definetly does not.

Another example (same project, same rep):
Branch has 3 ahead commits, but widget shows 9 ahead and 41 behind (when there is none).
https://prnt.sc/rjgzs8

Is it me or is it something wrong with this tool?

WebStorm 2019.3.3
GitToolBox 193.7.2

**Comment by zielu** [comment]
Hi, which IDE and plugin version are we talking about ?

**Comment by St-Permiakov** [comment]
Oh, sorry, was too confused to provide proper info in the first place.

WebStorm 2019.3.3
GitToolBox 193.7.2

**Comment by zielu** [comment]
No problem, I'll look into this.

**Comment by zielu** [comment]
Hi, few questions:
- does this persist after you reopen the project 
- does your project view show smth like `some-branch > master`
- can you check IDE logs if there are any warnings from GitStatusCalculator

**Comment by St-Permiakov** [comment]
- yes, it does. Exact same numbers.
- kinda. It shows `master > some-branch` (I guess that's the problem?)
- IDE logs are clear of any warnings (https://prnt.sc/rl0urr)

**Comment by zielu** [comment]
Ok, so it entered parent branch mode - you are probably using tasks.
You can read more about this here: https://github.com/zielu/GitToolBox/wiki/Manual#git-status-display - but in essence it is now showing number of commits not present in each of the branches.
You can disable this by changing Preferences > GitToolBox Project > Parent branch mode - to Tracked remote

**Comment by St-Permiakov** [comment]
Yes, it did the trick!
Thank you! Sorry for bothering)

**Comment by zielu** [comment]
@St-Permiakov you should also change it in New Project Settings so you don't have to fix it when creating new projects: https://github.com/zielu/GitToolBox/wiki/Manual#defaults-for-new-project
