### ISSUE TITLE
Rework configuration from global level migrations on project open to globals with per-project override

### ISSUE THREAD

**Issue by zielu** [zielu/GitToolBox#226]
Due to strict separation of app and project level configuration options there is a limited mechanism implemented to define overrides on app-level that are applied once on project-level. This is too complicated and unintuitive. 

Standard IDE approach is to have global defaults that can be overridden on project-level.

Following project-level configuration should be moved to app-level with project override:
- auto-fetch enabled
- auto-fetch interval
- auto-fetch on branch switch
- commit dialog completion enabled
- parent branch mode
- parent branch (selected parent)
- commit message validation
- completion formatters

App-level configuration tabs:
- General
  - ahead/behind presenation
  - git stat in statusbar
  - changed in statusbar
  - blame in statusbar
  - editor inline blame
  - project view decoration
  - behind tracker
  - behind tracker update action
  - absolute date-time style
- project view - stays as-is
- auto-fetch (new)
  - auto-fetch enabled
  - auto-fetch interval
  - auto-fetch on branch switch
- blame - stays as-is
- status (new)
  - parent branch mode
  - parent branch (selected parent)
- commit dialog (new)
  - completion mode 
  - branch name completion enabled
  - gitmoji completion enabled
  - message validation
  - completion formatters
- Extras - will be removed

Project-level configuration tabs:
- auto-fetch
  - auto-fetch enabled
  - auto-fetch interval
  - auto-fetch on branch switch
  - auto-fetch exclusions
- status (new)
  - parent branch mode
  - parent branch (selected parent)
- commit dialog
  - branch name completion enabled
  - gitmoji completion enabled
  - message validation
  - completion formatters

When override is enabled config is copied from app-level to project.
When override is disabled:
- project-level value is kept but app-level value is displayed
- UI control is disabled

Override checkboxes should be placed to right-side taking cue from IDE Maven config page.

Settings are moved under `Version Control` section.

Migration
- extras are converted to global settings
- project-level values that are different from app-level ones are converted into override
- settings for new project (a.k.a. default project) should also be migrated

**Comment by mfn** [comment]
>  commit dialog completion enabled

I would love to see that being able to disable globally. It's the _one_ thing I've to always manually disable for all projects I work on, unfortunately it just "gets in my way".

Thanks for the great work 🤗

**Comment by zielu** [comment]
It's taking a long time because I'm also migrating UI to kotlin dsl

**Comment by zielu** [comment]
@mfn feature is almost ready - feeling brave to give it a whirl ?

**Comment by mfn** [comment]
@zielu Yes! But… where? 🤔

I've https://plugins.jetbrains.com/plugins/eap/7499 added to my plugins (had it already there), but I don't see any newer version?

Thanks!

**Comment by zielu** [comment]
I was working out several issues, now it looks eap worthy :smile:

**Comment by zielu** [comment]
And it's out 203.5.0 😃

**Comment by zielu** [comment]
203.5.1 to fix small UI issue

**Comment by zielu** [comment]
Released in 203.5.3
