### ISSUE TITLE
Feature Requeste: Exclude Remote branch in Auto fetch

### ISSUE THREAD

**Issue by LostKatana** [zielu/GitToolBox#227]
We are working with customers repositories and as well with local repository for convenience.
The remote repository of our customer is not reachable without an authentication an fetching always fails. It would be nice to have the option to add an exclude for remotes or choose which one will auto fetch.

**Comment by zielu** [comment]
Hi @LostKatana there is a feature that is a bit hidden that allows excluding remotes: https://github.com/zielu/GitToolBox/wiki/Manual#automatic-fetch-exclusions

I need to rework that UI :/ 

Let me know if you have any qeustions

**Comment by LostKatana** [comment]
Wow, thanks for that quick answer. Even with reading this part of the manual it seems I overlocked that part.
 I'd like to propose a litte modified version of this manual:

# Automatic fetch exclusions
Under GitToolBox Project settings open the _Auto Fetch_ tab and add your repository with the plus sign.
Afterwards mark the repository in the list and add the remote you want to exclude with the plus sign again.

Exclusions are applied according to following rules:
1. If a repository without remotes is configured, the whole repository is excluded
2. If a repository with remotes is configured, only those remotes are excluded

Exclusions apply only to automatic fetch, they do not influence fetch actions.

**Comment by zielu** [comment]
Looks nice, thanks !
