### ISSUE TITLE
Branch name not visible against module in Android View on Android Studio

### ISSUE THREAD

**Issue by ethereal-carnival** [zielu/GitToolBox#231]
When I use this plugin in Project View on Android Studio, I get the names of the branch against the module as expected

<img width="240" alt="Screenshot 2020-04-09 at 1 00 18 PM" src="https://user-images.githubusercontent.com/25270365/78869378-1e2ef900-7a62-11ea-8991-ab3856068d90.png">

But when I view the same in Android view, I can't see the branch name. 

<img width="265" alt="Screenshot 2020-04-09 at 1 02 36 PM" src="https://user-images.githubusercontent.com/25270365/78869687-9695ba00-7a62-11ea-8151-5fea2ff025ef.png">

I can still see the branch name at the bottom right of the screen but it would be a good boost to productivity if I could see the branch name against the module name in Android View too.

Thanks.

**Comment by zielu** [comment]
@ethereal-carnival Current Android Studio release (3.6.2) is on Intellij Platform 192 and I don't wont to go back go that branch. Preview version 4 is on 193 - the same that I'm supporting at this moment.

I'll see how complicated it is to backport this feature to version 3.

**Comment by zielu** [comment]
@ethereal-carnival after investigation in IDE code it's not possible to add branch name on level visible on screenshots because it's not supported. What is possible is to add them one level underneath so on "package" level

**Comment by ethereal-carnival** [comment]
Oh. Well, thank you for putting in the time and effort to pursue the possibilities. I intend to stick to Android view so will have to reply on the bottom right corner.
Thanks for making an amazing plugin anyway. Cheers!
