### ISSUE TITLE
inline blame not working after computer sleep / hibernate

### ISSUE THREAD

**Issue by izzetince** [zielu/GitToolBox#232]
inline blame not working after computer sleep / hibernate.. But if restart intelliJ inline blame shown up again.

**Comment by zielu** [comment]
Hi could you specify:
- os
- IDE and version
- plugin version

**Comment by izzetince** [comment]
Hi,

- Windows 10 , version 1909 (Latest)

- IntelliJ Ultimate Edition 2020.1 (Latest) 

- GitToolBox 201.2.1 (Latest)

Thanks a lot.

**Comment by zielu** [comment]
Hi, I tried to reproduce in VM (I dont have Windows machine on hand) and had no luck, so additional question - is there any particular sleep time after which this happens ? If you sleep and wake immediately does it also occur ?

Could you enable logs from following categories in Debug Log Settings:
- `#zielu.gittoolbox.blame`
- `#zielu.gittoolbox.ui.blame`

and check if there is anything from `BlameServiceImpl` or `BlameCacheImpl` ?

**Comment by izzetince** [comment]
I've checked again and again but I can't reproduce the problem. It's weird. It seems work properly.
Nevertheless, thank you for attention.
