### ISSUE TITLE
failed to load plugin descriptor from file 

### ISSUE THREAD

**Issue by dickreuter** [zielu/GitToolBox#235]
When trying to install the plugin from file I get "failed to load plugin descriptor from file ".

**Comment by zielu** [comment]
Did you select the zip file or some jar from it ? Install issues usually occur when you try to install something other than full zip.

**Comment by dickreuter** [comment]
Yes I selected the zip file.

**Comment by zielu** [comment]
Hi, could you specify which version of plugin in which version of which IDE did you try to install ?

**Comment by dickreuter** [comment]
Latest version of pycharm with latest version of the plugin.

**Comment by zielu** [comment]
I re-released 201.2.1 as 201.2.2. Please try 201.2.2 with PyCharm 2020.1

**Comment by zielu** [comment]
Hi, did new release help ?

**Comment by dickreuter** [comment]
Yes thanks. Problem solved.
