### ISSUE TITLE
Inline blame doesn't show up while running something in debug mode?

### ISSUE THREAD

**Issue by alexcs-bsft** [zielu/GitToolBox#236]
Just want to start by saying that this plugin has dramatically leveled up my experience in WebStorm and RubyMine, thanks for putting all this functionality in one place!

That said, I've been noticing for a while that the inline git blame hasn't been showing up in one of my RubyMine projects, even when I can see it for another project in its own RubyMine window at the same time. At first I thought it might be due to some resource constraint that I was hitting from having too many tabs open or something, but I actually just discovered a more likely correlation:
- I have run configurations in RubyMine for a Rails server and Sidekiq background workers than I run side-by-side
- When I run both of these in the normal "Run" mode, the inline git-blame works, the same as if I wasn't running anything
- The second that I run either one with the "Debug" button, the inline blame disappears, and it comes back right away if I switch back to the "Run" configuration.

The debugger also displays some information inline when you stop at a breakpoint, so it seemed like a much more likely correlation. I'm totally okay with the git blame not displaying while I'm actually stopped a a breakpoint, but when the server is just running in debug mode, it would be nice to still be able to see the inline blame.

**Comment by zielu** [comment]
Hi, this is by design - if you you are using option for debugger to show inline values, then blame is disabled to prevent hiding the values.

At this moment there are 2 options:
- force showing inline blame Preferences > Git ToolBox Global > Blame uncheck `Hide inline blame...`
- blame is still available in status bar

I'll take a look if it's possible to determine if you are stopped at breakpoint or not.

**Comment by alexcs-bsft** [comment]
Thanks for the quick response!

**Comment by alexcs-bsft** [comment]
That's great to hear. After it is implemented, will the `Hide inline blame...` preference still default to checked, or will that preference be changed/updated?

**Comment by zielu** [comment]
Done in 193.8.1

**Comment by Maykonn** [comment]
I'm using PHPStorm 2018.3, inline blame checkbox doesn't show on the plugin settings, only the options to the status bar.
Inline blame not working.

**Comment by zielu** [comment]
Hi @Maykonn, let me take a look, I remember this is one of boundary versions where inline blame was introduced. Btw I think I need feature / version matrix :)

**Comment by zielu** [comment]
@Maykonn inline blame was added in 183.3.0 but for 2018.3 183.6.1 is the last release. I recommend it because earlier had performance issues in inline blame

**Comment by Maykonn** [comment]
Hi @zielu I added the plugin repository url to the plugin repositories list, but the ide shows me that 183.1.0 is the most recent version. I'll try an installation from the disk.

**Comment by Maykonn** [comment]
@zielu I've just tried a manual installation of 183.6.1 but the IDE returning this error: _Plugin 'GitToolBox' is incompatible with this installation_

**Comment by zielu** [comment]
@Maykonn there is one more possibility - looking at exact version - you need at least 2018.3.3 to get versions with inline blame

**Comment by Maykonn** [comment]
I see, thanks @zielu
