### ISSUE TITLE
It does not work on android studio 2.2.2

### ISSUE THREAD

**Issue by java02014** [zielu/GitToolBox#24]
It does not work on android studio 2.2.2

**Comment by spydesk** [comment]
Same for me...

The plugin does not appear into the plugin repository.

When trying to install version 16.3.2 manually, I have the following error :

> Plugin 'GitToolBox' is incompatible with this installation

**Comment by zielu** [comment]
Looks I removed one release from JB repository that covered Idea 2016.1 EAP (145) and AS 2.2.2 is based on 145 line.
I'll prepare release based on 16.3.2 that will be compatible with 145.

**Comment by java02014** [comment]
when  can I download the new version to support AS 2.2.2?

**Comment by zielu** [comment]
16.3.3 released although I don't know why it is not immediately visible in AS under 'Browse repositories' - it was in Idea.
You can download it from [Jetbrains repo](https://plugins.jetbrains.com/plugin/7499) and install from disk.

**Comment by java02014** [comment]
thank you
