### ISSUE TITLE
[new feature] Copy / open reference as git url

### ISSUE THREAD

**Issue by gberche-orange** [zielu/GitToolBox#240]
* As a gitoolbox user
* in order to share url to files across repos (e.g. in documentation),
* I would need to able to copy a file reference as a git url (e.g. `https://github.com/orange-cloudfoundry/osb-cmdb-ci/blob/master/scripts/clean-at-cf-environment.sh` or `https://github.com/orange-cloudfoundry/osb-cmdb-ci/blob/128943c297947b6bc26f436f6cb3400593e0b5d5/scripts/clean-at-cf-environment.sh` for a permalink in the example below)

Currently the "copy as toolbox url" seems to copy a reference across git project (`jetbrains://idea/navigate/reference?project=osb-cmdb-ci&path=scripts/clean-at-cf-environment.sh` in the example below)
![image](https://user-images.githubusercontent.com/4748380/81810902-101e3d80-9524-11ea-8295-1ed4e0b7d5cb.png)

Workaround: use github plugin to open the file in a browser, and copy the url from the address bar

![image](https://user-images.githubusercontent.com/4748380/81811168-7d31d300-9524-11ea-831a-cd55f8f9f9a3.png)

**Comment by ammmze** [comment]
There is also the [GitLink](https://plugins.jetbrains.com/plugin/8183-gitlink) plugin, which will add a `Copy GitHub Link` to the context (i.e. right click) menu as well as the menu bar's `View` menu.

**Comment by zielu** [comment]
Done for Github and Bitbucket Cloud & Server with Open / Copy link to file (and line in file). Also includes back-navigation - will be available in pro version of plugin.

**Comment by gberche-orange** [comment]
> Also includes back-navigation - will be available in pro version of plugin.
thanks @zielu ! Would you have a screenshot of back navigation available as a teaser ?

**Comment by zielu** [comment]
@gberche-orange looks like this: https://github.com/zielu/GitToolBox/wiki/Manual#repository-links - I'll adding more repo types soon.
