### ISSUE TITLE
[Feature] Blame - change font size and transparency

### ISSUE THREAD

**Issue by RGu0000** [zielu/GitToolBox#244]
I switched to GitToolBox after using VSCode's GitLense. I am really used to old solution and I failed to find a possibility to change font size and it's transparency, so I won't get distracted by it when coding - as for now, it's really hard to see the difference between code and annotation.

Is there a way to customise it already, or will it be possible in the future?

**Comment by zielu** [comment]
Hi, colors can be customised in Preferneces under Editor / Color Scheme / GitToolBox Colors

**Comment by RGu0000** [comment]
Ha indeed it can! Thanks for such a fast reply!

**Comment by haccks** [comment]
Is there a way to change the font size?
