### ISSUE TITLE
Fatal error reported by intellij in version 201.3.0

### ISSUE THREAD

**Issue by gberche-orange** [zielu/GitToolBox#245]
I'm seeing the following error and associated stack trace. I'm not sure what action triggered it and what side effects this caused. I however hope this can help.

![image](https://user-images.githubusercontent.com/4748380/82828085-9f2a3e80-9eb0-11ea-8afe-1b3a794551e0.png)

Detailed stack traces are available at https://gist.github.com/gberche-orange/7e6e732644135ea5b4cebc9569b0ec5c

Thanks again for the great work on GitToolBox!

**Comment by zielu** [comment]
Hi, there always seems to be one more exception like that hiding in code :/

**Comment by zielu** [comment]
Done in 201.3.1

**Comment by gberche-orange** [comment]
thanks @zielu !
