### ISSUE TITLE
Incompatible with IntelliJ IDEA 2020.2 EAP / Build #IU-202.4357.23

### ISSUE THREAD

**Issue by doublefx** [zielu/GitToolBox#246]
Incompatible with IntelliJ IDEA 2020.2 EAP / Build #IU-202.4357.23

I tried to uninstall / install as I did with some other plugins but I did not work for this one, it does not even appear anymore in the plugin list.

**Comment by doublefx** [comment]
Working now

**Comment by zielu** [comment]
Hi, I pushed the build into plugin EAP channel. How you can switch is described here: https://github.com/zielu/GitToolBox#eap-builds
