### ISSUE TITLE
Fetch operation steals focus from curent IDEA project/window

### ISSUE THREAD

**Issue by kool79** [zielu/GitToolBox#249]
Ususally I have few IntelliJ IDEA windows opened. Recently (~1 month or less ago) I found that my window where I do my code review suddenly closes and focus moved to IDEA instance where 'fetching' operatin is in progress. I thinks it is bug in your plugin because is the only plugin which is configured for auto-fetching. It is reproduced every time and became annoying

Windows10
IntelliJ IDEA 2020.2 EAP (Ultimate Edition)
Build #IU-202.4357.23, built on May 27, 2020
IntelliJ IDEA EAP User
Expiration date: June 26, 2020
Runtime version: 11.0.7+10-b912.1 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 3029M
Cores: 8

**Comment by zielu** [comment]
Hi, do you have 2 projects open or is it one project with 2 windows ?

**Comment by zielu** [comment]
I cannot reproduce on macos IntelliJ IDEA 2020.1.2 (Ultimate Edition)
Build #IU-201.7846.76, built on June 1, 2020.

I tried with one project and 2 windows with "review" one displayed on top.

I'll try with windows 10 under VM.

**Comment by zielu** [comment]
Cannot reproduce

**Comment by kool79** [comment]
Sorry for delay with answer (having vacation now). It was Win10,  with 2 separate projects opened. I use idea EAP version 2020.2 (it seems it is live now). I did not have such issues with previous IDEA versions. Please recheck on 2020.2. I cannot do that because no access to PC
