### ISSUE TITLE
Since the newest version, the status decorations are wrong after multi-push

### ISSUE THREAD

**Issue by pwilkin** [zielu/GitToolBox#25]
Several times now I have had this issue with the newest version - when doing multi-push (on multiple modules at once), if one of the repositories is auto-merged during the push, the status does not update and still shows the repo behind the upstream. Nothing fixes the issue short of a restart of IntelliJ (fetching, disabling/reenabling decorations etc. doesn't work).

**Comment by zielu** [comment]
Just an update - I've got some leads but this is one tricky issue. It happened for me also several times now :/

**Comment by zielu** [comment]
Attempted fix in 16.3.4

**Comment by pwilkin** [comment]
Still not fixed in newest build.

**Comment by zielu** [comment]
Does:
status bar > Git Stat > Refresh status help ?

**Comment by pwilkin** [comment]
Yes, it does.
