### ISSUE TITLE
[bug] IDE freezes on Preparing workspace

### ISSUE THREAD

**Issue by michalkos** [zielu/GitToolBox#250]
IntelliJ IDEA freezes on Preparing workspace while opening Flutter project. The freeze happens only when GitToolBox plugin is enabled. Once I disable this plugin, it works just fine.

IntelliJ IDEA 2020.1.2 (Ultimate Edition)
Build #IU-201.7846.76, built on June 1, 2020
Runtime version: 11.0.7+10-b765.53 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.5
GC: ParNew, ConcurrentMarkSweep
Memory: 2014M
Cores: 4
Non-Bundled Plugins: com.intellij.plugins.vscodekeymap, com.mallowigi, com.markskelton.one-dark-theme, mobi.hsz.idea.gitignore, net.vektah.codeglance, Dart, io.flutter, org.jetbrains.kotlin, zielu.gittoolbox, com.jetbrains.php, ru.adelf.idea.dotenv, intellij.prettierJS

**Comment by michalkos** [comment]
[threadDumps-freeze-20200618-092419-IU-201.7846.76.zip](https://github.com/zielu/GitToolBox/files/4796984/threadDumps-freeze-20200618-092419-IU-201.7846.76.zip)

Attaching threadDumps, if that helps.

**Comment by zielu** [comment]
Hi, that is great. Thanks !

**Comment by zielu** [comment]
Config migration is done and access method hangs on saving settings. This was introduced when migration on start-up was changed to migration on access.

Solution: do migration on startup proactively also review project config migration if it correctly detects no migration needed case.

**Comment by zielu** [comment]
Hi I uploaded fixed version to plugin EAP channel for now https://github.com/zielu/GitToolBox#eap-builds. I will release it next week

**Comment by zielu** [comment]
Done in 201.4.2
