### ISSUE TITLE
Version 202 is compiled with Java 11 bugs on IntelliJ when run with jbrsdk8

### ISSUE THREAD

**Issue by lozanro** [zielu/GitToolBox#254]
Jetbrains IntelliJ IDEA can be run with a JRE of version 8 (due to various reasons, enterprise constraints ...).
However when enabling the last version of the GitToolBox plugin after the 202.0.3 update, it breaks some of IntelliJ's gui : View -> Appearance menu doesn't open anymore, and most of the toolbars are missing. Disabling GitToolBox gets things back to normal.

`Caused by: java.lang.UnsupportedClassVersionError: zielu/gittoolbox/changes/ChangeListSubscriberChangeListListener has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0`

**Comment by lozanro** [comment]
[Switch to Java 11](https://github.com/zielu/GitToolBox/commit/44a89ae9204d838259b3347d7681a5a9422083e2)

**Comment by zielu** [comment]
Hi, it should be trivial to revert.

**Comment by zielu** [comment]
Done in 202.0.5

**Comment by lozanro** [comment]
> Hi, it should be trivial to revert.

Thanks for the prompt reaction.
