### ISSUE TITLE
 editor inline blame shows [NBSP] on WebStorm 2020.2

### ISSUE THREAD

**Issue by pelukron** [zielu/GitToolBox#255]
Since last WebStorm version (#WS-202.6397.88) editor inline blame is shown as below images:

![image](https://user-images.githubusercontent.com/5886170/88821980-e7076380-d188-11ea-9017-820b778540c7.png)

![image](https://user-images.githubusercontent.com/5886170/88822006-f1296200-d188-11ea-92d4-c75b7e6882a2.png)

![image](https://user-images.githubusercontent.com/5886170/88822035-00a8ab00-d189-11ea-8030-f7d9662f9eee.png)

IDE details:

WebStorm 2020.2
Build #WS-202.6397.88, built on July 24, 2020
Runtime version: 11.0.7+10-b944.20 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 2216M
Cores: 4

I found this similar issue.

https://github.com/zielu/GitToolBox/issues/252

Thank you for this amazing plugin

**Comment by sa1dai** [comment]
I also have WebStorm 2020.2 and don't have this issue
But I'am at Ubuntu 18.04

**Comment by pelukron** [comment]
Well, my project file has around 2k+ lines of code, i tried to "replicate" it on other project with small components but I couldn't 🙃

**Comment by sa1dai** [comment]
Try uninstall plugin, invalidate/restart webstorm, install plugin again

**Comment by zielu** [comment]
I also noticed that since 2020 code editor shows zero width characters as codes. Must be some new feature. I'll dig around.

**Comment by pelukron** [comment]
> 
> 
> Try uninstall plugin, invalidate/restart webstorm, install plugin again
@sa1dai 
I did it, but issue continue, I believe this new "major" release is breaking something :(

> 
> 
> I also noticed that since 2020 code editor shows zero width characters as codes. Must be some new feature. I'll dig around.

Thank you @zielu for tracking this issue

**Comment by zielu** [comment]
This could be it https://youtrack.jetbrains.com/issue/IDEA-115572

**Comment by zielu** [comment]
Only way to hide the characters would be adding some extra processing to strip them.
