### ISSUE TITLE
Git commit message validation regex not working

### ISSUE THREAD

**Issue by steebchen** [zielu/GitToolBox#258]
Regardless of what I type into the regex in the settings, even `.*`:

<img width="572" alt="image" src="https://user-images.githubusercontent.com/5013932/89098259-111e8700-d410-11ea-89d4-33417b6bff88.png">

it just doesn't work and when committing, an error pops up:

<img width="446" alt="image" src="https://user-images.githubusercontent.com/5013932/89098271-2398c080-d410-11ea-9bb6-b97a28999b40.png">

version 202.0.6 / Stable Release (20200731.093516

**Comment by zielu** [comment]
Hi, I cannot reproduce this

**Comment by steebchen** [comment]
Hm. Is there anything I can do to help you to reproduce?

**Comment by zielu** [comment]
Are you using commit tool window ?

**Comment by steebchen** [comment]
I'm using the new thing where it's in the sidebar, but it also happens when I switch to the separate window.

**Comment by steebchen** [comment]
Oh yeah – that's it! I'm using the new thing and not the separate window, but when switching to the window, it works!

**Comment by zielu** [comment]
I remember I had some hack in there. Time to dig in :smile:

**Comment by steebchen** [comment]
Thanks and good luck 😁

**Comment by zielu** [comment]
Done in 202.0.8
