### ISSUE TITLE
Error state

### ISSUE THREAD

**Issue by YiiGuxing** [zielu/GitToolBox#26]
![1](https://cloud.githubusercontent.com/assets/10737066/20417657/e1a937b2-ad81-11e6-882e-4564d8c965ec.png)

**Comment by peteyan** [comment]
I'm the same problem too. The up arrow has also display when it pushed.

**Comment by zielu** [comment]
Duplicate of #25 - I'm already working on fix

**Comment by zielu** [comment]
Attempted fix in 16.3.4
