### ISSUE TITLE
Pluginis no longer visible in latest IntelliJ

### ISSUE THREAD

**Issue by tomekbielaszewski** [zielu/GitToolBox#264]
Plugin disappeared after updating to the newest IntelliJ. The plugins menu was visible in lower right corner

IntelliJ IDEA 2020.2.1 (Ultimate Edition)
Build #IU-202.6948.69, built on August 24, 2020

**Comment by zielu** [comment]
Hi, which version did you update from ?

**Comment by tomekbielaszewski** [comment]
I've updated from 2020.1.3 where it worked well, also I've checked the settings and everything seems to be ok:
![image](https://user-images.githubusercontent.com/2652591/92379831-64b77b00-f108-11ea-8777-b0e1aa43d922.png)
but the toolbox is not visible :( 
![image](https://user-images.githubusercontent.com/2652591/92379870-7436c400-f108-11ea-8604-b56a7095fcbf.png)

**Comment by tomekbielaszewski** [comment]
Hi! I've resolved the issue. My Status Bar has been closed after update. I solely use it only for plugin of yours and that's why I raised this issue.
To anyone who will look for way to fix this:
ensure you've checked this setting: `View -> Appearance -> StatusBar`

**Comment by zielu** [comment]
Looks like whole status bar is hidden from some reason...

**Comment by zielu** [comment]
View > Appearance > Status bar

**Comment by tomekbielaszewski** [comment]
That was exactly that! Have a look at comment above :D
