### ISSUE TITLE
[Feature] Option to disable horizontal scrolling for inline blame

### ISSUE THREAD

**Issue by huzecong** [zielu/GitToolBox#267]
Currently the inline blame is treated as part of the line in the editor, so if the commit message is long, the blame would extend beyond the editor window boundaries and allow horizontal scrolling. I personally dislike horizontal scrolling so I wish there's an option to prevent this by e.g. automatically truncating the blame so it doesn't go beyond the editor boundaries.

This would be similar to the GitLens plugin in VS Code, which has an option: `gitlens.currentLine.scrollable` that "specifies whether the current line blame annotation can be scrolled into view when it is outside the viewport".

**Comment by zielu** [comment]
Hi, I'll take a look how hard this will be.

**Comment by zielu** [comment]
Done in (203/212).7.4
