### ISSUE TITLE
gitmoji auto completion support set  unicode or text

### ISSUE THREAD

**Issue by DoveAz** [zielu/GitToolBox#272]
like this https://plugins.jetbrains.com/plugin/14610-gitmoji-unicode

**Comment by zielu** [comment]
Hi, so you would like to be able to choose - either unicode or unicode + text ?

**Comment by DoveAz** [comment]
> Hi, so you would like to be able to choose - either unicode or unicode + text ?

unicode 🎉

**Comment by zielu** [comment]
Ok, got it colon notation is for github markdown

**Comment by ottnorml** [comment]
Thanks for your awesome plugin, @zielu.
It would be a really great feature if the user could choose in the settings whether to use text or Unicode for the emojis in commit messages. I would appreciate that a lot. :)

**Comment by zielu** [comment]
It's on the way :)
<img width="577" alt="image" src="https://user-images.githubusercontent.com/464103/100363478-15913000-2ffd-11eb-9272-3d47c582f46e.png">

**Comment by zielu** [comment]
Done in 202.2.5 - there is new option in global plugin settings that allows to select if unicode should be used
