### ISSUE TITLE
Incorrect displaying of inline blame with type hints

### ISSUE THREAD

**Issue by MairwunNx** [zielu/GitToolBox#276]
How it looks (as you see overlapped):
![image](https://user-images.githubusercontent.com/39625750/100421386-56d71d80-3099-11eb-9ab2-bd013d00840f.png)

Just screenshot with a type hint:
![image](https://user-images.githubusercontent.com/39625750/100421417-648ca300-3099-11eb-8b06-cb0052b848b4.png)

`201.4.2`, `Android Studio 4.1.1`, `Kotlin`

**Comment by zielu** [comment]
Hi, with current approach to how inline blame is displayed it's not possible to fix this. There is other IDE API that could be used to improve this and there is already issue open to switch to it #268.
