### ISSUE TITLE
IntelliJ freezes during interactive rebase

### ISSUE THREAD

**Issue by stovocor** [zielu/GitToolBox#28]
Since updating to 2016.3, an interactive rebase blocks IDEA completely on the first try. The status message shows "Rebasing..." but the GUI is not updated anymore.

My process list shows a "git4idea.rebase.GitRebaseEditorMain". If I kill that process, IDEA displays an error "There was a problem with the editor...". After that, I have to abort the rebase and try again. On the second try, everything works as expected.

[According to an IDEA developer](https://youtrack.jetbrains.com/issue/IDEA-164994), this is caused by GitToolBox. If I can help by providing logs and stacktraces, please tell me where I can send them privately without publishing them on GitHub.

**Comment by zielu** [comment]
Hi, I'll take a look at this today

**Comment by zielu** [comment]
Fixed in 163.2.1
