### ISSUE TITLE
Multi Repository support for incoming changes not working

### ISSUE THREAD

**Issue by LostKatana** [zielu/GitToolBox#283]
Having two repositories in a folder and opening that folder results in non working plugin.

How to reproduce:

- create a folder and name it root
- import two existing repos
- update the remote of one of the repos
- git stat Status bar not showing any changes.

**Edit:**
Works in case a file is open for the specific repo having changes.
Only seems to fail when having no file open.

Proposed solution:
Show any change disregarding the repo the change is in or the opened file is from  in the Git Stat status bar.

**Comment by zielu** [comment]
Image one repo has 1 incoming, second has 2. What would you expect to see ? Some general info to effect that something is incoming ?

**Comment by zielu** [comment]
I'm leaning towards sum in brackets and details per repo in mouse-over tooltip.

**Comment by LostKatana** [comment]
Totally fine for me. In most cases I do not care for the amount per repo anyways.

**Comment by zielu** [comment]
@LostKatana you are using IDE 2020.2 or 2020.3 ?

**Comment by LostKatana** [comment]
Since a few days i'm on 2020.3

**Comment by zielu** [comment]
Done in 202.3.0 (2020.2), has to be ported to 203
