### ISSUE TITLE
GitToolBox Does Not Use Intellij IDE Password Function to Retreive Passwords

### ISSUE THREAD

**Issue by paulprrn** [zielu/GitToolBox#29]
In the Intellij IDE GitToolBox constantly requests password when periodically pulling requests from my git repository.  It does not file the password with the Master Password in the IDE.

It does work properly in WebStorm.

**Comment by terrdavis** [comment]
I also have this issue. Every time I start the IDE I have to enter my GitLab password. Is this normal?

**Comment by zielu** [comment]
I just call IntelliJ apis and have no special passwords handling. Could you check if the same happens if you run Git > Fetch from context menu.

**Comment by terrdavis** [comment]
@zielu Thanks for the pointer. It still happened when running git fetch. I enabled password storage (after failing to get gitlab ssh to work) and that fixed the problem.
