### ISSUE TITLE
Autofetch fails on macOS Catalina

### ISSUE THREAD

**Issue by borissim** [zielu/GitToolBox#291]
Autofetch reports the following error:
`Auto fetch failed
			dyld: Library not loaded: /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib
			Referenced from: /usr/local/bin/ssh
			Reason: image not found
			Could not read from remote repository.
			Please make sure you have the correct access rights
			and the repository exists.
`

It is related to the version of openssl (currently for me 1.1.1i) and installing an older version of openssl is not an ideal solution

**Comment by zielu** [comment]
Hi, you should be getting the same error when running `Git / Fetch`, if so just disable auto-fetch in plugin settings

**Comment by borissim** [comment]
Thanks! You are right, `git fetch` reports the same error, so not a GitToolBox issue.
Just in case someone else hits the same error, `brew update && brew upgrade` resolved the issue for me.
