### ISSUE TITLE
Intellij freezes when using link to update workspace

### ISSUE THREAD

**Issue by Clindbergh** [zielu/GitToolBox#293]
GitToolbox informs me when the remote was updated with a green popup containing a link to update my workspace. After I pressed the link I am presented a dialog to choose whether I want to merge or rebase (the same dialog Intellij presents when I choose 'Update project'). After I press 'Rebase' and 'OK', Intellij freezes and I can not use it anymore. 
This does not happen when I use 'Update project' directly.

**Comment by zielu** [comment]
Hi, which Idea and plugin version are you using ?

**Comment by zielu** [comment]
I managed to reproduce this on latest plugin version in 2020.3

**Comment by zielu** [comment]
Done in 203.4.4

**Comment by Clindbergh** [comment]
Excellent, thanks! I can confirm it works. 

Sorry I didn't respond. Didn't notice the comment. I was on the most recent release.
