### ISSUE TITLE
Preview tab (quick file preview) not working if GitToolBox enabled

### ISSUE THREAD

**Issue by sxurik** [zielu/GitToolBox#295]
Preview tab (aka Quick file preview) is a feature relatively new for Jetbrains. For webstorm it was introduced in the 2020.3 update. 

Sadly it is impossible to use it and GitToolBox at the same time.  As soon as the file opens in a preview tab it becomes a permanent tab. 

With GitToolBox disabled everything works as intended. 

The checkbox to enable the feature is here: `Settings -> Editor -> General -> Editor Tabs`. 

![image](https://user-images.githubusercontent.com/32016927/106470982-391b9f80-64b2-11eb-8b7a-400a282d465b.png)

**Comment by zielu** [comment]
Hi, one idea from top of my head - what happens if you disable inline blame ? `GitToolBox Global / Show editor inline "Blame"`

**Comment by zielu** [comment]
Disabling inline blame helps - now the question is why does it break ?

**Comment by sxurik** [comment]
Yup, checked it as well, disabling it works. I wish it was smth else, inline blame is super helpful.

**Comment by sxurik** [comment]
Smth else I noticed. 

When opening a file in the preview tab for the first time the preview tab quickly becomes a permanent tab. But opening the same file subsequently doesn't trigger the change, the file stays in the preview tab.

**Comment by zielu** [comment]
Done in 203.4.7
