### ISSUE TITLE
Sometimes the status bar not updated correctly

### ISSUE THREAD

**Issue by PhantomThief** [zielu/GitToolBox#30]
Sometimes after push(Cmd+Shift+K), the status bar didn't refresh and remain the 1 ↑.

IntelliJ IDEA 2016.3.1 Build #IU-163.9166.29, built on December 9, 2016
git version 2.11.0

**Comment by zielu** [comment]
This is known problem for now. As workaround you can use status bar > Git Stat > Refresh status
