### ISSUE TITLE
Settings are gone

### ISSUE THREAD

**Issue by diskostu** [zielu/GitToolBox#302]
GitToolBox 203.5.1
IntelliJ 2020.3.3

I cannot see the settings anymore. I don't know if it's because of a recent update.

![image](https://user-images.githubusercontent.com/574147/112817480-c4fd1280-9082-11eb-9684-3e06720d281c.png)

**Comment by zielu** [comment]
@diskostu yes, moved under Version Control now

**Comment by zielu** [comment]
It might be a good idea to add "dummy" pages in old config location to redirect to new one

**Comment by diskostu** [comment]
@zielu Thanks for the info, I can see the settings.

For some strange reason, I did not find the GitToolBox settings when searching for the name in the settings search field. Now, it works. 🤷‍♂️

I like the new location, makes sense. 😊
