### ISSUE TITLE
Options to support?

### ISSUE THREAD

**Issue by mallowigi** [zielu/GitToolBox#307]
Is there any link I can use to support the project? Thanks

**Comment by mallowigi** [comment]
bump

**Comment by zielu** [comment]
Hi, I'm exploring support options. First step in that direction is close-sourcing of the plugin effective today.

**Comment by ForsakenHarmony** [comment]
> First step in that direction is close-sourcing of the plugin effective today.

Does this mean you'll make it paid in the future?
If you do, I'd really appreciate having a one time price, not a subscription

**Comment by zielu** [comment]
I'm considering having free and paid versions. With features being available in both but with different convenience level. For example:
- free: branch cleanup with UI action
- paid: branch cleanup on schedule, configurable period after which branch is considered outdated

I will NOT remove existing features and make them paid. Just any new additions will follow model outlined above.

For now plugin will continue as free but closed source.

**Comment by mallowigi** [comment]
I'm looking forward to it. In the meanwhile contact me whenever you have a support page, I'll gladly support you.
