### ISSUE TITLE
When the plugin is turned on, Resolve Conflicts... in VCS/context does not work properly

### ISSUE THREAD

**Issue by ilyarrgh** [zielu/GitToolBox#314]
Not sure if this has been brought up in the past, or if it has already been fixed since it last happened to me about a month ago. 
 I've had issues using built in merge when this plugin is turned on.  

To reproduce run `git merge <branch>`.  This merge needs to result in unresolved conflicts.  Normally you are able to select `Resolve Conflicts...` from either the context menu, or from `VCS`.  This does not work correctly when plugin is active.  I had to disable it get it to work.  

I will track to see if it happens again and will update this issue.

**Comment by zielu** [comment]
Hi, so `Resolve` was visible but disabled ?

**Comment by ilyarrgh** [comment]
I believe so

**Comment by zielu** [comment]
So now the question is if disabling and restarting helped or just restarting 😀

**Comment by ilyarrgh** [comment]
I actually just had to do this and seems good to go.  Wish I had taken notes before.  Anyway, I think it's working great!  Love the plugin, by the way.

**Comment by zielu** [comment]
Ok, closing then
