### ISSUE TITLE
Support 2021.2

### ISSUE THREAD

**Issue by zielu** [zielu/GitToolBox#315]
Support 2021.2 EAP

**Comment by zielu** [comment]
GitRepository interface added / removed deprecated version - in order to avoid merging matrix build will be introduced.

**Comment by zielu** [comment]
It's out in EAP channel: https://github.com/zielu/GitToolBox#eap-builds

I did not push to release channel because it is first release from private repo

**Comment by zielu** [comment]
Matrix build needs more work so it's old-style release from branch

**Comment by KotlinIsland** [comment]
`Failed to load plugins from 'https://github.com/zielu/GitToolBox#eap-builds': org.xml.sax.SAXParseException; lineNumber: 82; columnNumber: 89; Attribute name "data-pjax-transient" associated with an element type "meta" must be followed by the ' = ' character.`

**Comment by zielu** [comment]
Done, supported in matrix build
