### ISSUE TITLE
Unable to authenticate thru SSH in login

### ISSUE THREAD

**Issue by WilFonseca** [zielu/GitToolBox#316]
I'm working with a repo that is located in GitHub Enterprise, and for login I use the company's authentication process, hence my account doesn't have a password that I can use to authenticate. Normally for this kind of scenarios I have set my SSH authentication, but the plugin doesn't seem to recognize it as it stills asking me constantly to login despite the plugin features work as expected.

Is there a way to authenticate thru SSH or to disable the login popup?

**Comment by zielu** [comment]
Hi, plugin uses built in IDE features for fetching. See https://github.com/zielu/GitToolBox/wiki/Manual#faq

**Comment by zielu** [comment]
No feedback, closing
