### ISSUE TITLE
Show full name for inline blame

### ISSUE THREAD

**Issue by sara1068** [zielu/GitToolBox#322]
Hello, 

I would love the inline blame to show the full name of authors. Currently it's only showing last name, which is rather confusing, given that my team members tend to have same last names due to ethnic reasons. Plus, in a company setting we always address others by first names, so sometimes it takes an extra search to confirm who that author really is - that undermines the power of this tool. 

Thanks.

**Comment by zielu** [comment]
Hi, checkout plugin configuration in `Settings / Version Control / GitToolBox`, Blame tab - there are multiple options to choose from.

**Comment by sara1068** [comment]
Hi zielu,

Thanks! Now it works! I didn't know how to configure GitTool Box.

**Comment by zielu** [comment]
Glad to help !
