### ISSUE TITLE
Show the uncommitted changes

### ISSUE THREAD

**Issue by lddsb** [zielu/GitToolBox#323]
just like the vscode GitLens plugin do:
![image](https://user-images.githubusercontent.com/20765867/122744951-16e8b980-d2bb-11eb-8773-0265bd7a0f66.png)

**Comment by zielu** [comment]
Hi, so it's like file modification timestamp or is it more accurate and tracks line modification ?

**Comment by lddsb** [comment]
Looks like file modification timestamp, more accurate and tracks line modification is better. File modification timestamp is enough.

**Comment by zielu** [comment]
Done in 203/212.8.0
