### ISSUE TITLE
Inconsistent status icon

### ISSUE THREAD

**Issue by Leon99** [zielu/GitToolBox#326]
Git status icon looks "3D" while all others are flat, spoils otherwise perfect UX in Rider.

![image](https://user-images.githubusercontent.com/6840381/127583257-c5b5667d-68a4-49a5-8766-e221998a09af.png)

**Comment by zielu** [comment]
Hi, I'll add flat icon variants

**Comment by Leon99** [comment]
Many thanks @zielu! Looking forward to seeing it.

**Comment by zielu** [comment]
Done in 203/212.8.0
