### ISSUE TITLE
Account Lockouts When GitToolBox installed

### ISSUE THREAD

**Issue by hersh412** [zielu/GitToolBox#327]
Hello,

I've had this issue for a little over 2 years now. Running a 2018 Macbook Pro with OSX 10.15.7. I just downloaded the newest version of IntelliJ Idea Community Edition 2021.2 and figured I would try GitToolBox again. However, I had to uninstall it. When I have IntelliJ open with GitToolBox installed, my domain account will continually be locked out at the enterprise level. The Github password is correct as I can fetch/push/commit/etc. I do have to use a proxy for IntelliJ which is setup in my preferences. What could be causing this?

**Comment by zielu** [comment]
Hi, my guess would be that auto-fetch running at set intervals is flagged as an attack. You can try disabling it.

**Comment by zielu** [comment]
Did disabling auto-fetch help ?

**Comment by hersh412** [comment]
Yes that has resolved my issue, thank you.
