### ISSUE TITLE
Chinese display garbled

### ISSUE THREAD

**Issue by houkunlin** [zielu/GitToolBox#329]
Plugin Version : 212.7.4
IDE: IntelliJ IDEA 2021.2 (Ultimate Edition)、WebStorm 2021.2

中文显示乱码
Chinese display garbled
![idea64_dz9tVUYOSB](https://user-images.githubusercontent.com/12333292/128441490-00056025-2360-49c8-8569-5a449973d010.png)

**Comment by houkunlin** [comment]
今天更新了插件的最新版本，更新后显示中文乱码，在上一个版本中未存在此问题，在上一个版本中一切正常；

The latest version of the plug-in was updated today. After the update, Chinese garbled characters are displayed. This problem does not exist in the previous version, and everything is normal in the previous version.

**Comment by changshunxu520** [comment]
+1
The latest version of the plug-in was updated today. After the update, Chinese garbled characters are displayed. This problem does not exist in the previous version, and everything is normal in the previous version.

**Comment by chenyanli587** [comment]
中文乱码的问题貌似是今天更新完插件出现的
![QQ截图20210806102433](https://user-images.githubusercontent.com/8829268/128446563-08079ad9-8b72-4961-8121-bc0ab229b1f1.png)

**Comment by changshunxu520** [comment]
我认为这版本的插件没有支持 FallBackFont中设置的字体，仅仅是支持了MainFont 设置的字体，所以导致中文乱码。你可以把主字体设置为支持中文的，它就能正常显示了。
I think this version does not support FallBackFont, it just uses MainFont ，So it causes Chinese garbled。You can set the main font to support Chinese, and it will be displayed normally.

**Comment by houkunlin** [comment]
> 我认为这版本的插件没有支持 FallBackFont中设置的字体，仅仅是支持了MainFont 设置的字体，所以导致中文乱码。你可以把主字体设置为支持中文的，它就能正常显示了。
> I think this version does not support FallBackFont, it just uses MainFont ，So it causes Chinese garbled。You can set the main font to support Chinese, and it will be displayed normally.

我目前的IDEA、WebStorm都是安装了中文插件包，所有的中文（菜单、设置、编辑器）都是显示正常

**Comment by changshunxu520** [comment]
> > 我认为这版本的插件没有支持 FallBackFont中设置的字体，仅仅是支持了MainFont 设置的字体，所以导致中文乱码。你可以把主字体设置为支持中文的，它就能正常显示了。
> > I think this version does not support FallBackFont, it just uses MainFont ，So it causes Chinese garbled。You can set the main font to support Chinese, and it will be displayed normally.
> 
> 我目前的IDEA、WebStorm都是安装了中文插件包，所有的中文（菜单、设置、编辑器）都是显示正常

我知道，你可以按照我说的去尝试一下呢？我认为是插件的问题，在没有修复之前可以按照我说的去试试呢？

**Comment by houkunlin** [comment]
> > > 我认为这版本的插件没有支持 FallBackFont中设置的字体，仅仅是支持了MainFont 设置的字体，所以导致中文乱码。你可以把主字体设置为支持中文的，它就能正常显示了。
> > > I think this version does not support FallBackFont, it just uses MainFont ，So it causes Chinese garbled。You can set the main font to support Chinese, and it will be displayed normally.
> > 
> > 
> > 我目前的IDEA、WebStorm都是安装了中文插件包，所有的中文（菜单、设置、编辑器）都是显示正常
> 
> 我知道，你可以按照我说的去尝试一下呢？我认为是插件的问题，在没有修复之前可以按照我说的去试试呢？
> ![image](https://user-images.githubusercontent.com/16171624/128447039-9d6caf51-6b95-46eb-bae2-2a648b08db58.png)

试了确实能用，只能当作临时的解决方案了，换了一个字体后突然有点不适应

**Comment by changshunxu520** [comment]
> > > > 我认为这版本的插件没有支持 FallBackFont中设置的字体，仅仅是支持了MainFont 设置的字体，所以导致中文乱码。你可以把主字体设置为支持中文的，它就能正常显示了。
> > > > I think this version does not support FallBackFont, it just uses MainFont ，So it causes Chinese garbled。You can set the main font to support Chinese, and it will be displayed normally.
> > > 
> > > 
> > > 我目前的IDEA、WebStorm都是安装了中文插件包，所有的中文（菜单、设置、编辑器）都是显示正常
> > 
> > 
> > 我知道，你可以按照我说的去尝试一下呢？我认为是插件的问题，在没有修复之前可以按照我说的去试试呢？
> > ![image](https://user-images.githubusercontent.com/16171624/128447039-9d6caf51-6b95-46eb-bae2-2a648b08db58.png)
> 
> 试了确实能用，只能当作临时的解决方案了，换了一个字体后突然有点不适应

我也是一样感觉很难受,等着修复吧，我觉得应该很快就会修复的吧

**Comment by houkunlin** [comment]
@changshunxu520 目前的办法也就只能等下一个版本修复了

**Comment by chenyanli587** [comment]
> > > > 我认为这版本的插件没有支持 FallBackFont中设置的字体，仅仅是支持了MainFont 设置的字体，所以导致中文乱码。你可以把主字体设置为支持中文的，它就能正常显示了。
> > > > I think this version does not support FallBackFont, it just uses MainFont ，So it causes Chinese garbled。You can set the main font to support Chinese, and it will be displayed normally.
> > > 
> > > 
> > > 我目前的IDEA、WebStorm都是安装了中文插件包，所有的中文（菜单、设置、编辑器）都是显示正常
> > 
> > 
> > 我知道，你可以按照我说的去尝试一下呢？我认为是插件的问题，在没有修复之前可以按照我说的去试试呢？
> > ![image](https://user-images.githubusercontent.com/16171624/128447039-9d6caf51-6b95-46eb-bae2-2a648b08db58.png)
> 
> 试了确实能用，只能当作临时的解决方案了，换了一个字体后突然有点不适应

换字体就算了，还是等着作者修复吧，现在只是一行代码看着不舒服，换字体是满屏不舒服。

**Comment by changshunxu520** [comment]
@chenyanli587 或者大家可以选择降级回去，哈哈

**Comment by houkunlin** [comment]
我先等几天看看会不会出修复版本，反正今天周五了，下周不修复的话估计要降一个版本了，不然就只能忍着那几个方框了

**Comment by zielu** [comment]
Can you check if enabling font ligatures solves the issue ?

**Comment by houkunlin** [comment]
> Can you check if enabling font ligatures solves the issue ?
> There are two code paths depending on that setting or checking if font can be displayed and I think that part that does the detection is wrong. I'll just remove one of the paths and it will always use one that takes fallback font into account.
> 
> #277 for reference

经过测试验证，启用字体连写能够正常显示中文文字，关闭字体连写则中文显示乱码。

After testing and verification, the Chinese characters can be displayed normally when font chaining is enabled, and Chinese characters will be displayed garbled when font chaining is disabled.

![image](https://user-images.githubusercontent.com/12333292/128458860-5d11dd43-4ff1-43af-92a1-9f886e807251.png)

**Comment by zielu** [comment]
Ok, I'll release the fix today

**Comment by 393480846** [comment]
> 
> 
> > > 我认为这版本的插件没有支持 FallBackFont中设置的字体，仅仅是支持了MainFont 设置的字体，所以导致中文乱码。你可以把主字体设置为支持中文的，它就能正常显示了。 
> > > 我觉得这个版本不支持FallBackFont，只是使用MainFont，所以会造成中文乱码。可以设置主字体支持中文，就可以正常显示了。
> > 
> > 
> > 我目前的IDEA、WebStorm都是安装了中文插件包，所有的中文（菜单、设置、编辑器）都是显示正常
> 
> 我知道，你可以按照我说的去尝试一下呢？我认为是插件的问题，在没有修复之前可以按照我说的去试试呢？
> 我说的插件是GitToolBox这个插件
> ![图像](https://user-images.githubusercontent.com/16171624/128447039-9d6caf51-6b95-46eb-bae2-2a648b08db58.png)

可怕的是我发现他不是用的这个字体
![图片](https://user-images.githubusercontent.com/50394882/128484033-85b8d1fe-bf9b-483f-b5a1-43fd5994f177.png)

**Comment by Eli2021** [comment]
更新乱码+1

**Comment by Eli2021** [comment]
插件版本：212.7.4
![image](https://user-images.githubusercontent.com/25074704/128485837-871e9f5f-aff1-4b3a-bbbc-12c114ce0e8c.png)

**Comment by zielu** [comment]
212.7.4 will also be affected - same codebase - same workaround

**Comment by zielu** [comment]
Done in 203/212.7.5
