### ISSUE TITLE
two different git project shows the same git repo

### ISSUE THREAD

**Issue by astroshot** [zielu/GitToolBox#330]
![图片](https://user-images.githubusercontent.com/24741314/128587906-ced1724c-e4d2-4b65-a2f7-c3c1a64f2c4a.png)

Here is my problem:

I have 2 modules not using git submodule. Each of them has its own git upstream project. They just share the same prefix "famg" and they are placed in the same directory(~/Projects/Java/medical). While since 203.6.6 version(I installed 203.7.5 version in the above picture ), my module "famg-doctor" always shows git status info of "famg" including branch name and commit changes in project view.  

But 203.5.10 version can displays status of each module as the following image:

![图片](https://user-images.githubusercontent.com/24741314/128588027-1e4ca9b5-bf11-4461-a360-ea1f0efb285e.png)

I'm looking forward to your attention, and thank you for developing such a convenient plugin! 🙏

Here is my IDEA version info:

```text
IntelliJ IDEA 2020.3.4 (Community Edition)
Build #IC-203.8084.24, built on April 27, 2021
Runtime version: 11.0.10+8-b1145.96 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.16
GC: ParNew, ConcurrentMarkSweep
Memory: 2014M
Cores: 4
Non-Bundled Plugins: IdeaVIM, com.tylerthrailkill.intellij.solarized, com.werfad, net.vektah.codeglance, izhangzhihao.rainbow.brackets, zielu.gittoolbox, String Manipulation, com.dubreuia, MavenRunHelper
```

**Comment by zielu** [comment]
Done in (203/212).7.6
