### ISSUE TITLE
Commit message validation: multiline commit messages aren't allowed

### ISSUE THREAD

**Issue by samolisov** [zielu/GitToolBox#332]
Dear GitToolBox plugin developers,

I'm trying to use GitToolBox in IntelliJ IDEA and get a lot of false positive commit message validation reports. I played a bit with the validation regexp and have found no way to pass a message with a body, not only the header line. So, the header line validates fine regarding to my regexp but when I skip a line, as git suggests, and write something, the plugin displays the "Commit Message Invalid" dialog.

I tried the following regexp to let GitToolBox just skip two lines but unfortunately it doesn't work too:

```
(?:docs|style|test|runtime)(?:\(.*\))?:
(?:\n|\r|\r\n)
(?:\n|\r|\r\n)
[A-Z].*\s#\d+
```

If I remove those new line clauses and use the following:

```
(?:docs|style|test|runtime)(?:\(.*\))?:
[A-Z].*\s#\d+
```
the first line of the commit message successfully validates:

`docs( 12): Initial commit #124`  - ok, I can make a commit

But when I add a message body:

```
docs( 12): Initial commit #124

Some details are here
```

The plugin rejects this commit message.

Could you  let me know how to configure the plugin to validate commit messages with the body?

Thank you very much for your work, this is a really helpful plugin.

**Comment by zielu** [comment]
Hi, I'll check what options are used to create the regexp. I suspect miltiline or dot all is missing.

**Comment by zielu** [comment]
There is neither dot all nor multiline set. I'll add support to be able to use these 2 options.

**Comment by zielu** [comment]
It will look like this
<img width="820" alt="image" src="https://user-images.githubusercontent.com/464103/132571516-9812c8c6-33b1-478a-a0ca-6cca90b980e4.png">

**Comment by samolisov** [comment]
@zielu Thank you very much for the investigation and suggestions. I've updated the GitToolBox plugin and tried: now the multiline commits can also be checked. I think the issue can be closed.

Thank you again.

**Comment by zielu** [comment]
Hmm, funny thing - looks like by accident I produced regex that works for multilines too. I''l reopen and close when new validation UI is released - which is very soon :)(

**Comment by zielu** [comment]
Done in (203/212).7.10
