### ISSUE TITLE
Where is "Add to .gitignore" button?

### ISSUE THREAD

**Issue by akay0214** [zielu/GitToolBox#334]
Omg, spent about an hour looking for this button.

**Comment by zielu** [comment]
Hi, it's not provided by my plugin, never was. You need .ignore plugin for that.

**Comment by akay0214** [comment]
Hi @zielu , could you please add this button? It will improve the value a lot, it's one of those essential thing most devs are looking for. Thanks.

**Comment by zielu** [comment]
Hi, sorry but I won't be duplicating feature already available in Jetbrains plugin. I see little value in this.

**Comment by akay0214** [comment]
@zielu  I don't think it's a duplicate. **.ignore** plugin just allows you to generate the file. I was talking about working with the project directory. For instance, right click on the file/directory and add it to the gitignore, instead of going to the file and specify ignore paths manually.

**Comment by zielu** [comment]
From .ignore plugin description:
`Add a selected file/directory to Gitignore rules from the popup menu`
