### ISSUE TITLE
Where is the pop-up up-to-date?

### ISSUE THREAD

**Issue by SuperJoJoD** [zielu/GitToolBox#335]
I cannot find the pop-up up-to-date when the mouse hovers on the up-to-date.
I use this feature much in the previous version.
How can I get it again the latest version?

Best regards,
JJD

**Comment by zielu** [comment]
Hi, you mean popup on hovering on statusbar ? I'll take a look what happened.

**Comment by zielu** [comment]
@SuperJoJoD looks like I lost it when migrating code to kotlin, fix incoming

**Comment by zielu** [comment]
Done in (203/212).7.7
