### ISSUE TITLE
Disable while stash/rebasing?

### ISSUE THREAD

**Issue by boardtc** [zielu/GitToolBox#336]
I wanted to do a git stash & rebase and I was worried the auto-refresh would mess with this?

I could not see a way to disable the plugin in project settings so I disabled the plugin in settings,

Did I need to worry, or would auto-refresh see a rebase was in operation?

Thanks!

p.s I would like to add a question label but I can't edit side options.

**Comment by zielu** [comment]
Done in (203/212).7.7
