### ISSUE TITLE
Cant save "Auto fetch" setting

### ISSUE THREAD

**Issue by aliusa** [zielu/GitToolBox#339]
Can't save settings after I unchecked "Auto fetch" setting - "Apply" or "OK" doesn't work.
GitToolBox: 212.7.7
PhpStorm: 2021.2.1 (PS-212.5080.71)

**Comment by zielu** [comment]
Hi, in Version Control / GitToolBox or Version Control / GitToolBox / GitToolBox Project

**Comment by aliusa** [comment]
Version Control -> GitToolBox
all projects settings

**Comment by zielu** [comment]
So you uncheck Auto fetch but Apply button does not become active, correct ?

**Comment by aliusa** [comment]
1. I uncheck "Auto fetch"
2. "Apply" button becomes active (pressable)
3. I try to press "Apply" or "OK"
4. nothing happens

**Comment by zielu** [comment]
But it is disabled when you reopen configuration ? Because there is no special feedback when auto-fetch is disabled - it just stops being executed.

**Comment by aliusa** [comment]
It ("Auto fetch" option) is disabled when configuration is reopened. It is disabled because changes haven't been saved because of "Apply"/"OK" buttons not responding.

Tested all GitToolBox options... (global and project scope) - any change will "Apply" button to not respond. :)

**Comment by zielu** [comment]
What do you mean exactly by ""Apply" button to not respond." - it is grey out or it blocks. A screen recording could help.

**Comment by aliusa** [comment]
When I press "Apply" - it does not work (does not save settings).
Here's a screenshot - when I pressed "Apply" button - it indicates (blue border) that I pressed, but it does not apply (save) settings.
![image](https://user-images.githubusercontent.com/9768908/132805916-5defeb7c-4020-40fd-b708-1cddd7aaaae0.png)

**Comment by zielu** [comment]
Could you gather the logs and attach them ?  I suspect there might be some exception being thrown during save.
See https://github.com/zielu/GitToolBox/wiki/AdvancedManual#accessing-logs

**Comment by aliusa** [comment]
Bug disappeared as of GitToolBox 212.7.8

**Comment by zielu** [comment]
Aha the extras config - thing is removed in 212.7.8 :)
