### ISSUE TITLE
No blame on blank lines?

### ISSUE THREAD

**Issue by WilfulTravesty** [zielu/GitToolBox#342]
Is there any way to disable the blame overlay just on blank lines? I don't find it useful on blank lines and it is distracting because it makes the line look non-empty until my brain processes it.

**Comment by zielu** [comment]
Hi, there is no such feature. I'll add it to the backlog

**Comment by WilfulTravesty** [comment]
Lol. Came to file a feature request for this and found my own that I forgot about.

**Comment by zielu** [comment]
It means it's time for me to do something about it :D

**Comment by zielu** [comment]
Done in 600.0.7+242
