### ISSUE TITLE
Commits are not showing in Intellij 2021.2.2 

### ISSUE THREAD

**Issue by sendev1** [zielu/GitToolBox#343]
It used to show the commits when I click the line on the file in intellij but its no longer shows that once I updated to Intellij 2021.2.2

**Comment by zielu** [comment]
Hi, feature is there and working. As first step you might want to check plugin config if everything looks correct.

**Comment by sendev1** [comment]
Thanks, after intelliji update and pulgin was asking for update and then now it works. thanks for quick response. closing this issue
