### ISSUE TITLE
212.7.10 seems to break -> commit in IntelliJ IDEA

### ISSUE THREAD

**Issue by mrbscreen** [zielu/GitToolBox#344]
See [IDEA-278473](https://youtrack.jetbrains.com/issue/IDEA-278473)

Downgrade to GitToolBox to 212.7.7 fixes the Problem.

What steps will reproduce the issue?
1. Try to commit when there are warnings in your files
2. Click on commit anyway & push
3. The checks will re-run and you have to click it again
What is the expected result?
The warnings will get ignored and the commit process continues.

What happens instead?
The commit checks re-run which leads to an "infinite loop"

**Comment by zielu** [comment]
@mrbscreen so conditions to reproduce this are:
- use non-modal commit interface
- enable Before commit / Analyze code
- have file with warnings

**Comment by mrbscreen** [comment]
Hi @zielu,

thank you for your response.

That is right, but at least one warning/error is sufficient.

No, it is not enabled. The only enabled option is: “Commit dialog branch completion”.

**Comment by zielu** [comment]
Ok, I managed to reproduce it. Now I need to understand what is wrong.

**Comment by zielu** [comment]
Fixed in 203/212.7.11
