### ISSUE TITLE
Project View Decoration not working on subrepositories anymore

### ISSUE THREAD

**Issue by Darllao** [zielu/GitToolBox#345]
I am really not sure what causes this issue, whether it is a wrong configuration or a bug. I have the latest v212.7.11 (tried also with older versions, did not change anything)

I have a git repo containing several git repositories (all are direct children / subfolders of the parent) which have worked perfectly with displaying the _status / numbers of ahead / behind / branch_ etc. in the Project View but since (i am not exactly sure since when) approximately 3 weeks I do not see this information behind the subrepositories anymore. Toggling the "Show Project View decoration" only enables / disables the decoration that I am already seeing (the parent repository)

The repos are all configured in the "Version Control" settings of PHPStorm.

PHPStorm 2021.2.2 (Build PS-212.5284.49)

**Comment by zielu** [comment]
Hi, I'll take a look but I don't remember changing anything in that area of code recently.

**Comment by Darllao** [comment]
> Hi, I'll take a look but I don't remember changing anything in that area of code recently.

Is there anything for me to provide you to assist you in that process? Some information ?

**Comment by zielu** [comment]
You could enable logging from category `#zielu.gittoolbox.blame.ui.projectView:trace`. https://github.com/zielu/GitToolBox/wiki/AdvancedManual#logging

Close and open the project and wait until status is shown. This should give some idea what is wrong.

**Comment by zielu** [comment]
So far cannot reproduce
![image](https://user-images.githubusercontent.com/464103/134484753-e75de08e-15b2-41c9-ab75-28b63aa91e6d.png)

**Comment by Darllao** [comment]
I created a test repository with several subrepos too and it worked like a charm. I really do not understand why our big project lacks this feature.

What is noticable from the logs I read is that there are a lot of messages considering unsupported nodes, including all the subrepositories which dont have the project view decoration. For example the subdirectory middleware logs in chronological order:

```
(possibly relevant)
2021-09-23 10:42:07,500 [   9723]   WARN - a.repo.GitUntrackedFilesHolder - Ignoring ignored file under another root: /path/to/main/repository/middleware; root: /path/to/main/repository; mapped root: /path/to/main/repository/middleware 
................
2021-09-23 10:42:08,245 [  10468]  DEBUG - ittoolbox.blame.ui.projectView - node FileNode is dir file:////path/to/main/repository/middleware module root 
2021-09-23 10:42:08,245 [  10468]  TRACE - ittoolbox.blame.ui.projectView - Unsupported node middleware, type=FileNode, name=middleware, title=null, parent=RootNode 
...............
2021-09-23 10:42:16,156 [  18379]  DEBUG - ittoolbox.blame.ui.projectView - node PsiDirectoryNode is dir file:////path/to/main/repository/middleware module root 
2021-09-23 10:42:16,156 [  18379]  TRACE - ittoolbox.blame.ui.projectView - Unsupported node .run, type=FileNode, name=.run, title=null, parent=RootNode 
2021-09-23 10:42:16,156 [  18379]  DEBUG - ittoolbox.blame.ui.projectView - Repo for dir middleware is: /path/to/main/repository/middleware 
```

**Comment by zielu** [comment]
@Darllao so `Unsupported node middleware, type=FileNode, name=middleware` is actually a directory ? Maybe it's a symlink or smth ?

**Comment by Darllao** [comment]
@zielu yes, middleware is a repository.
the filestructure is
[<img src="https://i.imgur.com/YLumK6f.png">](https://i.imgur.com/YLumK6f.png)

**Comment by zielu** [comment]
Could you check is `ls -la` what does it say for it ?

**Comment by Darllao** [comment]
drwxrwxr-x  6 myname mygroup     4096 Aug 10 12:31 middleware

**Comment by zielu** [comment]
Second batch of logs from `2021-09-23 10:42:16` suggest that at least it was recognised as git root, but I don't know yet why decoration was not added.

**Comment by zielu** [comment]
Could you switch to EAP build channel as described here: https://github.com/zielu/GitToolBox#eap-builds ? There will be a new 212.7.12 in there in a moment that should handle Unsupported FileNode. It seems there was a hole in the logic for this case.

**Comment by Darllao** [comment]
This patch instantly fixed the issue! Great work my friend, thank you very much!

**Comment by zielu** [comment]
Good to hear that !

**Comment by zorohu** [comment]
@zielu I had the same problem after upgrading from `IDEA 2020.3.4` to a later version, and tried uninstalling and reinstalling the plugin.

GitToolBox `203.8.5` `212.8.5` both have the same problem
![image](https://user-images.githubusercontent.com/24402746/155724446-d097a407-0dbf-47de-9d52-4452ab2f8062.png)

**Comment by zielu** [comment]
@zorohu are those full violet nodes sub git repositories under top-level with `master` or only subdirectories ? Reason I'm asking is because I made changes recently to have project view decoration only on top-level node per repository in project view, repeating same information was leading to clutter in my opinion.
There is one fix to this logic in EAP channel (https://github.com/zielu/GitToolBox#eap-builds) you could consider switching to see if it changes anything.

I might consider adding a config option to either enable decoration top-level only or all of them.

**Comment by zielu** [comment]
In general it works as intended but I'll add an option to either decorate only top-level or all of them. I created #388 for tracking.

**Comment by zorohu** [comment]
Ok, then I think this is a bug. My current IDEA version is `2021.1.3`. The version of GitToolBox is`3.7.15` which is fine. Problem occurred after upgrade,`203.8.5`  `EAP203.8.7`. And I tried to upgrade IDEA to`2021.2.2,`GitToolBox`212.8.5` also has problems

This is my IDEA`2021.1.3` and gittoolbox `203.7.5`. Use effect
![image](https://user-images.githubusercontent.com/24402746/155992348-e34f14c8-8900-47a1-a62c-b1cb2188bae8.png)

**Comment by zielu** [comment]
No, it is definitely not a bug.

**Comment by zorohu** [comment]
ok, i can understand it's an optimization right?
