### ISSUE TITLE
Idea: Commit mesaage complete

### ISSUE THREAD

**Issue by DokanBoy** [zielu/GitToolBox#346]
Git commit message suggestions based on branch name.
For example: `feature/TASK-1` suggest `[TASK-1]`, `bugfix/TASK-2` ->  `[TASK-2]`

**Comment by zielu** [comment]
It's already there, you need to add pattern completion formatters in plugin config.

**Comment by DokanBoy** [comment]
Amazing Can you tell me how to do this?  I tried to compose a regex, but it didn't work for me

**Comment by zielu** [comment]
Something like `(?:.+/)*(\w+-\d+).*` should do the trick

**Comment by zielu** [comment]
I created #347 for template support in pattern formatter

**Comment by zielu** [comment]
Closing - will continue in feature ticket
