### ISSUE TITLE
False Positive - BitDefender Security Alerts

### ISSUE THREAD

**Issue by Perforce-Chris** [zielu/GitToolBox#352]
Our company uses this plugin with IntelliJ IDEA.  It is causing security alerts with BitDefender.  I reached out to JetBrains & they wrote: Do you think you could file an issue to this plugin's vendor at https://github.com/zielu/GitToolBox ?
We will think of how could we prevent this kind of issues during plugins onboarding further.
![BitDefender-Report](https://user-images.githubusercontent.com/92925211/138271848-5ea94b1e-de6c-4303-a8e1-a8553eb8feb8.jpg)

**Comment by zielu** [comment]
No feedback, closing
