### ISSUE TITLE
Typo in message while validating commit message

### ISSUE THREAD

**Issue by tboba** [zielu/GitToolBox#356]
Hi,
I found a typo, when I was trying to commit my changes.
There is two "the" in the message dialog.

![typo](https://user-images.githubusercontent.com/23281839/141144966-85e5722c-2aa2-4bb8-9c04-5a9f82fd543b.png)

Steps to reproduce:
1. Make a changes in code.
2. Try to commit by commit dialog (ctrl + K).
3. Check "Validate commit message".
4. Try to commit. 

IJ version: IU-212.5457.46, 
JRE 11.0.12+7-b1504.40x64 
OS: Windows 10

**Comment by zielu** [comment]
Done in 203/212.8.0
