### ISSUE TITLE
[Cosmetic] Typo in the string "Uncommited changes"

### ISSUE THREAD

**Issue by ddalcino** [zielu/GitToolBox#364]
When I have uncommitted changes, GitToolBox prints a string after the end of the line that says "uncommited changes". This message is misspelled: there are two `t`s in the word "uncommitted".

I am grateful for all your work on this extremely useful plugin, and I hate to bother you for such a minor issue. Hopefully this will be trivial to fix.

Thank you for all your hard work!

**Comment by zielu** [comment]
Hi, it seems that single t is a common misspelling: https://dictionary.cambridge.org/pl/spellcheck/english/?q=commited

**Comment by ddalcino** [comment]
> Hi, it seems that single t is a common misspelling: https://dictionary.cambridge.org/us/spellcheck/english/?q=commited

I'm not sure what you mean by this. Are you trying to say that since the word is commonly misspelled, it's correct to misspell it? Many English words have multiple correct spellings, like ["colour" (UK)](https://dictionary.cambridge.org/us/dictionary/english/colour) and ["color" (US)](https://dictionary.cambridge.org/us/dictionary/english/color). This is not the same as "committed" (correct) and "commited" (misspelled). Consider this commonly misspelled word: https://dictionary.cambridge.org/us/spellcheck/english/?q=acheive. It is never correct to spell "achieve" (correct) as "acheive" (misspelled).

**Comment by zielu** [comment]
Done in 203/212.8.3

**Comment by unikitty37** [comment]
I've installed 212.8.3, but the old spelling still seems to be there:

![image](https://user-images.githubusercontent.com/139183/145572354-9aaad6e7-a6df-4364-a7b5-c13150fe6037.png)
![image](https://user-images.githubusercontent.com/139183/145572371-1a6979ba-121a-4a60-b2d1-bcf831c8841f.png)

**Comment by ddalcino** [comment]
> I've installed 212.8.3, but the old spelling still seems to be there:

I can confirm this; the word "uncommitted" is still misspelled in v212.8.3, although the change notes claim otherwise.

**Comment by zielu** [comment]
Fixed for good in 203/212.8.4 - I must have reverted it by accident.

**Comment by ddalcino** [comment]
> Fixed for good in 203/212.8.4 - I must have reverted it by accident.

I can confirm that this is now fixed. Thanks!
