### ISSUE TITLE
Jetbrains Client

### ISSUE THREAD

**Issue by ReptoxX** [zielu/GitToolBox#369]
Hey,

have you considered adding support for Jetbrains Client?

Regards

**Comment by zielu** [comment]
@ReptoxX I search for it and it's not clear for me which Jetbrains product / feature you are referring to.

**Comment by ReptoxX** [comment]
I just figured out that you most likely can not support this product as it does not have support for the built-in git4idea extension.

JetBrains Client is a thin client for remote development through JetBrains Gateway. Download the Gateway, setup a remote connection and you'll connect through the JetBrains Client.

**Comment by moshuipan** [comment]
+1 need help

**Comment by zielu** [comment]
Comment from ReptoxX is correct - my plugin has hard dependency on Jetbrains Git plugin (git4idea). This feature is not possible until their plugin works with Gateway

**Comment by zielu** [comment]
https://gittoolbox.lukasz-zielinski.com/docs/jetbrains-gateway/
