### ISSUE TITLE
Error in visual mode in code scala using ideavim + GitToolBox

### ISSUE THREAD

**Issue by Miuler** [zielu/GitToolBox#371]
I'm using IDEA (Build #IU-213.5744.223, built on November 27, 2021), plugin ideavim and scala plugin. My GitToolBox have fail and my vim keybinding in scala code fail the visual mode.

**Comment by zielu** [comment]
Hi, you do not provide any actionable details:
- GitToolBox have fail - meaning what exactly
- vim keybinding in scala code fail the visual mode - what is happening exactly

**Comment by zielu** [comment]
No feedback
