### ISSUE TITLE
Message validation regular expression is not working as before

### ISSUE THREAD

**Issue by frontendplace** [zielu/GitToolBox#375]
after update version (2021-12-12T17:33:10.557744) 
previously accepted regexp : WK-\d{5} .* was working in message validation 
a comment starting with "WK-00000 some text" was accepted before but now not anymore

**Comment by zielu** [comment]
Hi, could you check commit validation plugin config on project level ? There might be an issue if you used checkbox in commit dialog.

**Comment by zielu** [comment]
No feedback

**Comment by frontendplace** [comment]
Sorry for late response. Yes I use the checkbox in the check commit message in the project. As I have done before. Shouldn't I do that?

**Comment by zielu** [comment]
Ok I'll dive one more time into this

**Comment by zielu** [comment]
Can you enable logs from category `#zielu.gittoolbox` ? During validation there should be an entry like `Validate commit message with expression`. I'm curious what it will print.

https://github.com/zielu/GitToolBox/wiki/AdvancedManual#logging

**Comment by frontendplace** [comment]
This is in de log:
#zielu.gittoolbox - Validate commit message with expression: '(?:fix|chore|docs|feat|refactor|style|test)(?:\(.*\))?: [A-Z].*\s#\d+' 

This is what I have in the settings: 
in plugin:
check pattern match: on , 
pattern: WK-\d{5}\s.*  with a green checkmark after it

In commit dialog: before commit, message matches pattern: on

Commit message used: WK-00000 test

**Comment by zielu** [comment]
Looks like this is the case of "funky checkboxes" - see #358. There are 2 levels on configuration - app and project - if you used checkbox from commit dialog to disable validation then a project override was created and it does not copy settings from app level.
I'm working on a fix but it is surprisingly difficult issue.

**Comment by frontendplace** [comment]
I see now for the first time the extra project level override. I did not see that before and defaults to another setting I see that now
