### ISSUE TITLE
Missing gitmoji completion in non-modal commit UI

### ISSUE THREAD

**Issue by scruel** [zielu/GitToolBox#376]
![GIF](https://user-images.githubusercontent.com/16933298/147016812-0ff78ab4-3720-4742-a7fd-5505c912ccd9.gif)

No completion if start with “:”.

IntelliJ IDEA 2021.2.4 (Ultimate Edition)
Build #IU-212.5712.43, built on December 21, 2021
Runtime version: 11.0.13+8-b1504.49 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2016M
Cores: 8

**Comment by zielu** [comment]
On it

**Comment by zielu** [comment]
Looks like completion is not called at all for ':'. I need to dig into IDE internal to check where it's getting blocked

**Comment by zielu** [comment]
It's impossible to fix - IDE cuts out `:` very early in completion processing and my completion providers are simply not called.

**Comment by scruel** [comment]
May we can try to report it as a BUG?
https://youtrack.jetbrains.com/

**Comment by scruel** [comment]
I have created an issue to track this, your can visit and comment more detail info: https://youtrack.jetbrains.com/issue/IDEA-285549

**Comment by zielu** [comment]
Investigate approach from `GitCommitCompletionContributor`

**Comment by zielu** [comment]
Done in x.8.5
