### ISSUE TITLE
[BUG] saved selected files in rollback menu

### ISSUE THREAD

**Issue by IWareQ** [zielu/GitToolBox#380]
**Describe the bug**
The file is not saved when rolling back

**To Reproduce**
1. Select the files you want to rollback
2. Click on the rollback button
3. Look at how your sample files are not selected

**Expected behavior**
Saving a selection of files

**Plugin version**
212.8.4

Kotlin: 213-1.6.10-release-923-IJ5744.223

**IDE version**
IntelliJ IDEA 2021.3.1 (Ultimate Edition)
Build #IU-213.6461.79, built on December 28, 2021

**Screenshots**
![image](https://user-images.githubusercontent.com/51165317/149764537-153b44f6-cbbb-4a96-af56-a63d5d334a06.png)
![image](https://user-images.githubusercontent.com/51165317/149764615-cf22fbb6-bdd3-4792-ac2a-82c861edab98.png)

**Comment by IWareQ** [comment]
Please fix

**Comment by zielu** [comment]
Hi, from the description I don't understand what is wrong. Describe exactly which UI are you using for rollback (dialog or tool window) and why do you expect that after rollback files should be selected - afaik they disappear from UI

**Comment by IWareQ** [comment]
> Hi, from the description I don't understand what is wrong. Describe exactly which UI are you using for rollback (dialog or tool window) and why do you expect that after rollback files should be selected - afaik they disappear from UI


https://user-images.githubusercontent.com/51165317/195332088-de16cfe8-424b-4f19-84ff-904fbc60774c.mp4

**Comment by zielu** [comment]
Can you check if it works as expected with my plugin disabled ?

**Comment by IWareQ** [comment]
> Can you check if it works as expected with my plugin disabled ? So far I cannot reproduce it.

yes, it works

**Comment by zielu** [comment]
I managed to reproduce this and it is buggy too without my plugin installed. Best report this to Jetbrains.
