### ISSUE TITLE
[Feature] Allow to open the PR of a code line

### ISSUE THREAD

**Issue by HaloKo4** [zielu/GitToolBox#383]
Use case:
Currently the plugin shows the PR that created a code line. By clicking Open In -> Github you can open the browser on this code line. I'm interested in functionality where i can also open the PR that created this code line. The PR number is viable it just doesn't allow to open it in a continent way.

**Comment by zielu** [comment]
Hi, that open action is not provided by the plugin but afair it's from IDE Github integration. If you give me an example of such blame message I might suggest some workarounds.
