### ISSUE TITLE
[BUG] Current Branch auto-complete suggestion in commit message dialog does not come up when typing the beginning letters of the current branch name

### ISSUE THREAD

**Issue by cmatos23** [zielu/GitToolBox#384]
**Describe the bug**
"Branch" auto-complete suggestion in commit message dialog does not come up when typing the beginning letters of the current branch name

**To Reproduce**
1. Checkout `main` branch
2. Make a change to a random file.
2. Go to commit dialog and select the file changed above
3. type beginning of current branch name in commit text box. Ex 'mai' while on branch 'main'
4. No auto-complete suggestion comes up

**Expected behavior**
An auto-complete suggestion for current branch 'main' pops up.

**Plugin version**
212.8.5

**IDE version**
IntelliJ IDEA 2021.3.1 (Community Edition)
Build #IC-213.6461.79, built on December 28, 2021
Runtime version: 11.0.13+7-b1751.21 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Non-Bundled Plugins:
    com.intellij.plugin.adernov.powershell (2.0.9)
    com.illuminatedcloud2.intellij (2.2.0.5)
    zielu.gittoolbox (212.8.5)
    izhangzhihao.rainbow.brackets (6.21)

Kotlin: 213-1.5.10-release-949-IJ6461.79

**Screenshots**
![image](https://user-images.githubusercontent.com/28399749/152594753-8091ea84-84c5-4430-b097-b973b7d491b2.png)

The expected result happens when typing other letters of the branch name, but not the beginning letter
![image](https://user-images.githubusercontent.com/28399749/152594791-d90f2250-5fef-4547-8611-9d0e3dc4af8a.png)

**Comment by zielu** [comment]
Hi, indeed I can reproduce it - it is  bizarre - no it

**Comment by zielu** [comment]
Released to EAP channel in variant.8.7

**Comment by zielu** [comment]
Done in variant.8.8
