### ISSUE TITLE
Update Gitmoji: Adhesive_bandage missing

### ISSUE THREAD

**Issue by Clindbergh** [zielu/GitToolBox#386]
The Gitmoji adhesive_bandage 🩹 is missing from the list of suggested gitmojis.

![image](https://user-images.githubusercontent.com/2742027/154040556-2678268c-4c7e-417d-b1ca-cff443c263b5.png)

[gitmoji.dev](gitmoji.dev):
![image](https://user-images.githubusercontent.com/2742027/154040641-a478459b-1a68-4d02-bddf-efeda9c78e6c.png)

**Comment by zielu** [comment]
Hi, I added it to my todo list.

**Comment by zielu** [comment]
Done in (203/212).8.9
