### ISSUE TITLE
if the module is in a group, location path is "null" 

### ISSUE THREAD

**Issue by vaurat** [zielu/GitToolBox#39]
In the "Project" view, if a module is placed in a module group, the location path of every module of the group is "null".
Projects outside of the module group (at the root of the view) have their location path well displayed.

**Comment by zielu** [comment]
Could you provide which version you are using and what is you repository / module / groups layout ?
I'm having problems reproducing.

**Comment by vaurat** [comment]
Yes :+1:  good question : i just upgraded today Idea and GitToolbox and nothing has changed.
let me be more precise :
- idea 2017-1 build 171-3780-107
- GitToolBox 171.1.2
- Git integration 8.1
- Ubuntu 16.04 with Gnome with that set : https://confluence.jetbrains.com/display/IDEADEV/Inotify+Watches+Limit

every modules has its own repository and also its own folder. (one folder by module and thus one repo by module)
You see below that all modules have "null" in the so called "Monolithe" group
but the two modules NOT in the group have their folder path displayed after the branch name.
![selection_267](https://cloud.githubusercontent.com/assets/333869/24246054/d0d82d48-0fc5-11e7-8d84-54ca9d4537f8.png)

Here is the Project Files View with the location paths :
![selection_269](https://cloud.githubusercontent.com/assets/333869/24246535/0e8480e0-0fc8-11e7-8afc-2908618e4cfc.png)

This is why i saw a dependency between having a module in a group and not having its location path displayed. This could be another cause that i do not see.

**Comment by zielu** [comment]
Fixed in 171.1.4
