### ISSUE TITLE
(🐞) auto fetch resets the gitlog selected commit

### ISSUE THREAD

**Issue by KotlinIsland** [zielu/GitToolBox#391]
**Describe the {🐞}**
A clear and concise description of what the (🐞) doin.

auto fetch causes the currently selected commit in the log window to reset to the selected branch from the branch pane.

This also happens if you are looking at a diff which can be extremely frustrating

**To Reproduce**

Select this option:
![image](https://user-images.githubusercontent.com/65446343/157803275-0173b5fc-6e45-4f81-a84c-bffc1d6849a3.png)

1. Go to 'branches pane'
2. Click on 'a branch'
3. Scroll down to 'a different commit'
4. Wait for auto-fetch
5. Selection resets to the selected branch

**Expected behavior**
Nothing at all, the same behavior as a normal fetch.

**Plugin version**
Exact plugin version. 212.8.8

**IDE version**
Exact IDE and OS. You can use About > Copy 
PC 2022.1 (but happens on older versions too)
Windows 10

**Comment by zielu** [comment]
Hi, I'll take a look

**Comment by zielu** [comment]
The same thing happens when invoking build-in fetch action - selection get's scrolled to HEAD commit of branch selected in 'branches pane'. The trigger seems to be any commits are actually fetched from remote.

**Comment by KotlinIsland** [comment]
no it doesn't

**Comment by KotlinIsland** [comment]
https://youtrack.jetbrains.com/issue/IDEA-290571

**Comment by KotlinIsland** [comment]
@zielu I'm sorry my diagnosis was incorrect. Thanks for looking into it!

**Comment by zielu** [comment]
@KotlinIsland no problem at all, take care!
