### ISSUE TITLE
(🎁) Autofetch should not log a notification or at least make it an option

### ISSUE THREAD

**Issue by KotlinIsland** [zielu/GitToolBox#392]
24/7 (yes I code non stop) I have this ![image](https://user-images.githubusercontent.com/65446343/159636746-b64a2190-e5d7-4798-beed-22e09552d2e7.png) blue dot sitting in my notifications window, it doesn't provide any value to inform me that an auto fetch has occured, and dulls my senses to actual notifications that will appear.

I would very much appreciate the option to disable this logging 😁

**Comment by zielu** [comment]
Hi, good idea.

**Comment by zielu** [comment]
(203/212).8.9

Go to Preferences / Appearance & Behavior > Notifications > GitToolbox fetch info. Select `No Popup` and disable `Show in tool window`
