### ISSUE TITLE
[BUG] Merge Target not shown | Behind Tracker

### ISSUE THREAD

**Issue by adam1010** [zielu/GitToolBox#394]
**Describe the bug**
When a branch is behind the merge target (`master` in our case), that information is not displayed. Is it necessary for me to tell gittoolbox what branch is the merge target so that it knows to show that information?

**To Reproduce**

## Storm view
![image](https://user-images.githubusercontent.com/3019544/162040433-3ad2e53b-6e87-47a3-bfbf-253bd2e87920.png)

## Github view
![image](https://user-images.githubusercontent.com/3019544/162040531-83c5189d-2bc1-47f3-aa3f-957b02fb237a.png)

## Storm settings
![image](https://user-images.githubusercontent.com/3019544/162040601-1288a193-6d0f-4bde-baf7-01973645c6f4.png)

**Expected behavior**
Expecting to see Behind Tracker showing the branch is `22 commits behind` 

**Plugin version**
212.8.8

**IDE version**
PhpStorm 2021.3.2

**Comment by zielu** [comment]
Hi, it's parent branch mode which is described here:
- https://github.com/zielu/GitToolBox/wiki/Manual#git-status-display
- https://github.com/zielu/GitToolBox/wiki/Manual#parent-branch-mode

Whether is works on not depends on config and usage. In general git has no notion of PR - it does not track into which branch another one is supposed to be merged.

If someone using IDE `Task management` I can extract that info and as alternative if can be configured.

I might add a feature that assumes parent branch is the one from which current one was created but it's tricky.

**Comment by adam1010** [comment]
That worked great, thank you!  Feel free to close this Issue -- we very much appreciate your hard work on this plugin!

![image](https://user-images.githubusercontent.com/3019544/162879806-f7094a55-9eb1-49b5-89ba-1a6c952b7464.png)
