### ISSUE TITLE
[BUG] New version of IDE

### ISSUE THREAD

**Issue by datpham19** [zielu/GitToolBox#395]
**Describe the bug**
I've updated to PyCharm 2022. I can't enable GitToolBox because it has some errors

**Plugin version**
Exact plugin version: 212.8.9

**IDE version**
PyCharm 2022.1.1 (Professional Edition)
Build #PY-221.5591.52, built on May 11, 2022
Licensed to Dat Pham
Subscription is active until June 6, 2022.
For educational use only.
Runtime version: 11.0.14.1+1-b2043.45 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4000M
Cores: 6

**Screenshots**
![image](https://user-images.githubusercontent.com/27439513/168730070-6af48b4d-28fb-48e1-8f48-31e2467af8ef.png)
![image](https://user-images.githubusercontent.com/27439513/168730119-16c09984-7a2f-4fcd-a7ac-7f6d54009dfa.png)
![image](https://user-images.githubusercontent.com/27439513/168730163-16b6a394-bb8a-443b-92ee-09d3e8bfcc3d.png)
![image](https://user-images.githubusercontent.com/27439513/168730208-0a2de49e-6bc3-4647-93fc-2144a7f20a27.png)

**Comment by zielu** [comment]
Hi, I cannot reproduce this with plugin installed from official repository. How did you install the plugin ?

**Comment by datpham19** [comment]
I searched from Marketplace 
![image](https://user-images.githubusercontent.com/27439513/168955603-c5837360-587b-49ac-8ae1-dbde7022d601.png)

**Comment by datpham19** [comment]
But when I uninstall plugin and re-installed, the plugin worked :/
