### ISSUE TITLE
[Feature] Update Gitmoji - Latest spec

### ISSUE THREAD

**Issue by beanaroo** [zielu/GitToolBox#397]
First of all, thank you so much for this wonderful plugin! It has been invaluable. ❤️ 

---

In addition to https://github.com/zielu/GitToolBox/issues/386, there are a few more entries missing:

Reference: https://github.com/carloscuesta/gitmoji/blob/master/src/data/gitmojis.json

```properties
bricks=Infrastructure related changes
closed_lock_with_key=Adding or updating secrets
coffin=Removing dead code
dizzy=Adding or updating animations / transitions
goal_net=Catching errors
hammer=Adding or updating development scripts
monocle_face=Data exploration / inspection
necktie=Adding or updating business logic
passport_control=Working on authorization, roles and permissions
seedling=Adding or updating seed files
stethoscope=Adding or updating healthcheck
technologist=Improving developer experience
test_tube=Adding a failing test
triangular_flag_on_post=Modifying feature flags
wastebasket=Deprecating code to be cleaned up
```

### Notes:
- [Platform specific emoji](https://github.com/carloscuesta/gitmoji/pull/471/files) have been removed
- [Code Review emoji](https://github.com/carloscuesta/gitmoji/pull/463/files) has been removed
- [Renamed `hankey` emoji](https://github.com/carloscuesta/gitmoji/pull/313/files) for bitbucket compatibility ([`memo` reverted](https://github.com/carloscuesta/gitmoji/pull/563#issuecomment-687852175))
- I was not sure if this repo is still accepting PRs since main development is now private. 
  - I have attached updated `gitmoji.yaml` and `gitmoji.properties` if that is helpful: [gitmoji.zip](https://github.com/zielu/GitToolBox/files/8749184/gitmoji.zip)
  - I was unsure what the [codepoint for `:technologist:` 🧑‍💻](https://emojipedia.org/technologist/) should be.

**Comment by zielu** [comment]
technologist will be an interesting one :)

**Comment by zielu** [comment]
Picking this up - I finally have emoji generator in place.

**Comment by zielu** [comment]
Done in 500.0.3+213
