### ISSUE TITLE
[Feature] How to contribute ?

### ISSUE THREAD

**Issue by DevDengChao** [zielu/GitToolBox#398]
I found it incompatible with IntelliJ IDEA 2022.2 EAP (Ultimate Edition) Build #IU-222.2270.31 these days, so I'd like to known if there is something I can do to help it and how to do it.

I noticed the announcement in readme, does it means no more code contribution will be accepted in the feature ?

**Comment by zielu** [comment]
Hi, you are correct - no more code contributions are accepted. Build with 2022.2 EAP support should be up today.
