### ISSUE TITLE
[BUG] too many processes spawned

### ISSUE THREAD

**Issue by Jidehem** [zielu/GitToolBox#404]
**Describe the bug**
The plugin can spawns to many Git processes, and the number of spawned processes is increasing until CPU limit is reached (~around 1000 processes on my machine)

**To Reproduce**
1. Launch IntelliJ with the GitToolbox enabled
2. Open a complex project with around 10-15 different Git repositories
3. When checking in task manager, the number of tasks progressively increases up to 100% CPU is filled

**Workaround**
Disable the GitToolbox plugin

**Expected behavior**
The number of spawned processes should remain bounded and not exhaust machine's resources.

**Plugin version**
212.9.0

**IDE version**
IntelliJ IDEA 2022.1.2 (Ultimate Edition)
Build #IU-221.5787.30, built on May 31, 2022
Licensed to ELCA Informatique SA / Jean-David Maillefer
Subscription is active until December 5, 2022.
Runtime version: 11.0.15+10-b2043.56 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry:
    debugger.watches.in.variables=false
    ide.tooltip.initialDelay=584
    maven.import.compiler.arguments=false

Non-Bundled Plugins:
    krasa.CpuUsageIndicator (1.14)
    de.netnexus.camelcaseplugin (3.0.12)
    com.khmelyuk.multirun (1.13)
    org.jetbrains.kotlin (221-1.7.0-release-281-IJ5591.52)
    com.intellij.guice (221.5787.20)
    com.dubreuia (2.3.0)
    VisualVMLauncher (1.21.211.6085.0)
    GrepConsole (12.14.211.6693.0)
    org.sonarlint.idea (6.7.0.45926)
    mobi.hsz.idea.gitignore (4.4.0)
    com.intellij.javaee.batch (221.5787.20)
    Karma (221.5787.15)
    com.ppolivka.plugin.gitcleaner (1.1.4)
    com.atlassian.bitbucket.references (2022.1.200)
    FitNesse (1.13.0)
    CMD Support (1.0.5)
    Builder Generator (1.1.8)
    org.mapstruct.intellij (1.3.1)
    org.jfrog.idea (1.16.0)
    com.haulmont.jpab (2022.2.5-221)

Kotlin: 221-1.7.0-release-281-IJ5591.52

Note: the GitToolbox is not listed as I had to disable it in order to access the "About" menu...

**Screenshots**
From Windows Task Manager:
![2022-06-15 16_44_08-Window](https://user-images.githubusercontent.com/647939/174559663-b08f3e33-13ef-4ae2-a1ce-f8778f9e0f46.png)
We can clearly see that the number of spawned processes is above 1000. Most of the commands are "Git for Windows". A lot of other processes are shells which are probably used to control "Git for Windows" (not visible on the screenshot)

**Comment by zielu** [comment]
Hi, could you check some of these processes to see what git command they are running ? With 15 repos I would not expect to see more than 50 but only when opening the project.

**Comment by Jidehem** [comment]
I've re-enabled the plugin and IntelliJ's sub-processes are always following the same tree structure
![image](https://user-images.githubusercontent.com/647939/174634616-89879021-b07e-4b5b-8477-cb23b28aa3e9.png)

Using Process Explorer to get more infos, it appears that
- "C:\Program Files\JetBrains\IntelliJ IDEA 2018.2.5\bin\runnerw.exe" "C:\Program Files\Git\cmd\git.exe" -c credential.helper= -c core.quotepath=false -c log.showSignature=false tag -l --points-at 0604b96e103ed04ee913f43bf223c06f7feace39
-- \??\C:\WINDOWS\system32\conhost.exe 0x4
-- "C:\Program Files\Git\cmd\git.exe" -c credential.helper= -c core.quotepath=false -c log.showSignature=false tag -l --points-at 0604b96e103ed04ee913f43bf223c06f7feace39
--- git.exe -c credential.helper= -c core.quotepath=false -c log.showSignature=false tag -l --points-at 0604b96e103ed04ee913f43bf223c06f7feace39

**Comment by Jidehem** [comment]
The issue seems to be fixed after updating to 212.9.5.

**Comment by zielu** [comment]
Done in (211/212).9.6
