### ISSUE TITLE
[BUG] "Push Tags On Branch" lacks sorter

### ISSUE THREAD

**Issue by paoloscr** [zielu/GitToolBox#408]
Hi, unfortunately since the last Intellij Idea Ultimate 2022.1.3,
"Push Tags On Branch" form does not sort tags anymore.
They are in sparse order, but they should be in local creation time order.
Anytime I have to push the last tags I have to search across hundreds of labels.

**Plugin version**
219.9.6

**IDE version**
2022.1.3 | IU-221.5921.22, built on June 21, 2022

**Comment by zielu** [comment]
Hi, I'll take a look as soon as I can.

**Comment by zielu** [comment]
Found it - collection type has changed hence mess with tag ordering. On it.
