### ISSUE TITLE
[Question] Disable "Auto fetch finished" message?

### ISSUE THREAD

**Issue by mu88** [zielu/GitToolBox#410]
Hey 👋🏻

Is it possible to disable the "Auto fetch finished" message?
![image](https://user-images.githubusercontent.com/4560672/183352063-da3e352a-4597-4608-a75c-10cae4fe3630.png)

I don't want to get notified each and every time that it worked 🙂

Thx!

**Comment by zielu** [comment]
Hi, it is possible, I'll add relevant section to manual and post link here.

**Comment by zielu** [comment]
Hi, https://github.com/zielu/GitToolBox/wiki/Manual#notifications should help to get you going :)

**Comment by mu88** [comment]
Thank you :)
