### ISSUE TITLE
[BUG] Git blame Affected Files is not working

### ISSUE THREAD

**Issue by thongtrinhbsm** [zielu/GitToolBox#411]
**Describe the bug**
Git blame Affected Files is not working

**To Reproduce**
1. Click in line blame to open Blame modal
2. Click on the 'Affected Files' link in Blame modal
3. Nothing happens

**Expected behavior**
A list of affected files should be displayed

**Plugin version**
212.9.7

**IDE version**
Windows 10 Pro 19044.1889
PhpStorm 2022.2
Build #PS-222.3345.135, built on July 29, 2022

**Screenshots**
![image](https://user-images.githubusercontent.com/103472551/184589589-aa419d8f-c36b-44f9-80a7-9b699e3e8596.png)

**Comment by zielu** [comment]
Hi, it is indeed broken - on it.

**Comment by zielu** [comment]
Done in (211/212).9.8

**Comment by thongtrinhbsm** [comment]
> Done in (211/212).9.8

thanks @zielu

**Comment by allhailwesttexas** [comment]
Thanks for fixing @zielu - this has been killing me recently!
