### ISSUE TITLE
[Bug] Set Color Scheme font style for inline blame not working

### ISSUE THREAD

**Issue by kyle1an** [zielu/GitToolBox#412]
**Describe the bug**
Set Color Scheme for inline blame not working

**To Reproduce**
1. Go to Webstorm Setting > Editor > Color Scheme > GitToolBox Colors
2. Click on italic to set Editor inline blame to italic
3. Back to Editor, font still regular not italic

**Expected behavior**
Set Editor inline blame to italic, font style of inline blame will be italic

**Plugin version**
212.9.8

**IDE version**
WebStorm 2022.2
Build #WS-222.3345.108, built on July 23, 2022

Runtime version: 17.0.3+7-b469.32 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.6
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true

Non-Bundled Plugins:
    quokka.js (1.0.356)
    lermitage.intellij.extratci (1.23.0.201)
    com.nasller.CodeGlancePro (1.4.8)
    org.intellij.plugins.postcss (222.3345.108)
    com.github.copilot (1.1.29.1869)
    String Manipulation (9.5.1)
    Statistic (4.1.10)
    zielu.gittoolbox (212.9.8)
    mobi.hsz.idea.gitignore (4.4.2)
    ru.adelf.idea.dotenv (2022.2)
    BrowseWordAtCaret (3.0.5)

**Screenshots**
<img width="972" alt="Screen Shot 2022-08-16 at 5 18 51 PM" src="https://user-images.githubusercontent.com/50689806/184845945-ce160eab-6b88-4487-aab9-1d706710233e.png">
<img width="539" alt="Screen Shot 2022-08-16 at 5 18 33 PM" src="https://user-images.githubusercontent.com/50689806/184845971-d8b3f234-84d7-46a7-be34-0906ce259b18.png">

**Comment by zielu** [comment]
Hi, I'll take a look.

**Comment by zielu** [comment]
Done in (211/212).9.9
