### ISSUE TITLE
[Feature] Support GitLab SSO

### ISSUE THREAD

**Issue by artfiedler** [zielu/GitToolBox#413]
We switch from gitlab on prem to gitlab cloud recently at the company and now after that was setup I can no longer use this plugin. It seems this plugin does not support gitlab.com SSO login, the regular gitlab.com login page options do not work for company sso we have to goto a specific gitlab.com url to trigger company sso. 

If there is a way to do this currently I can't find the configuration option, otherwise it just repeatedly pops up the login popup every minute or so

**Comment by zielu** [comment]
This must be shortcoming of IDE Git Integration - I do not do any auth directly - just use APIs provided by the platform

**Comment by zielu** [comment]
@artfiedler could you try checking what happens when regular fetch action is used ? Please follow https://github.com/zielu/GitToolBox/wiki/Manual#login-popup-is-shown-every-few-minutes

**Comment by artfiedler** [comment]
Finally figured this out, for whatever reason, I had to go into gitlab.com generate a new personal access token with read_repository & write_repository, then go into "manage windows credentials" add a new "windows credentials" > "generic credentials" use "git:https://gitlab.com" as the internet or network address, my sso username, and then use the generated personal access token as the password

**Comment by zielu** [comment]
Good that is works now
