### ISSUE TITLE
[BUG] Git Toolbox caused commit button unresponsive

### ISSUE THREAD

**Issue by auto-generated** [zielu/GitToolBox#414]
**Describe the bug**

see `https://youtrack.jetbrains.com/issue/IDEA-302552/Git-Toolbox-caused-commit-button-unresponsive`

**Plugin version**
212.9.9

**IDE version**
IntelliJ IDEA 2022.3 EAP (Ultimate Edition)
Build #IU-223.4884.69, built on September 22, 2022

**Comment by zielu** [comment]
Version 212.9.9 never supported 223 platform (https://plugins.jetbrains.com/plugin/7499-gittoolbox/versions/stable/213357).  This is user modifying plugin.xml manually.
