### ISSUE TITLE
[Feature] Support 2022.3 EAP

### ISSUE THREAD

**Issue by zielu** [zielu/GitToolBox#415]
212.9.12 is out in plugin EAP channel. How to switch to EAP: https://github.com/zielu/GitToolBox#eap-builds

**Comment by zielu** [comment]
212.9.11 is out in plugin EAP channel. How to switch to EAP: https://github.com/zielu/GitToolBox#eap-builds

**Comment by zielu** [comment]
There is a know issue with excessive scrollbars visible in plugin configuration UI on 2022.3 - under investigation

**Comment by zielu** [comment]
On 223.6160.11 it is possible to encounter following exception during commit validation:
`java.lang.Throwable: java.lang.AbstractMethodError: Receiver class m223.b does not define or inherit an implementation of the resolved method 'abstract java.lang.Object runCheck(com.intellij.openapi.vcs.checkin.CommitInfo, kotlin.coroutines.Continuation)' of interface com.intellij.openapi.vcs.checkin.CommitCheck.`

Fix is on the way

**Comment by nvdweem** [comment]
Is there some functionality that we can turn off to prevent the 

> Checks failed: Couldn't check commit: Receiver class m223.b does not define or inherit an implementation of the resolved method 'abstract java.lang.Object runCheck(com.intellij.openapi.vcs.checkin.CommitInfo, kotlin.coroutines.Continuation)' of interface com.intellij.openapi.vcs.checkin.CommitCheck.

error? 

I'm on the latest EAP and I added the EAP plugin channel because I'm absolutely dependant on the auto-fetch feature but not being able to commit kinda breaks my workflow :)

**Comment by zielu** [comment]
@nvdweem I plan to release the feature today

**Comment by zielu** [comment]
Done in 212.10.0
