### ISSUE TITLE
Inline blame has color same as last character on the line

### ISSUE THREAD

**Issue by stribor** [zielu/GitToolBox#416]
**Describe the bug**
inline blame has the same color as the last character of the line

**To Reproduce**
open document 
click on any line
git blame will be displayed in color of last character on the line

**Expected behavior**
always have same color of inline comments

**Plugin version**
Exact plugin version. 212.9.11 EAP Release (2022-09-29T07:50:08.675553)

**IDE version**
CLion 2022.3 EAP
Build #CL-223.4884.72, built on September 22, 2022

**Screenshots**

**Comment by zielu** [comment]
Hi, can you paste setting from `Preferences > Editor > Color Scheme > GitToolBox Colors` ?

**Comment by zielu** [comment]
Please try 212.9.12. It was possible from inline blame to "inherit" color in case when none was configured in Color Scheme. Now in such case editor text color will be used as fallback.

**Comment by stribor** [comment]
Sorry for late reply, I had nothing selected in GitToolBox Colors, all good now, thanks for great plugin!

**Comment by LinWanCen** [comment]
Hello, I also encountered this issue while developing plugins. May I ask for your advice on how to solve it?

I have asked this question on the official platform before:
[https://youtrack.jetbrains.com/issue/IDEA-300093](https://youtrack.jetbrains.com/issue/IDEA-300093)

My Plugin: [Show Comment](https://plugins.jetbrains.com/plugin/18553-show-comment)

Thanks.

**Comment by zielu** [comment]
Hi @LinWanCen, you might find this useful https://plugins.jetbrains.com/docs/intellij/inlay-hints.html.
At the point this issue was solved I was already using inlays but with the most low-level API possible `com.intellij.openapi.editor.InlayModel` - which is actually quite a chore to implement.

**Comment by LinWanCen** [comment]
Thank you very much. Based on your reply, I have found some relevant content and know how to solve it.

https://github.com/zielu/GitToolBox/issues/268
