### ISSUE TITLE
[BUG] AppCode  I can't see every line of git info anymore

### ISSUE THREAD

**Issue by baiyidjp** [zielu/GitToolBox#419]
**Describe the bug**
I can't see every line of git info anymore

**To Reproduce**

**Expected behavior**
I can see every line of git info anymore

**Plugin version**
Exact plugin version. Eg. 212.8.4

**IDE version**
AppCode 2022.2.2

**Screenshots**
<img width="1402" alt="iShot2022-10-13 13 46 48" src="https://user-images.githubusercontent.com/12672573/195512078-6fb1211f-e7d4-4bcc-bf5d-07d828aa2297.png">

**Comment by baiyidjp** [comment]
<img width="570" alt="iShot2022-10-13 13 48 16" src="https://user-images.githubusercontent.com/12672573/195512464-af7292fd-f4d6-4204-9f3e-3d5751a46c55.png">

I can see when my commit is not committed

**Comment by zielu** [comment]
Hi, latest plugin version is 212.9.9 - could you try it ?

**Comment by baiyidjp** [comment]
> Hi, latest plugin version is 212.9.9 - could you try it ? If you are on latest and it still does not work can you run following in CLI and share the result ? `git blame --incremental -l -t -w --encoding=UTF-8 <repository root relative path to your file>`

First of all, thank you for your reply, my version is 212.9.9, then I uninstalled and reinstalled and it can be displayed normally
