### ISSUE TITLE
[BUG] Inline comment is too bright with EAP in dark mode.

### ISSUE THREAD

**Issue by RoyRao2333** [zielu/GitToolBox#422]
**Describe the bug**
After upgrading to EAP version of GitToolBox, the inline comment seems as bright as the normal code text. This makes it hard to distinguish between codes and git comment.

**Screenshots**
<img width="654" alt="image" src="https://user-images.githubusercontent.com/31413093/199211374-ca036704-fd52-4f55-aff2-26e9182b6ff3.png">

**Comment by zielu** [comment]
Hi, I see what is wrong - fix is on the way.

**Comment by RoyRao2333** [comment]
> Hi, I found were I broke it - fix is on the way.

By the way, if the stable version has released, should I remove the EAP plugin repository to receive stable updates?

**Comment by zielu** [comment]
You can keep EAP - I push all stable releases there too.

**Comment by RoyRao2333** [comment]
> Done in 212.10.0

Yes, it's fixed! Great work 🎉
