### ISSUE TITLE
[BUG] Inline Comment dislocation

### ISSUE THREAD

**Issue by shilohooo** [zielu/GitToolBox#425]
**Describe the bug**
Inline Comment dislocation.

**To Reproduce**
1. Open a git project  via IntelliJ IDEA.
2. Open a file.
3. See the inline comment.

**Expected behavior**
Inline comment are not misplaced.

**Plugin version**
212.10.1.

**IDE version**
IntelliJ IDEA 2022.2.3 (Ultimate Edition)
Build #IU-222.4345.14, built on October 5, 2022
Subscription is active until December 30, 2022.
Runtime version: 17.0.4.1+7-b469.62 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 3072M
Cores: 8
Non-Bundled Plugins:
    one.util.ideaplugin.screenshoter (1.8)
    de.netnexus.camelcaseplugin (3.0.12)
    org.jetbrains.kotlin (222-1.7.21-release-272-IJ4167.29)
    com.alibaba.p3c.smartfox (2.1.1)
    zielu.gittoolbox (212.10.1)
    MavenRunHelper (4.23.222.2964.0)
    cn.yiiguxing.plugin.translate (3.3.5)

Kotlin: 222-1.7.21-release-272-IJ4167.29

**Screenshots**
![image](https://user-images.githubusercontent.com/46670399/202068805-bf41d89a-e71f-484f-8f1e-a94da08541da.png).

**Comment by zielu** [comment]
Hi, I'll take a look - I did not test english and chinese combo.

**Comment by shilohooo** [comment]
Thanks

**Comment by zielu** [comment]
@shilohooo could you share your setting from here?
<img width="632" alt="image" src="https://user-images.githubusercontent.com/464103/203150397-e48d72f5-4000-4b1c-968b-4e2b40921e62.png">

And maybe some test for which this is happening.

**Comment by shilohooo** [comment]
@zielu 
![image](https://user-images.githubusercontent.com/46670399/203212602-da1cd3c3-e45f-40a6-9a0d-db9f6e7a67b2.png)

**Comment by StevenCai1996** [comment]
Same issue with chinese and english composed comment,previous version works fine.

**Comment by zielu** [comment]
@StevenCai1996 can you provide some sample and same settings page as original reporter? I tried to reproduce it but no luck so far.

**Comment by StevenCai1996** [comment]
@zielu 
![gittoolboxRP2](https://user-images.githubusercontent.com/55140081/204731872-83afd289-ad34-4867-a6eb-1fb3d567d93f.PNG)
![gittoolboxRP1](https://user-images.githubusercontent.com/55140081/204731878-7c806e30-f051-414f-88d8-21cc687e0309.PNG)

`https://github.com/StevenCai1996/gittoolbox213102Report.git`
You can pull this sample project to see inline blame.
212.8.8 [O]
213.10.2 [X]

**Comment by zielu** [comment]
@StevenCai1996 your are on Windows by any chance ?

**Comment by StevenCai1996** [comment]
> @StevenCai1996 your are on Windows by any chance ?

Yes,Win 10 pro 64bit

**Comment by shilohooo** [comment]
After upgrading WebStorm to 2022.3 and GitToolBox to 213.10.2,  the plug-in works fine.

The screeshot:
![image](https://user-images.githubusercontent.com/46670399/204747710-a065d5b1-90e8-4877-9031-eb59f3f4306b.png)

and setting:
![image](https://user-images.githubusercontent.com/46670399/204747838-98eeb459-d270-41ec-bd2c-ccd164c0cb27.png)

**Comment by shilohooo** [comment]
The inline blame in  IntelliJ IDEA v2022.2.4:
![image](https://user-images.githubusercontent.com/46670399/204748915-c3c72395-7adc-436b-9ddc-ca7f368b280c.png)
and my setting:
![image](https://user-images.githubusercontent.com/46670399/204749066-db55de66-1c09-4d0d-a97a-f3ad30f9947a.png)

Plug-in version is 213.10.2

**Comment by shilohooo** [comment]
Hope it can help you to reproduce the problem:)

**Comment by zielu** [comment]
2022.2 and Windows is the way to reproduce this - I found there is indeed difference in aligning text between plugin 212.8.8 and more recent code. Some Y coordinate adjustment were lost along the way...

**Comment by zielu** [comment]
Looks like old code is the best code :)

**Comment by shilohooo** [comment]
Can't agree more.

**Comment by zielu** [comment]
Done in 213.10.3
