### ISSUE TITLE
[BUG] Auto-fetch error (git executable issue)

### ISSUE THREAD

**Issue by hassanrazmy** [zielu/GitToolBox#433]
**Describe the bug**
Whenever I turn this plugin on in my PHPStorm, it gives me the error visible in the screenshot given below.

**Plugin version**
213.10.2

**IDE version**
PHP Storm 2021.2.1

**Screenshot**
https://www.screencast.com/t/ZO9rO5Mjb3

**Comment by zielu** [comment]
Hi, looks like issue with your Git configuration. First try running this action: 'Git / Fetch' it should also fail.
If so look into `Settings / Version Contol / Git` and verify if executable actually exists.

**Comment by zielu** [comment]
But it looks like git error handling needs some improvement too.

**Comment by hassanrazmy** [comment]
Basically, I am using Tower App for the git related tasks. The plugin was mainly used to see who worked on any specific line which was very helpful. Now, it is not working at all on my end.

**Comment by zielu** [comment]
The issue with with you local config - I mean you can disable autofetch but you still need working git executable to invoke blame

**Comment by zielu** [comment]
Just try the steps I posted earlier

**Comment by hassanrazmy** [comment]
The Git executable doesn't exist. It asked me to install the command line tool I am doing now. It doesn't consider. I will share the progress shortly.

**Comment by hassanrazmy** [comment]
After the download, it works fine. Problem was on my end.

Thank you for the guidance mate :)
