### ISSUE TITLE
[BUG] Issue key reference complains about finding the same reference it expects

### ISSUE THREAD

**Issue by mastacheata** [zielu/GitToolBox#434]
**Describe the bug**
When referencing an issue in the branch name and commit message, with `#`-prefix the plugin will always complain about issue key mismatch, but then list the very same issue in expected and found.

**To Reproduce**
1. Create a branch i.e.: feature/#1234-some-title
2. Commit to that branch with a commit message that includes #1234 in the message

**Expected behavior**
No error

**Actual behavior**
The plugin complains about an issue key mismatch, but in the details it shows that it actually found the same issues in the message and branch name.

**Plugin version**
213.10.2

**IDE version**
PyCharm 2022.3 (Professional Edition)
Build #PY-223.7571.203, built on November 30, 2022
Windows 11 22H2

**Screenshots**
![issue key mismatch](https://user-images.githubusercontent.com/716261/206231970-9045655b-7970-40b3-851c-b1f7ca6f3cee.png)

**Comment by zielu** [comment]
@mastacheata did you have issue key mentioned 2 times in message by any chance ? From code it looks like this is a possible scenario.

**Comment by derula** [comment]
I think the main problem here isn't that the issue name appears in "message references" twice, but that it complains _even if you reference the correct issue_. I still experience that problem in 213.10.14:

![image](https://user-images.githubusercontent.com/601781/208635711-098b6278-ec5c-4223-a1cb-a72c5f855b10.png)

(And yes, the CIA'd project keys are the same)

This means that the message will pop up on _every single commit_, no matter if you reference the correct or incorrect issue key.

@zielu could you have a look at this again, please?

**Comment by zielu** [comment]
@derula sure, back on it :)

**Comment by zielu** [comment]
Ok, I think I know what is wrong - issue key text offsets are compared too and it does not make sense. You can have key at start of branch name and at the end of message for example :/

**Comment by derula** [comment]
For reference, my branch name looks like this: `feature/ABC-123` and my commit message: `ABC-123 Did something amazing.`
It used to work fine with this exact setup (I suppose I may have had to configure the branch naming scheme?) and stopped working a few versions back without me changing anything. (I was too lazy to report then...)

**Comment by zielu** [comment]
I was changing how key matches are represented (adding offsets) in code to support another feature, I believe I broke it around that time.

**Comment by zielu** [comment]
Done in 213.10.5
