### ISSUE TITLE
[BUG] Change Local Branch Name

### ISSUE THREAD

**Issue by ariexx** [zielu/GitToolBox#439]
**Describe the bug**
I wanna change my local branch name to another name and pop up showed up from phpstorm

**To Reproduce**
1. Press Ctrl+Shift+G
2. Click on your local branch and change the name
3. See error

**Expected behavior**
I expected no see any error when change my local branch name.

**Plugin version**
213.10.3

**IDE version**
PhpStorm 2022.3
Build #PS-223.7571.212, built on December 1, 2022
Licensed to Muhammad Arief
Subscription is active until May 29, 2023.
For educational use only.
Runtime version: 17.0.5+1-b653.14 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 6.0.6-76060006-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 1460M
Cores: 4
Registry:
    editor.focus.mode.color.light=777777
    ide.editor.tab.selection.animation=true
    run.processes.with.pty=TRUE
    editor.distraction.free.mode=true
    ide.new.editor.tabs.vertical.borders=true
    ide.balloon.shadow.size=0
    editor.focus.mode.color.dark=777777

Non-Bundled Plugins:
    com.vermouthx.xcode-theme (1.6.1)
    com.fernandojimenez.mattecarbon.theme (3.0.0)
    com.github.copilot (1.1.37.2188)
    com.intellij.ideolog (203.0.30.0)
    net.antelle.intellij-xcode-dark-theme (1.2.4)
    izhangzhihao.rainbow.brackets (2022.3.5)
    ru.adelf.idea.dotenv (2022.3)
    nl.deschepers.laraveltinker (2.5.1)
    de.espend.idea.php.annotation (8.3.0)
    com.laravel_idea.plugin (6.2.2.223)
    dev.ekvedaras.laravelquery (4.0.0)
    com.mallowigi (80.0.0)
    zielu.gittoolbox (213.10.3)

Current Desktop: pop:GNOME

**Screenshots**
![image](https://user-images.githubusercontent.com/30616892/208263343-71cc558e-080e-4390-9df2-a648dcd31bfb.png)

**Comment by zielu** [comment]
Hi, indeed there is potential for NullPointer

**Comment by zielu** [comment]
Done in 213.10.4
