### ISSUE TITLE
[BUG] copied github repository url is incorrect when multiple git remotes in repo

### ISSUE THREAD

**Issue by gberche-orange** [zielu/GitToolBox#443]
**Describe the bug**

thanks again for the great plugin. disclaimer, I'm not sure this feature is brought by GitToolBox or GitLink, did not find related documentation in either plugin, but the feature is'nt available on a repo with gitlab remotes, so I assumed it is related to GitToolBox 

Given a git repo with multiple remotes
```
$ (main) git remote -v
gberche-orange  https://github.com/gberche-orange/kuttl.git (fetch)
gberche-orange  https://github.com/gberche-orange/kuttl.git (push)
orange  https://github.com/orange-cloudfoundry/kuttl.git (fetch)
orange  https://github.com/orange-cloudfoundry/kuttl.git (push)
origin  https://github.com/kudobuilder/kuttl.git (fetch)
origin  https://github.com/kudobuilder/kuttl.git (push)
```
When copying the github repository url
Then the copied url is invalid and contains all remote urls:
`https://github.com/kudobuilder/kuttl/blob/f6d64c915c8dd9e2da354562c3d5c6fcf88aec2b/crds/testassert-json-schema.yaml
https://github.com/orange-cloudfoundry/kuttl/blob/f6d64c915c8dd9e2da354562c3d5c6fcf88aec2b/crds/testassert-json-schema.yaml
https://github.com/gberche-orange/kuttl/blob/f6d64c915c8dd9e2da354562c3d5c6fcf88aec2b/crds/testassert-json-schema.yaml`

**To Reproduce**
![image](https://user-images.githubusercontent.com/4748380/213159891-b3ae26bd-6746-442f-b88e-430bf5778ce3.png)
![image](https://user-images.githubusercontent.com/4748380/213159899-1f21d1db-bcad-4dee-b58e-aeb91226d5a3.png)

**Expected behavior**

Either
* the current upstream remote associated with the current git branch is selected (preferred)
* the UI asks to select the remote to copy the url from
* the settings offer a way to select the preferred remote

**Plugin version**
Exact plugin version. 213.10.5

**IDE version**
Exact IDE and OS. You can use About > Copy 
IntelliJ IDEA 2022.3.1
Build #IU-223.8214.52, built on December 20, 2022

Ubuntu 20.02

**Comment by zielu** [comment]
Hi, this must be from IDE Github plugin - I will have similar feature but it' still in implementation. Looks like area my plugin could do better than built-in one.

**Comment by gberche-orange** [comment]
thanks @zielu ! 
I've reported that to jet brains in https://youtrack.jetbrains.com/issue/IDEA-310943/copied-github-repository-url-is-incorrect-when-multiple-git-remotes-in-repo
