### ISSUE TITLE
[Feature] Disable GitToolBox for specific project

### ISSUE THREAD

**Issue by filipstojakovic** [zielu/GitToolBox#444]
It would be nice to be able to disable GitToolBox for specific projects while leaving it enabled for others.

**Comment by zielu** [comment]
Hi, there are 2 levels of configuration:
-  global - called "GitToolBox"
-  per-project - called "GitToolBox Project". 

Global level applies to all projects and most features can be overridden (and disabled) on project level.

I need to add this to manual btw :)

**Comment by filipstojakovic** [comment]
Yes, the manual would help for sure. I can't find a way to disable "code author" for the specific project.

**Comment by zielu** [comment]
@filipstojakovic so basically inline blame ?

**Comment by zielu** [comment]
Ah, that one does not have override per-project but I'll add one.

**Comment by zielu** [comment]
Done in 500.0.7
