### ISSUE TITLE
[Feature] Offer to open a "Create Pull Request" link returned by git server on push

### ISSUE THREAD

**Issue by mslalith** [zielu/GitToolBox#446]
Show a balloon to create PR on successful push. Relates to [IDEA-195111](https://youtrack.jetbrains.com/issue/IDEA-195111)

**Comment by zielu** [comment]
I was considering it :)

**Comment by zielu** [comment]
It cannot use Console links because until Console view is opened text is cached and there is not access to it, but I found how to do it another way.

**Comment by zielu** [comment]
Done in 500.1.0+222
