### ISSUE TITLE
[BUG] GitToolBox doesn't respect git local config `blame.ignoreRevsFile` option

### ISSUE THREAD

**Issue by retyui** [zielu/GitToolBox#448]
**Describe the bug**

I tried the next article approach  https://michaelheap.com/git-ignore-rev/

**To Reproduce**
1. Go to root repo
2. Create file `.git-blame-ignore-revs`
3. Add commits that should ignored to file abve
4. Run `git config blame.ignoreRevsFile .git-blame-ignore-revs`
5. Open IDE 7 reset cache
6. IMPORTANT  IDE should be use non root folder:

```tsx
├── be
│   └── ruby_code
├── fe // <-- open IDE project in this folder
│   ├── node_modules
│   ├── package.json
│   └── yarn.lock
├── .git
│   └── config
└── .git-blame-ignore-revs
```

**Expected behavior**

Inline blame should exclude that commit (as `git blame`  do)

**Plugin version**

`213.10.5`

**IDE version**

```
WebStorm 2022.3
Build #WS-223.7571.168, built on November 28, 2022
Licensed to Mur Amur
Subscription is active until November 14, 2023.
Runtime version: 17.0.5+1-b653.14 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.4.0-60-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 1978M
Cores: 12
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true

Non-Bundled Plugins:
    com.github.copilot (1.2.0.2322)
    izhangzhihao.rainbow.brackets (2023.1.1)

Current Desktop: X-Cinnamon
```

**Screenshots**

`git blame`

![image](https://user-images.githubusercontent.com/4661784/214833383-dd1c5607-63da-4cd7-80f0-7426ee691e8c.png)

`IDE`

Prettier commit has to be disregarded.

![image](https://user-images.githubusercontent.com/4661784/214833569-5d4f3eb0-0028-483e-8a41-8c9c9aa5f7d5.png)

**Comment by zielu** [comment]
This must have broker when persistent blame cache was introduced, previously it was enough to restart.
Reseting cache did not help because #337 is not implemented.

I'll add proper cache clearing first as a workaround and next full support for ignoreRevs

**Comment by zielu** [comment]
Cache invalidation ready: https://github.com/zielu/GitToolBox/wiki/Manual#cache-invalidation

**Comment by zielu** [comment]
#453 tracks proper support implementation

**Comment by retyui** [comment]
thanks

**Comment by eXpl0it3r** [comment]
> Manual cache invalidation ready: https://github.com/zielu/GitToolBox/wiki/Manual#cache-invalidation

Can't seem to find this page on the new website.

Should this work with the "Refresh Blame" option?
![image](https://github.com/user-attachments/assets/04e4a4a9-b446-4aba-92fb-044eebb871fe)

**Comment by zielu** [comment]
Hi, it's under https://www.gittoolbox.com/docs/troubleshooting/

**Comment by eXpl0it3r** [comment]
Ah okay, thank you!

I'd have expected a cache refresh that didn't require a restart of the IDE

**Comment by zielu** [comment]
I'll revisit that part, so soon there will be no manual steps needed.
