### ISSUE TITLE
[BUG] no way to purchase license

### ISSUE THREAD

**Issue by WilfulTravesty** [zielu/GitToolBox#452]
**Describe the bug**
In MacOS Android Studio Electric Eel 2022.1.1 patch 1, GitToolBox plugin version 500.0.1+213 includes "Pro" features in the plugin's configuration menu, and the Plugins menu itself shows the plugin as Freemium with "No license". The plugin configuration menu shows "License Type: Basic" under its About menu.

Attempts to go to Android Studio's Help>Register Plugins>GitToolBox>Buy License goes to page https://plugins.jetbrains.com/plugin/7499-gittoolbox/pricing which just says "Oh no, something went wrong!
We’re sorry this happened. It’s probably either a hiccup, or we’re working on it already."

**To Reproduce**
1. Install GitToolBox in Android Studio Electric Eel 2022.1.1 patch 1
2. In Android Studio go to Help>Register Plugins
3. Select GitToolBox
4. Select Activate GitToolBox
5. Select Get license from "JB Account"
6. Click on Buy License in the upper right

Expected: Be taken to a page to buy a license
Actual: End up at an error page "Oh no, something went wrong!"

**Expected behavior**
Be taken to a web page to buy a license.

**Plugin version**
500.0.1+213

**IDE version**
Android Studio Electric Eel | 2022.1.1 Patch 1
Build #AI-221.6008.13.2211.9514443, built on January 20, 2023
Runtime version: 11.0.15+0-b2043.56-8887301 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.1
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 12
Registry:
    external.system.auto.import.disabled=true
    ide.text.editor.with.preview.show.floating.toolbar=false

Non-Bundled Plugins:
    training (221.6008.16)
    tanvd.grazi (221.6008.14)
    org.roana0229.android-xml-sorter (1.1.1)
    com.intellij.marketplace (221.6008.18)
    com.jetbrains.codeWithMe (221.6008.13.5)
    String Manipulation (9.5.0)
    zielu.gittoolbox (500.0.1+213)
    izhangzhihao.rainbow.brackets (2023.1.1-ij)
    Batch Scripts Support (1.0.13)

**Screenshots**
![gittoolbox-license-error](https://user-images.githubusercontent.com/6433968/216477533-2ff1e303-41bd-42ce-991a-7ef8d8dd90ad.png)

**Comment by zielu** [comment]
Hi, waiting for JB approvals for sales to go live.

**Comment by zielu** [comment]
Sales are up
