### ISSUE TITLE
[BUG] No clickable link in inline blame for paid version

### ISSUE THREAD

**Issue by vineus** [zielu/GitToolBox#457]
**Describe the bug**

I don't see clickable links with the PRO version (mentioned here: https://github.com/zielu/GitToolBox/wiki/Manual#git-blame-display-paid)

![image](https://user-images.githubusercontent.com/467126/218707977-c6aa9127-8b83-4a25-91c7-c48350bc600e.png)
![image](https://user-images.githubusercontent.com/467126/218708017-99fc2e98-672f-45d2-865e-1b36051fd9f4.png)

I've tried restarting PyCharm

**To Reproduce**
1. Go to any line with an inline blame containing a github PR number
2.  observe the inline blame
3. See error (no link)

**Expected behavior**
issue id like `#33236` is clickable in the inline blame line

**Plugin version**
500.0.2+213

**IDE version**
PyCharm 2022.3.2 (Professional Edition)
Build #PY-223.8617.48, built on January 24, 2023
Licensed to Alan / Vincent de Lagabbe
You have a perpetual fallback license for this version.
Subscription is active until December 2, 2023.
Runtime version: 17.0.5+1-b653.25 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.1
GC: G1 Young Generation, G1 Old Generation
Memory: 3072M
Cores: 8
Metal Rendering is ON
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true

Non-Bundled Plugins:
    socrates.tabshifter (0.33)
    some.awesome (1.14)
    dev.mayankmkh.intellij.linear (1.1.0)
    awesome.console (0.1337.12)
    org.intellij.plugins.hcl (223.8214.6)
    com.github.copilot (1.2.3.2385)
    org.turbanov.run.configuration.as.action (1.4.5)
    com.khmelyuk.multirun (1.13)
    com.intellij.ideolog (203.0.30.0)
    name.kropp.intellij.makefile (223.8214.6)
    Statistic (4.2.6)
    String Manipulation (9.6.1)
    GrepConsole (12.15.211.6693.1)
    ski.chrzanow.foldableprojectview (1.1.4)
    com.ivanovych666.intellij.plugin.jsonsorter (1.0.0-beta.3.4)
    net.seesharpsoft.intellij.plugins.csv (3.0.3-223)
    org.intellij.prisma (223.8617.8)
    izhangzhihao.rainbow.brackets (2023.1.3)
    com.dropbox.plugins.mypy_plugin (0.3.2)
    ru.adelf.idea.dotenv (2022.3)
    Git Scope (3.0.6)
    zielu.gittoolbox (500.0.2+213)
    mobi.hsz.idea.gitignore (4.4.4)
    aws.toolkit (1.60-223)

**Screenshots**

![image](https://user-images.githubusercontent.com/467126/218707977-c6aa9127-8b83-4a25-91c7-c48350bc600e.png)
![image](https://user-images.githubusercontent.com/467126/218708017-99fc2e98-672f-45d2-865e-1b36051fd9f4.png)

I have other PRO featured enabled:

![image](https://user-images.githubusercontent.com/467126/218708123-9495a813-a315-4551-b3b7-f226bd183654.png)

**Comment by zielu** [comment]
Hi, two things that might lead to this:
- Issue Navigation needs to be configured
- there might be an issue right after license is activated - this is limitation of IDE license check, but as a workaround you can open `Settings > Version Control > GitToolBox > About` if it says Professional, license should be refreshed

**Comment by vineus** [comment]
> Issue Navigation needs to be configured (Settings > Version Control > Issue Navigation)

OK got it! I thought you where using the auto-detected by GitToolbox repo for this

After configuring a pattern it works!

You might want to specify this in the doc?

Thanks a lot for your help!

**Comment by zielu** [comment]
@vineus good point - docs need updating that same setup as for freemium is needed.

**Comment by vineus** [comment]
yes I missed this part 😅 : https://github.com/zielu/GitToolBox/wiki/Manual#issue-navigation-integration
