### ISSUE TITLE
[Feature] Premium version for Students

### ISSUE THREAD

**Issue by tintinmaster** [zielu/GitToolBox#459]
I would really like it, if you would offer the premium version for free or at a discount for students with a JetBrains Students Account

**Comment by zielu** [comment]
Hi, I'll consider it in near future.

**Comment by Deewens** [comment]
Hi! Is this something you'll still consider?

**Comment by jaybhanushali3195** [comment]
Hello, is this still something you are considering ?

**Comment by zielu** [comment]
Hi, it's not under consideration at this moment.
