### ISSUE TITLE
[BUG] Commit dialog gitmoji completion can not work on webstorm

### ISSUE THREAD

**Issue by wangtaicheng** [zielu/GitToolBox#461]
**Describe the bug**
Commit dialog gitmoji completion can not work on webstorm 

**To Reproduce**

**Expected behavior**
Commit dialog gitmoji completion   works on the webstorm like on the idea

**Plugin version**
   zielu.gittoolbox (500.0.4+213)

**IDE version**
WebStorm 2022.3.2
Build #WS-223.8617.44, built on January 24, 2023

Runtime version: 17.0.5+1-b653.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 16384M
Cores: 12
Non-Bundled Plugins:
    ideanginx9 (0.1.10)
    Batch Scripts Support (1.0.13)
    com.haojiyou.CharAutoReplace (1.6.0)
    com.shuzijun.markdown-editor (2.0.4)
    ski.chrzanow.foldableprojectview (1.1.4)
    com.alibabacloud.intellij.toolkit-intellij (2023.1.1-223)
    zielu.gittoolbox (500.0.4+213)
    mobi.hsz.idea.gitignore (4.4.4)
    izhangzhihao.rainbow.brackets (2023.1.3)
    pro.bashsupport (3.2.1.223)

**Screenshots**

![webstorm64_MmrJeP9TfS](https://user-images.githubusercontent.com/6257526/220837130-a3d264c2-af1f-48b6-9ed8-b614ba9d8e62.gif)
![idea64_gkTbz8NOgY](https://user-images.githubusercontent.com/6257526/220837142-94d7f217-9d53-4968-866a-edc3933f2840.gif)

**Comment by zielu** [comment]
Hi, are you trying to insert 🪶 ? Because it seems to be github-specific one. I use https://gitmoji.dev as reference and it's not there.
<img width="1088" alt="image" src="https://user-images.githubusercontent.com/464103/220845327-5e5aacf3-f6e7-4dba-b10a-d19562226aff.png">

**Comment by wangtaicheng** [comment]
When I enter keywords, webstorm cannot prompt which gitmoji to use, but it can prompt and automatically complete moji code in idea. The first two screenshots in front are those that cannot be prompted in webstrom, and the second one is the correct prompt in idea

**Comment by zielu** [comment]
Ok, I get it now - I'll investigate.

**Comment by zielu** [comment]
@wangtaicheng did you enable Gitmojis in `Preferences > Version Control > GitToolBox / GitToolBox Project`

**Comment by wangtaicheng** [comment]
> @wangtaicheng did you enable Gitmojis in `Preferences > Version Control > GitToolBox / GitToolBox Project`

yes, i get it ，you can close this issue . thanks for your helpful reply .
