### ISSUE TITLE
[BUG] error while try to cleanup old branches

### ISSUE THREAD

**Issue by Ivanov-Anton** [zielu/GitToolBox#466]
**Describe the bug**

**To Reproduce**
1. create a branch that is assigned to git worktree
2. cleanup branch

**Expected behavior**
The old branch is deleted and `worktree` folder is deleted 

**Actual behavior**

```
00:22:53.476: [y_branch_name] git -c core.quotepath=false -c log.showSignature=false branch -D y_branch_name
error: Cannot delete branch 'y_branch_name' checked out at '/Users/example/p/y_branch_name'
```

**Comment by zielu** [comment]
Hi, this happened when you invoked cleanup from main repo or in worktree repo ?

**Comment by Ivanov-Anton** [comment]
@zielu from worktree repo
