### ISSUE TITLE
[Feature] GitToolBox for JetBrains Gateway

### ISSUE THREAD

**Issue by GTruf** [zielu/GitToolBox#467]
Hi, are there any plans to add GitToolBox (along with the free version) to the [JetBrains Gateway](https://www.jetbrains.com/remote-development/gateway/)? I really miss it there

**Comment by zielu** [comment]
Hi, my plugin is dependant on JB `Git Integration` - and afaik it is not supported by gateway.

**Comment by GTruf** [comment]
I really hope that in the future it will all work in JB Gateway. Apparently, we should create an issue in `Git Integration`.
Thanks for the answer!
