### ISSUE TITLE
[Feature] Disable notification of autofetch succeeding

### ISSUE THREAD

**Issue by jason-c-daniels** [zielu/GitToolBox#469]
As a developer with ADHD, I want to disable the popup that tells me when autofetch succeeded, so that I can limit my distractions and stay focused on coding.

Rationale:
Having this visual interruption is impossible for me to ignore. I still want it to fetch periodically and on branch switches. BUT, I cannot with the constant interruption of it telling me that it succeeded.

Instead I **have to turn off periodic fetching so that I can stay focused.** This is a request for accommodating a pretty common disability. (It's still a distraction when switching branches, but it's not one that derails my work every 15, 30, however many minutes its configured to... I **need** it to be quiet unless there is a problem.)

**Comment by zielu** [comment]
Hi, you can disable it in IDE notifications, see https://github.com/zielu/GitToolBox/wiki/Manual#notifications. Set "GitToolBox fetch info" Popup type to "No popup".

It looks like I need to expand that particular manual section to describe what each notification does.

**Comment by jason-c-daniels** [comment]
I still want to see it when there are errors. It's my understanding that using the setting you've recommend it will not show it, even if there are errors. **Is that correct?**

**Comment by zielu** [comment]
Hi, errors are shown via another group from IDE Git plugin, so you will still see them.

**Comment by jason-c-daniels** [comment]
Thanks! I'll close the issue then!
