### ISSUE TITLE
there is prompt information in the webstorm prompt at intervals

### ISSUE THREAD

**Issue by vela666** [zielu/GitToolBox#470]
**Describe the bug**
There is prompt information in the webstorm prompt at intervals

**To Reproduce**
open the editor for a while to view the prompts

**Expected behavior**
this issue did not exist in previous versions. How can I resolve it?

**Plugin version**
latest version

**IDE version**
WebStorm 2022.3.4
Build #WS-223.8836.50, built on March 15, 2023

Runtime version: 17.0.6+1-b653.34 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows Server 2019 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 6144M
Cores: 12
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true

Non-Bundled Plugins:
    zielu.gittoolbox (500.0.5+213)

**Screenshots**
![image](https://user-images.githubusercontent.com/69613314/228115321-a1422fae-b3c5-4c57-8aa9-58568beadec7.png)
![1679971492223](https://user-images.githubusercontent.com/69613314/228114023-a37aaa32-051a-4d6e-a3e0-a98400d494ab.jpg)

**Comment by zielu** [comment]
HI, you can mute this notification in IDE settings: https://github.com/zielu/GitToolBox/wiki/Manual#notifications

**Comment by vela666** [comment]
> 嗨，您可以在 IDE 设置中将此通知静音：https://github.com/zielu/GitToolBox/wiki/Manual#notifications

ok thanks
