### ISSUE TITLE
[BUG]java.lang.NullPointerException

### ISSUE THREAD

**Issue by JuanCaarPapers** [zielu/GitToolBox#471]
When I opened the first time the git toolbox this bug occurred but nothing destacable happened. 
The complete error: 

> d#update@GoToAction (zielu.gittoolbox.F.a.b.d), actionId=GitToolBox.OpenFileLink, text='Open File Link'
> 
> java.lang.NullPointerException
> 	at zielu.gittoolbox.t.u.a(SourceFile:144)
> 	at zielu.gittoolbox.t.u.a(SourceFile:117)
> 	at zielu.gittoolbox.F.a.b.a.a(SourceFile:40)
> 	at zielu.gittoolbox.F.a.b.a.update(SourceFile:22)
> 	at zielu.gittoolbox.F.a.b.d.update(SourceFile:13)
> 	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performDumbAwareUpdate$0(ActionUtil.java:157)
> 	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:180)
> 	at com.intellij.openapi.actionSystem.impl.ActionUpdater.doUpdate(ActionUpdater.java:718)
> 	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$updateActionReal$4(ActionUpdater.java:136)
> 	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$computeOnEdt$7(ActionUpdater.java:233)
> 	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:68)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
> 	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
> 	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:68)
> 	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$computeOnEdt$8(ActionUpdater.java:229)
> 	at com.intellij.diagnostic.telemetry.TraceKt.computeWithSpan(trace.kt:123)
> 	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$computeOnEdt$9(ActionUpdater.java:225)
> 	at io.opentelemetry.context.Context.lambda$wrapSupplier$8(Context.java:309)
> 	at com.intellij.openapi.actionSystem.impl.ActionUpdateEdtExecutor.lambda$computeOnEdt$0(ActionUpdateEdtExecutor.java:51)
> 	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:194)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:838)
> 	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:454)
> 	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:74)
> 	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:114)
> 	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:36)
> 	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
> 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
> 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
> 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
> 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
> 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
> 	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:909)
> 	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:756)
> 	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
> 	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
> 	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
> 	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
> 	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:838)
> 	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
> 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
> 	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
>

**Plugin version**
500.0.5 + 213 

**IDE version**
PyCharm 2022.3.3 (Professional Edition)
Build #PY-223.8836.43, built on March 10, 2023
Runtime version: 17.0.6+1-b653.34 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

**Comment by zielu** [comment]
Hi, I'll look into it tomorrow

**Comment by zielu** [comment]
Done in 500.0.6+213
