### ISSUE TITLE
[Feature] Auto Fetch popup length

### ISSUE THREAD

**Issue by enerjazzer** [zielu/GitToolBox#477]
I have a lot of repos in my project, so every time the Auto fetch is done, a huge 6-line popup appears.
Could we have an option to disable listing of all fetched repos if they are more than some N? I guess we really need a detailed notification for the repos we faiiled to fetch, and for the successful ones just "Auto Fetch finished (N repos)" could be enough

**Comment by zielu** [comment]
Hi, you can disable success notification via https://github.com/zielu/GitToolBox/wiki/Manual#notifications.
I was going to revisit notifications, so looks like now is the good time to do it 🙂.

**Comment by zielu** [comment]
@enerjazzer indeed it looks horrible. Out of curiosity - how many repos to you have ?

**Comment by thatcoleyouknow** [comment]
I would like to second this. I have well over 50 repos that get refreshed every 15 minutes and it fills up my notifications tab. I like to see when it fetches but I'd rather not see the mile-long list of repos every time. An option to show the previous success notification or what @enerjazzer proposed above would be nice.

**Comment by zielu** [comment]
I will release a change next week - when there are multiple repos updated it will just show a number. Regardless this notification can be muted even now, please see https://github.com/zielu/GitToolBox/wiki/Manual#notifications.

**Comment by thatcoleyouknow** [comment]
I did mute them for now. Thank you!

**Comment by zielu** [comment]
Done in 500.0.8

**Comment by enerjazzer** [comment]
Thanks, "53 repositories finished" is much more concise!
