### ISSUE TITLE
[Feature] Make icon color more neutral

### ISSUE THREAD

**Issue by tyrann0us** [zielu/GitToolBox#481]
**Is your feature request related to a problem? Please describe.**
I've been using your plugin for a couple of weeks now, and it's really great; thanks for maintaining it!

One thing bothers me, though: The icon in the GitToolBox notifications is red. For many people, including me, red means error. Whenever GitToolBox does an auto fetch or similar, the notification overlay shows, and I instantly think something has failed. This is hardened by my brain turning the message "Auto fetch finished" into "Auto fetch failed" if it sees the red icon next to it.

<img width="606" alt="Bildschirmfoto 2023-05-16 um 08 56 55" src="https://github.com/zielu/GitToolBox/assets/8144115/bdbc3632-4902-4120-bc69-3eff4ce3aa65">

**Describe the desired solution**
Use an icon with a more "neutral" color, like blue.

**Describe the alternatives that you have considered**
Don't output the notification so "prominently" because everything's already in the "Notifications" tab/toolbar. But even there, the red icon causes me to think everything failed:

<img width="371" alt="Bildschirmfoto 2023-05-16 um 10 27 33" src="https://github.com/zielu/GitToolBox/assets/8144115/20534895-f15a-467f-80ed-be2ebdd6d8e1">

Have fun finding the actual failure. 😉

**Additional context**
PhpStorm 2023.1.1

**Comment by zielu** [comment]
Agreed, it looks confusing. I'll dial it down 🙂

**Comment by zielu** [comment]
For info notifications I will adopt same color as IDE info icon - should blend right in :)
<img width="411" alt="image" src="https://github.com/zielu/GitToolBox/assets/464103/11e39b10-88a4-4b7e-afac-db82caa94b3c">

**Comment by zielu** [comment]
Done in 500.0.9

**Comment by tyrann0us** [comment]
Hi @zielu, not sure if this is a problem on my side, but with 500.0.9+213, most icons are still in the old color:
<img width="374" alt="Bildschirmfoto 2023-06-05 um 13 05 47" src="https://github.com/zielu/GitToolBox/assets/8144115/5590ad23-638f-449a-8372-7146ae6624be">

Note that I use the free version.

Thanks!

**Comment by zielu** [comment]
I'll take a look tonight

**Comment by zielu** [comment]
Done in 500.0.10 (this time for good :))

**Comment by tyrann0us** [comment]
I can confirm it works now. Thanks a ton! 🎉 

<img width="251" alt="Bildschirmfoto 2023-06-08 um 08 50 14" src="https://github.com/zielu/GitToolBox/assets/8144115/4544f2fc-4112-4208-91e4-8a0ee0d3b6c0">
