### ISSUE TITLE
[BUG] 【Affected Files 】is too slow

### ISSUE THREAD

**Issue by AndrewTseZhou** [zielu/GitToolBox#485]
**Describe the bug**

**To Reproduce**
1. Click on '【Affected Files 】'

**Expected behavior**
Hope to open the changes tab quickly, but the actual opening speed is very slow

**Plugin version**
500.0.10+213

**IDE version**
Android Studio Flamingo | 2022.2.1 Patch 2

**Screenshots**

**Comment by zielu** [comment]
Hi, I'll look into it.

**Comment by zielu** [comment]
All processing that could be moved to background was moved.
