### ISSUE TITLE
How does "Check key issue reference" work

### ISSUE THREAD

**Issue by wawyed** [zielu/GitToolBox#488]
I can't seem to get it to error. I have a commit VPC-9 and the branch is VPC-10 but no error.

This is my config:

![image](https://github.com/zielu/GitToolBox/assets/4390806/780acd65-6edf-4eac-ba38-d20995e9d11c)

**Comment by zielu** [comment]
Hi, this is inconsistency I recently discovered - on one hand there are completion formatters, yet in other places IDE Issue Navigation is used. I will address it soon. 
For issue key validation to work you have to configure https://www.jetbrains.com/help/idea/settings-version-control-issue-navigation.html

**Comment by wawyed** [comment]
Thank you, that worked :D
