### ISSUE TITLE
[Feature] File size limit to act on (e.g. compute blame annotations)

### ISSUE THREAD

**Issue by keiki61** [zielu/GitToolBox#490]
Hi, 

first thanks for the great plugin. 

Is it possible to provide a maximum file size (if not available already?) for gittoolbox for the current file?

We have huge ressource.properties files > 10 000 lines. Is it possible to disable automatic annotation computation for those files?

Best regards
Jens

**Comment by zielu** [comment]
Hi, there's no such limit. Do you experience any issues with current implementation or is blame for such files just useless information ?

**Comment by keiki61** [comment]
I had two git commands computing  blame information fully blocking 2 CPU cores and that for at least 10 seconds and blocking IntelliJ in that time for me. 

The information is not useless for me, but as the files are huge I favor to compute them manually when needed.

**Comment by zielu** [comment]
Hi, small update - I still need to reproduce this, but IDE should not be blocked during computation. Is UI getting non-responsive during calculation ?

**Comment by keiki61** [comment]
It was laggy, but this was more I guess due to the overall issue of IntelliJ handling 25 of those changed files in a commit dialog while in the meantime the blame information are computed for the files I have open.

**Comment by zielu** [comment]
500.1.0+222
