### ISSUE TITLE
[Feature] Hide auto fetch pop-up

### ISSUE THREAD

**Issue by ozturkberkay** [zielu/GitToolBox#491]
I don't like having too many pop-ups and notifications in my IDE, I find them distracting. It would be useful if we can disable the pop-ups for the auto fetch feature.

<img width="297" alt="image" src="https://github.com/zielu/GitToolBox/assets/7548962/1e36b485-31db-4015-96c6-2388312dd388">

**Comment by zielu** [comment]
Hi, this is how you can mute it https://man.sr.ht/~zielu/gittoolbox-man/manual.md#notifications
