### ISSUE TITLE
[BUG] pretty date formatting makes git log use 12h format

### ISSUE THREAD

**Issue by Sharpened99** [zielu/GitToolBox#493]
**Describe the bug**
In the Git LOG Window, the dates are shown on the right side (by default).
When using pretty date formatting, the times are always formatted in the 12h format, even when using the 24h format everywhere else

**To Reproduce**
1. Go to "Settings"->"Appearance & Behavior"->"System Settings"->"Date Format"
2. Set "Use 24-hour time"
3. Set "Use pretty formatting"
4. Go to "Git Log"
5. Look at the Commit dates, especially ones starting with "Today" or "Yesterday"

**Expected behavior**
It should correctly use the 24-hour format when specified in the settings

**Plugin version**
500.0.13+213

**IDE version**
OS: Linux Mint 21.2 Cinnamon
IDE: PyCharm Professional 2023.1.4 (231.9225.15)

**Screenshots**
![Settings](https://github.com/zielu/GitToolBox/assets/71272215/c48fb6a8-69fd-4801-8fcc-3b0dd3187b6a)
![Git Log](https://github.com/zielu/GitToolBox/assets/71272215/0cff409f-ff65-4193-b527-6c5c21e4b228)

**Comment by zielu** [comment]
HI, Git Log is not a feature of my plugin but it is provided by IDE https://www.jetbrains.com/help/pycharm/investigate-changes.html. I can report issue that you found in JetBrains tracker https://youtrack.jetbrains.com/issues/PY

**Comment by Sharpened99** [comment]
Well that went different to what I was expecting. Thank you for your help!
