### ISSUE TITLE
[Feature] Ability to disable/hide recent branches

### ISSUE THREAD

**Issue by MpoMp** [zielu/GitToolBox#495]
Please let us completely disable the recent branches section (either by setting to zero or with a flag).

It is also frustrating that even though I collapse the section in the pop-up, when I close and re-open it, the recent branches expand automatically.

**Comment by zielu** [comment]
Hi, could you add screenshot of UI control are you refering to ?

**Comment by MpoMp** [comment]
> Hi, could you add screenshot of UI control are you refering to ?

Sure: 
![image](https://github.com/zielu/GitToolBox/assets/1170690/133b1569-8ac3-4382-aaf6-62556da8a0cb)

**Comment by zielu** [comment]
This control is not provided by my plugin but by IDE Git integration https://www.jetbrains.com/help/idea/manage-branches.html

I'll create bug report in Jetbrains issue tracker.

**Comment by MpoMp** [comment]
Thank you!

**Comment by zielu** [comment]
@MpoMp there is Jetbrains issue open - https://youtrack.jetbrains.com/issue/IDEA-326328 and it contains some workaround.

**Comment by MpoMp** [comment]
Thanks a lot!
