### ISSUE TITLE
[Feature] Configure `branches cleanup` to work with squash merging

### ISSUE THREAD

**Issue by kvenn** [zielu/GitToolBox#499]
Right now it lists branches as "outdated, not merged" because it is unaware of squash-merged branches.

I've been using this stack-overflow solution to list local branches that have been squash-merged and deleted on remote:
https://stackoverflow.com/a/56026209/1759443

It would be incredible if this was a configuration for both the list and the prune.

**Comment by zielu** [comment]
Hi, I was considering this but it requires "base" branch to be set up somehow. I'll look into how it can be done.

**Comment by kvenn** [comment]
Thank you!!! I love GTB and this would be such a massive unlock. Also happy to help in any way. Just let me know.
I'd personally be fine if there was a checkbox with a field where you enter in base branch (either in settings or on the clean dialog itself).

**Comment by Mathieson** [comment]
I've wondered why my branches show this status during the cleanup operation when I know they've been merged. I'd love to see this working!

**Comment by zielu** [comment]
I'm revisiting branch cleanup so squash merge detection will also be added 😀

**Comment by zielu** [comment]
Done in 500.2.8
