### ISSUE TITLE
Feature Request: check repository changes

### ISSUE THREAD

**Issue by wutscho** [zielu/GitToolBox#5]
I miss a feature in PHPStorm which might be possible to implement in GitToolBox:

Can you add some note if a remote repository / branch did change after the last fetch?

The tricky part might be that you can not permform a git fetch outside of the regular phpstorm git environement because this will confuse the phpstorm git log.
On the other hand it might be ok to just trigger a regular git fetch via the usual PHPStorm way, for example every minute.

I think this would be really great to have!

**Comment by zielu** [comment]
Just to let you know - feature is coming this week just needs some testing in "production" ;). 
It works like this when enabled:
- when project is opened first fetch runs after 30 seconds - I added delay, not to hit IntelliJ too much during startup
- after that fetch is executed with configurable intervals (10 - 180 minutes)

Do I understand correctly that it would be also nice to display some kind of message when "new" commits appeared since last fetch ?

**Comment by zielu** [comment]
Implemented in 13.5.0

**Comment by wutscho** [comment]
Hi Lukasz,
thanks a lot! This feature is really really cool, I like it!
Is there a technical reason why the minimum fetch interval is limited to 10 minutes?

**Comment by zielu** [comment]
Hi,
there is synchronization in IDE on some git commands that blocks others. For example fetch causes push, commit to wait. I didn't want fetch to overwhelm other actions. 
I think lowering minimum to 5 minutes would still będzie usable

**Comment by cburakov** [comment]
Thanks for this feature but please disable it on local branches.

**Comment by zielu** [comment]
@cburakov - I'll add check that will run Auto-fetch only for project repositories that have remotes and only then.

Question is do you need some more control this ? 
For example I could add 2 strategies:
- run when at least one repo has remotes
- run when at least one current branch in project has remote
It would also run fetch only for repos meeting strategy condition.

**Comment by cburakov** [comment]
No need of more controls for me now. Just don't want to see error messages when there is no chance for Auto-fetch to succeed.

**Comment by zielu** [comment]
I pushed new build, it should help.

If it does not I will need more details like: IDE version, your project setup - no. of repos, what kind of branches do you have checked out (pure local, remote tracking etc.), do they have remotes, are remotes reachable etc.

**Comment by cburakov** [comment]
Thanks, it works good now.

**Comment by zielu** [comment]
Closing for good
