### ISSUE TITLE
[BUG] file/repository links do nothing

### ISSUE THREAD

**Issue by billwert** [zielu/GitToolBox#502]
**Describe the bug**
I've just paid for my license and restarted the IDE, etc. I got issue links working with configuration. When I right click->GitToolBox and choose any of file/repository open/copy nothing happens. I see nothing in the log.

**To Reproduce**
1. Right click and open context menu
2. Choose copy file link. (or open, or do either for remote.)

**Expected behavior**
The link is copied.

**Plugin version**
500.0.18+222

**IDE version**
IntelliJ IDEA 2023.2.1 (Ultimate Edition)
Build #IU-232.9559.62, built on August 22, 2023
Runtime version: 17.0.8+7-b1000.8 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 16
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true

Non-Bundled Plugins:
    com.github.copilot (1.2.21.2995)
    Key Promoter X (2023.2.0)
    com.intellij.plugins.vscodekeymap (232.8660.88)
    com.samdark.intellij-visual-studio-code-dark-plus (2.8)
    CheckStyle-IDEA (5.82.0)
    uk.co.ben-gibson.remote.repository.mapper (4.3.6)
    zielu.gittoolbox (500.0.18+222)
    com.microsoft.tooling.msservices.intellij.azure (3.80.2-2023.2)

Kotlin: 232-1.9.0-IJ9559.62

**Comment by zielu** [comment]
Hi, which repository type is that ? (github, gitlab etc)

For repository links there should be a log from `zielu.gittoolbox.ui.link` if the link could not be calculated.

**Comment by billwert** [comment]
Oh, sorry. Github almost always with two remotes configured, ala:

origin    https://github.com/billwert/azure-sdk-for-java (fetch)
origin    https://github.com/billwert/azure-sdk-for-java (push)
upstream           https://github.com/Azure/azure-sdk-for-java.git (fetch)
upstream           https://github.com/Azure/azure-sdk-for-java.git (push)
s
Thanks,
-Bill

**Comment by zielu** [comment]
I created a dev build with extra logging (500.0.19+222). Could you do the following:
1. switch to plugin [EAP channel ](https://man.sr.ht/~zielu/gittoolbox-man/manual.md#eap-release-channel)
2. enable [debug logging](https://man.sr.ht/~zielu/gittoolbox-man/manual.md#debug-logging) from `zielu.gittoolbox.ui.link` by adding `#zielu.gittoolbox.ui.link` to `Debug Log Settings`
3. check in logs for `zielu.gittoolbox.ui.link`

**Comment by zielu** [comment]
@billwert checking in if you tried steps outlined above?

**Comment by billwert** [comment]
Apologies, not yet. I'm off work today but will check it out on Wednesday.

**Comment by zielu** [comment]
No feedback on the issue, but plugin was extended with new notifications indicating why action did nothing

**Comment by billwert** [comment]
hey @zielu apologies for disappearing on you here. :)

I just renewed my license and gave this a shot. I think I'm on the EAP build (`600.0.1+242` is my version number) and enabled the debug logging and do not see anything interesting in the log, past seeing the log is enabled:
```
8547:2024-10-08 12:58:43,828 [  92545]   INFO - #c.i.d.l.LogLevelConfigurationManager - Level DEBUG is set for the following category: #zielu.gittoolbox.ui.link
8548:2024-10-08 12:58:43,828 [  92545]   INFO - #c.i.d.l.LogLevelConfigurationManager - Level DEBUG is set for the following category: zielu.gittoolbox.ui.link
```

The new UI popup when I try to execute the action just says:
![image](https://github.com/user-attachments/assets/04c66b3b-90d9-411b-9557-c2d140810937)

**Comment by zielu** [comment]
Hi, a break was not that bad. I finally see it -  `https://github.com/billwert/azure-sdk-for-java` without `.git` and the end. I did not realize that It is possible to have such upstream uri. Definitely this is something to fix.

**Comment by zielu** [comment]
Done in 600.0.2+242, 233 variant will be released in few days.

**Comment by billwert** [comment]
fixed! thank you!
