### ISSUE TITLE
[BUG] Changes to GitToolBox > Branch > Excluded branches does not save

### ISSUE THREAD

**Issue by baynezy** [zielu/GitToolBox#504]
**Describe the bug**
I am trying to modify the list of Excluded branches, but any change I make is lost on Save.

**To Reproduce**
1. Go to Version Control > GitToolBox > Branch > Excluded branches
2. Edit the list of branches
3. Click Save button
4. Go to Version Control > GitToolBox > Branch > Excluded branches
5. Changes are not saved

**Expected behavior**
1. Go to Version Control > GitToolBox > Branch > Excluded branches
2. Edit the list of branches
3. Click Save button
4. Go to Version Control > GitToolBox > Branch > Excluded branches
5. Changes are saved

**Plugin version**
Exact plugin version. 500.0.18+222

**IDE version**
Exact IDE and OS.
JetBrains Rider 2023.2.1
Build #RD-232.9559.61, built on August 22, 2023
Subscription is active until July 12, 2024.
Runtime version: 17.0.8+7-b1000.8 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
.NET Core v7.0.7 x64 (Server GC)
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 16
Registry:
    ide.experimental.ui=true
    vcs.empty.toolwindow.show=false
    ide.new.project.model.index.case.sensitivity=true
    database.show.search.tab=false

Non-Bundled Plugins:
    com.settler.rider.specflow (1.17.0)
    verify-rider (2023.2.0)
    org.intellij.plugins.hcl (232.8660.88)
    com.github.copilot (1.2.22.3129)
    org.jetbrains.plugins.go-template (232.8660.88)
    nsubstitutecomplete-rider (1.10.0)
    fr.socolin.application-insights-debug-log-viewer (1.9.0)
    com.wakatime.intellij.plugin (14.2.2)
    com.intellij.resharper.StructuredLogging (2023.2.0.305)
    com.intellij.plugin.adernov.powershell (2.1.0)
    com.intellij.kubernetes (232.9559.34)
    me.seclerp.rider.plugins.efcore (232.1.0)
    com.intellij.ml.llm (232.9826)
    zielu.gittoolbox (500.0.18+222)
    com.intellij.resharper.azure (3.50.0.1679-2023.2)
    aws.toolkit (1.79-232)
    org.digma.intellij (2.0.175+232)

**Screenshots**

![image](https://github.com/zielu/GitToolBox/assets/1049999/1823f470-c065-4927-95cd-e95a9b29c3b2)
If I edit the Excluded branches and press save the changes are not saved.

**Comment by zielu** [comment]
Hi, I'll look into it today.

**Comment by zielu** [comment]
Done in 500.0.20+222

**Comment by baynezy** [comment]
Works a treat. Thank you.
