### ISSUE TITLE
[BUG]What does the cleanup did when it says it deleted some branches

### ISSUE THREAD

**Issue by Happy-ArthurYang** [zielu/GitToolBox#505]
**Describe the bug**
The UI told me there are some branchs are outdated, and when I click the OK button, it begin to deletge the outdatged branches.
My question is what does outdated branche mean and what did this tool do when it cleans up the outdated branches?

**To Reproduce**

**Expected behavior**

**Plugin version**
Exact plugin version. Eg. 212.8.4

**IDE version**
Exact IDE and OS. You can use About > Copy 

**Screenshots**
![image](https://github.com/zielu/GitToolBox/assets/113080404/9f8ac8d7-f3d3-4472-ad30-eceef46de065)

**Comment by zielu** [comment]
Hi, it deletes local branches as in 'git branch -d'.

**Comment by Happy-ArthurYang** [comment]
thanks a lot
