### ISSUE TITLE
Missing inline blame text color

### ISSUE THREAD

**Issue by serious-angel** [zielu/GitToolBox#506]
**Describe the bug**

Dear Developers,

Thank you for the wonderful project!

I am sorry, but just wanted to clarify an absence of any option to change the color of the inline blame to make it not look the same as the code preferably.

For example, how it looks like: `Screenshot #1`.

As you might notice, it may be quite challenging to differentiate the actual code (i.e. a comment in this case) from the blame line.

Hence the clarification request since I didn't notice that setting in the actual settings nor the source code of the plugin.

Best and kind regards :sparkles: 

**To Reproduce**

1. Create any temporary JavaScript or Bash file;
2. Write some wonderful comments;
3. Create a commit from all of this;
4. Set some `Monokai` code/editor theme;
5. See the blame and try noticing the charming difference!

**Expected behavior**

Preferably, inline blame lines should be slightly darker than the comment text. For example, I tried changing the text color to something more colorful, but _it would be more awesome to have it **darker instead** of colorized_: `Screenshot #2`.

**Plugin version**

`500.0.21+222`

**IDE version**

```
PhpStorm 2023.2.2
Build #PS-232.9921.55, built on September 15, 2023
Licensed to Faith
Subscription is active until October 31, 2023.
Evaluation purpose only.
Runtime version: 17.0.8+7-b1000.22 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.19.0-35-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 8192M
Cores: 4
Registry:
    run.processes.with.pty=TRUE
    documentation.show.toolbar=true
    caches.scanningThreadsCount=3
    ide.experimental.ui=true

Non-Bundled Plugins:
    OpenGL-Plugin (1.0.72)
    com.nasller.CodeGlancePro (1.7.5)
    monokai-pro (1.10)
    com.intellij.ideolog (222.1.0.0)
    String Manipulation (9.11.3)
    dev.meanmail.plugin.nginx-intellij-plugin (2022.1.1)
    Key Promoter X (2023.2.0)
    de.espend.idea.php.annotation (9.4.0)
    net.seesharpsoft.intellij.plugins.csv (3.2.1-232)
    com.atlassian.bitbucket.references (2022.1.242)
    izhangzhihao.rainbow.brackets (2023.3.6)
    zielu.gittoolbox (500.0.21+222)
    mobi.hsz.idea.gitignore (4.5.2)

Current Desktop: KDE
```

**Screenshots**

### `Screenshot #1`

![Screenshot_20231013_163114](https://github.com/zielu/GitToolBox/assets/25136754/b05e3b63-590c-4eb6-8a8a-b637bd96f142)

### `Screenshot #2`

![Screenshot_20231013_163114-2](https://github.com/zielu/GitToolBox/assets/25136754/37a928ee-b641-484a-a88c-f9500a86f59b)

**Comment by zielu** [comment]
Hi, color configuration is under `Settings / Editor / Color Scheme / GitToolBox Color`

**Comment by serious-angel** [comment]
> Hi, color configuration is under `Settings / Editor / Color Scheme / GitToolBox Color`

Dear! This is so awesome! I am sorry I did not notice it in the first place...
Thank you very much, dear @zielu, and Everyone Marvelous for the project!

I hope you are safe! Please stay safe and have a pleasant time! :sparkles:

**Comment by serious-angel** [comment]
![Screenshot_20231016_151210](https://github.com/zielu/GitToolBox/assets/25136754/180303ef-77f8-4a1c-8694-5ee521926072)
