### ISSUE TITLE
[Question] can I pull mutiple projects at one time

### ISSUE THREAD

**Issue by Happy-ArthurYang** [zielu/GitToolBox#507]
**Describe the bug**
I will work with mutiple projects at one time, currently I can only pull data one  by one, wnat to know can I pull mutiple projects at one time, on need to right mouse and find find the Git/pull options?

![image](https://github.com/zielu/GitToolBox/assets/113080404/14187220-6686-4714-a91e-fed473ddddc9)

**Comment by zielu** [comment]
Hi, this is part of standard IDE Git integration - you can do `Git > Update Project...`

**Comment by Happy-ArthurYang** [comment]
Thank you very much!
