### ISSUE TITLE
[BUG] GitHub Links Broken when Branch doesn't exist on remote

### ISSUE THREAD

**Issue by jamesmcguirepro** [zielu/GitToolBox#511]
**Describe the bug**

**To Reproduce**
1. Create a git branch locally (but do not push to remote)
2. Use GitHub Toolbox to Open File Link/Copy File Link
3. Observe link is broken as the branch name is missing

**Expected behavior**
GitHub Toolbox should fallback to master (or even fancier, whatever base branch is present on the remove)

**Plugin version**
500.0.22+222

**IDE version**
RubyMine 2023.2.5
Build #RM-232.10227.6, built on November 7, 2023
Licensed to Procore Technologies / James McGuire
You have a perpetual fallback license for this version.
Subscription is active until December 26, 2024.
Runtime version: 17.0.9+7-b1000.46 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.1.1
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 10
Metal Rendering is ON
Registry:
    ide.experimental.ui=true

Non-Bundled Plugins:
    com.github.copilot (1.4.0.3748)
    com.intellij.swagger (232.9921.7)
    com.crunch42.openapi (1.69)
    zielu.gittoolbox (500.0.22+222)

**Screenshots**

**Comment by zielu** [comment]
Hi, I'm preparing to release new version soon that will address this issue.

**Comment by zielu** [comment]
Done in 500.1.0+222
