### ISSUE TITLE
unnecessary notifications

### ISSUE THREAD

**Issue by DennisKost** [zielu/GitToolBox#514]
I want to disable notifications in the popup like "Auto fetch", "Git Branch Cleanup". It's annoying and distracting when running on a timer.
![Screenshot_1](https://github.com/zielu/GitToolBox/assets/63783766/fcaa6701-dff6-463f-9b08-c6f00c243f7d)

**Comment by zielu** [comment]
Hi, you can disable them in IDE settings https://man.sr.ht/~zielu/gittoolbox-man/manual.md#notifications.
