### ISSUE TITLE
Text is overlapping with other tabs

### ISSUE THREAD

**Issue by volkflo** [zielu/GitToolBox#519]
**Describe the bug**
If you are in split pane view with two tabs the content of the left tab overlaps the content of the right tab.
See the screenshot below.
The problem is solved once you disable the plugin and restart Intellij.

The jetbrains team already analysed the problem and confirmed the behavior.
Please see the related Jetbrains tickets in youtrack:

- https://youtrack.jetbrains.com/issue/IDEA-340571
- https://youtrack.jetbrains.com/issue/IDEA-340935

**To Reproduce**
1. Split editor into two tabs
2. Left tab should contain one longer line

**Expected behavior**
Content is not overlapping.

**Plugin version**
500.1.1+222

**IDE version**
```
IntelliJ IDEA 2023.3.1 (Ultimate Edition)
Build #IU-233.11799.300, built on December 12, 2023
Subscription is active until August 3, 2024.
Runtime version: 17.0.9+7-b1087.7 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 6.1.67-2-manjaro
GC: G1 Young Generation, G1 Old Generation
Memory: 8192M
Cores: 16
Registry:
  debugger.new.tool.window.layout=true
  ide.experimental.ui=true
  go.run.processes.with.pty=false
Non-Bundled Plugins:
  com.github.lppedd.idea-conventional-commit (0.22.0)
  some.awesome (1.14)
  com.markskelton.one-dark-theme (5.9.0)
  com.godwin.json.parser (1.7.1)
  org.jetbrains.plugins.go (233.11799.196)
  com.jetbrains.packagesearch.intellij-plugin (233.11799.196)
  String Manipulation (9.12.0)
  com.github.camork.fileExpander (2.3)
  org.asciidoctor.intellij.asciidoc (0.41.2)
  MavenRunHelper (4.27.1-IJ2022.2)
  zielu.gittoolbox (500.1.1+222)
  mobi.hsz.idea.gitignore (4.5.2)
  ru.adelf.idea.dotenv (2023.3)
  com.intellij.plugins.html.instantEditing (233.11799.172)
Kotlin: 233.11799.300-IJ
Current Desktop: GNOME

```

**Screenshots**
![image](https://github.com/zielu/GitToolBox/assets/13332383/ddd7c3e6-c8e0-492a-95f4-6549c80245fa)

**Comment by zielu** [comment]
Hi, I'll start investigating today.

**Comment by zielu** [comment]
RCA: new blame rendering pipeline was overwriting Graphics2D clip

**Comment by zielu** [comment]
Fixed in GitToolBox 500.1.2+222

**Comment by volkflo** [comment]
Fantastic, thank you for this quick fix! :rocket:

**Comment by zielu** [comment]
Fortunately it was a 2-liner ;)
