### ISSUE TITLE
[BUG] Option for "Always calculate git blame" missing

### ISSUE THREAD

**Issue by Engazan** [zielu/GitToolBox#520]
**Describe the bug**
its rlly annoying to click in every file with 5000+ lines, there should be option to enable it for every file, cuz default was enabled for all files without this annoying msg, now it doesnt work until you allow it for every single file :/

**To Reproduce**
1. Open file with 5000+ lines

**Expected behavior**
button "Always calculate"

**Plugin version**
500.1.1+222

**IDE version**
Build #PS-233.11799.297, built on December 11, 2023

**Screenshots**
![Screenshot 2023-12-15 090902](https://github.com/zielu/GitToolBox/assets/53254371/afb04e21-2337-4ad9-9176-b0c51927f57f)

**Comment by zielu** [comment]
Hi, you can configure threshold and even disable this feature here:
![image](https://github.com/zielu/GitToolBox/assets/464103/26fdd850-5372-445a-8d20-3eccb536ed9b)
