### ISSUE TITLE
[Feature] Support built-in Settings Sync

### ISSUE THREAD

**Issue by keysmashes** [zielu/GitToolBox#522]
Every time GitToolbox gets installed in a new IDE or on a new machine by Settings Sync I have to remember to configure it how I want (e.g. turning off auto fetch etc.)

It seems like it should be possible for plugin settings to sync between IDEs, but it requires some action on the part of the plugin developer – see https://youtrack.jetbrains.com/issue/IDEA-227142/Sync-plugins-settings-with-IDE-Settings-Sync and https://plugins.jetbrains.com/docs/intellij/persisting-state-of-components.html#settings-sync-plugin. (Or maybe it's because GitToolbox's settings are under "Version Control", which is per-project? I have no idea)

I would be extremely grateful if you would consider implementing some way of syncing settings between projects/IDEs :)

**Comment by zielu** [comment]
Hi, I'll look into it - looks like IDE-level settings (Version Control / GitToolBox) should be possible to sync.

Note - min IDE version needs to be bumped to 2022.3 (from 2022.2), but it should not be a problem.

**Comment by zielu** [comment]
Done in 500.1.6+222
