### ISSUE TITLE
[BUG] Wrong git submodule recognition

### ISSUE THREAD

**Issue by wait2035** [zielu/GitToolBox#523]
**Describe the bug**

When i have a git repo named "**`aaaa`**",  and i have 2 submodule, named "**`bbbb`**" and "**`cccc`**", while this time, i have one directory named "**`bbbbXXXX`**"(bbbb, which is submodule name, and also a prefix of aaaa's sub-director), the gittoolBox will recognize this bbbbXXXX as a part of submodule, and show me wrong message: "Fetal: xxx is outside repository at bbbb".

directory just like following:

tree aaaa
-------------
.
├── bbbb (submodule)
├── bbbbXXXX (normal directory of aaaa)
├── cccc (submodule)

**To Reproduce**

**Expected behavior**
the files under bbbXXX/ can be recognized correctly
only the files under bbbb/ can be recognized as the part of submodule bbbb.

**Plugin version**
3.3.5.233

**IDE version**
CLION Version: #CL-233.13135.93

Runtime Info: 
17.0.9+7-b1087.9 aarch64
VM: OpenJDK 64-Bit Server VM，JetBrains s.r.o

MAC M1, 14.1.2 (23B92)
**Screenshots**
Unable to provide external information

**Comment by wait2035** [comment]
i mismatched the lable, it should be bug not question, sorry.

**Comment by wait2035** [comment]
![image](https://github.com/zielu/GitToolBox/assets/40983090/cac8aea9-c875-4b4a-9296-c073bb0e721e)
like this pic.

**Comment by zielu** [comment]
Hi, I'll look into it.

**Comment by wait2035** [comment]
> Hi, I'll look into it.
Thank you.

**Comment by zielu** [comment]
Done in 500.1.5+222

**Comment by wait2035** [comment]
Thanks a lot. I see it works fine in my workspace now.
