### ISSUE TITLE
[Feature]Incompatible with Webstorm 2024.1 EAP

### ISSUE THREAD

**Issue by xin2014** [zielu/GitToolBox#524]
![image](https://github.com/zielu/GitToolBox/assets/7124907/01ad9920-057c-44f0-b78c-d3cf67525cb2)

**Comment by zielu** [comment]
Hi, I did not notice JB already started 2024.1 EAP. On it.

**Comment by zielu** [comment]
Hmm, my primary build target is Idea and 2024.1 build is not up yet - need to wait for one.

**Comment by zielu** [comment]
Done in 500.1.6+222
