### ISSUE TITLE
[BUG] Manual link times out

### ISSUE THREAD

**Issue by Craig-At-Ollie** [zielu/GitToolBox#526]
**Describe the bug**
The manual is failing

**To Reproduce**
1. Go to [['...'](https://man.sr.ht/~zielu/gittoolbox-man/manual.md)](https://man.sr.ht/~zielu/gittoolbox-man/manual.md)

**Expected behavior**
To see a manual

**Screenshots**
![image](https://github.com/zielu/GitToolBox/assets/150487402/77056a82-5ba1-4d5e-ad25-50c12fdc441c)

**Comment by zielu** [comment]
Hi, I'm aware of this. Unfortunately Sourcehut where I'm hosting the manual went down day before yesterday [due to DDoS](https://outage.sr.ht). I'm monitoring the situation if they are not back tomorrow I will be moving to new hosting provider.

**Comment by zielu** [comment]
Looks like sourcehut is up, but I'll be setting up dedicated manual site anyway

**Comment by zielu** [comment]
New docs site is up: https://gittoolbox.lukasz-zielinski.com
