### ISSUE TITLE
[BUG] The address that opened from "generator" button is not correct in our company's gitlab. How to config the address?

### ISSUE THREAD

**Issue by baiyulong** [zielu/GitToolBox#527]
**Describe the bug**

**To Reproduce**
1. Press Ctrl + T to update project.  Then failed because of none token was configed.
2. Now the window is showing. Click on 'Generator' button. It will open gitlab like this "http://xxx.gitlab.com/-/profile/personal_access_tokens?name=IntelliJ%20IDEA%20GitLab%20Integration%20Plugin&scopes=api%2Cread_user". But the address of our gitlab is not same with below address.
3. How can I change the address?

![image](https://github.com/zielu/GitToolBox/assets/4569023/8a5e883e-2890-4fa6-9c77-85aea0b5ed03)

**Expected behavior**

**Plugin version**
Exact plugin version. Eg. 212.8.4

**IDE version**
Exact IDE and OS. You can use About > Copy 

**Screenshots**

**Comment by zielu** [comment]
Hi, this is not part of my plugin but does seem to be part of [IDE built-in GitLab integration](https://www.jetbrains.com/help/idea/gitlab.html#manage-gitlab-accounts)

**Comment by baiyulong** [comment]
OK. Thanks. Your plugin is great. It's very useful.
