### ISSUE TITLE
[Feature] 在goland2023.3.2中安装之后报错需要安装插件'Git4Idea'

### ISSUE THREAD

**Issue by zzzpppy** [zielu/GitToolBox#534]
![image](https://github.com/zielu/GitToolBox/assets/49774236/4f7caa92-913c-409c-9249-d079a936f1b6)

**Comment by zielu** [comment]
Hi, I'll look into this. I was under impression it should be available.

**Comment by zielu** [comment]
I looked into this and it seems that for some reason you are missing Jetbrains Git bundled plugin which is a mandatory dependency of GitToolBox. Bundled Git is normally present in goland.

I mean this bundled plugin:
![image](https://github.com/zielu/GitToolBox/assets/464103/c1e804f8-d631-4cbf-8c3d-e15834b622f8)
