### ISSUE TITLE
[Feature] new plugin just for “Git blame display” 

### ISSUE THREAD

**Issue by buildyuan** [zielu/GitToolBox#535]
First of all, I want to say that this plugin is the best git plug-in I have ever used.

He has a lot of great features, customized for advanced developers.

However, my current git is a self-built private repository.

I only used the function “Git blame display” .

Is it possible to launch this function to the market as an independent plugin?

**Comment by zielu** [comment]
Hi, I gave it some thought and my approach is to keep things as one plugin - currently features are interlocked at deep level. It creates some complexity but allows features to be added faster, by building on top of shared infrastructure.
