### ISSUE TITLE
[BUG] "File is too big for inline blame calculation" warning banner is shown even when inline blame is disabled

### ISSUE THREAD

**Issue by PrOF-kk** [zielu/GitToolBox#536]
**Describe the bug**
The "File has 5,000 or more lines, inline blame calculation might be CPU intensive" warning banner is shown even when the feature is disabled

**To Reproduce**
1. Disable inline blame in Settings > Version Control > GitToolBox > "Blame" tab > uncheck "Show editor inline Blame"
2. Open a very large file
3. See warning banner anyway

**Expected behavior**
Plugin shouldn't calculate inline blame at all if not enabled

**Plugin version**
500.1.11+222

**IDE version**
PhpStorm 2023.3.4

**Comment by zielu** [comment]
Hi, it looks like I missed this code path. Large file notification can be triggered by two features:
1. inline blame that you disabled
2. status bar blame - GitToolBox > General > Show 'Blame' in status bar

As a workaround, until I fix this, you can disable second one too and restart it. Blame calculation should not be triggered anymore.

**Comment by zielu** [comment]
Done in 500.2.0
