### ISSUE TITLE
[Feature] AzureDevops Support

### ISSUE THREAD

**Issue by kimpenhaus** [zielu/GitToolBox#542]
Hi @zielu 

thanks for the plugin - which I use on a daily basis and which helps a lot.

I wonder - or maybe am mistaken - why there is no AzureDevops support for the repos:

<img width="2198" alt="image" src="https://github.com/zielu/GitToolBox/assets/575109/60e47d27-4097-4a15-a912-0233cb79a1ac">

<img width="1522" alt="image" src="https://github.com/zielu/GitToolBox/assets/575109/ea475516-7030-450f-b4a9-064ff5eab82a">

Is there any chance to build that? Or is there any custom configuration one can do to make it work?

one more thing - ewhich is more like a question - if AzureDevops would be supported, would that issue number turn into a link to the ticket?

<img width="2762" alt="image" src="https://github.com/zielu/GitToolBox/assets/575109/75241ae6-4d87-4be0-9f20-589513bdccc6">

Thanks,
Marcus

**Comment by zielu** [comment]
Hi @kimpenhaus I'm actually working on Azure repos support right now. It should be ready next week.
As for issue links they should be working right now - I'm just [integrating](https://gittoolbox.lukasz-zielinski.com/docs/issue-navigation-integration/) with IDE [Issue Navigation](https://www.jetbrains.com/help/idea/handling-issues.html)

For issue pattern from screenshot something like following should work:
- Issue ID: `#\d+`
- Issue Link: `https://dev.azure.com/<your organization>/<your project name>/_workitems/edit/$1/`

**Comment by kimpenhaus** [comment]
@zielu that sounds awesome - so just waiting happily for the next release - cheers mate!

the issue navigation worked perfectly - thanks!

<img width="962" alt="image" src="https://github.com/zielu/GitToolBox/assets/575109/fe188f3f-15ca-40a6-87b3-0550736d5b3d">

**Comment by zielu** [comment]
Done in 500.2.3

**Comment by kimpenhaus** [comment]
@zielu oh that's pretty cool - the first tests I did look very good

repo is detected

<img width="1312" alt="image" src="https://github.com/zielu/GitToolBox/assets/575109/97ad8a30-4ef7-4be3-b498-c0356ee74244">

and all the links seem to work properly

<img width="904" alt="image" src="https://github.com/zielu/GitToolBox/assets/575109/a327d448-c7eb-452c-82b4-8e391aef161a">

thanks for keeping me in the loop and of course for implementing azure devops support :)
