### ISSUE TITLE
[Feature] Optionally require key pressed for inline links to work

### ISSUE THREAD

**Issue by anbuc** [zielu/GitToolBox#545]
The links added by GitToolBox (Code vision, inline blame) currently work directly and open the browser. This forces the IDE into the background, which is especially irritating if I just wanted to bring the IDE into the foreground and clicked _somewhere_ in the editor but accidentally hit one of those links.

PHPStorm itself has a configurable keybind for clicking links (command+click or ctrl+click by default), otherwise the links are just treated as text. Something similar would be nice for the GitToolBox links as well.

This should go for any links that would open the browser.

**Comment by zielu** [comment]
Hi, you are correct it's irritating :) . I'll add this.

**Comment by zielu** [comment]
Done in 500.2.5
![image](https://github.com/zielu/GitToolBox/assets/464103/d0a6356e-e9d9-4cc2-991a-a7adf182757c)

**Comment by Muscleape** [comment]
> Done in 500.2.5 ![image](https://private-user-images.githubusercontent.com/464103/324433924-d0a6356e-e9d9-4cc2-991a-a7adf182757c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3ODQ1OTgsIm5iZiI6MTcxMzc4NDI5OCwicGF0aCI6Ii80NjQxMDMvMzI0NDMzOTI0LWQwYTYzNTZlLWU5ZDktNGNjMi05OTFhLWE3YWRmMTgyNzU3Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMlQxMTExMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMTgyOGYxNmNmMzg3NWY4OWRhYTQxNDkwNjZjNWZhMzdhYTc0MDAxZDg0YTFkZDQzMzI4YjU4NWE3ODZlNWQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Oz7h310C_7IpKKQ9cE0pVykPMTA5H2_UHOBJMZO_B9Y)

but it doesn't work for me

**Comment by zielu** [comment]
Now it depends what you have configured for Click Link action. For example I'm on mac and I had to remove `force touch` to  make it behave
