### ISSUE TITLE
[BUG] GitToolBox shows an advertisement every time I start RubyMine

### ISSUE THREAD

**Issue by unikitty37** [zielu/GitToolBox#548]
**Describe the bug**
Every time I restart RubyMine, a new tab is opened with the following text

> 🎉 Thank you for using GitToolBox 🎉
I recently released a new freemium plugin integrating Git worktrees into the IDE. You can find more info on [gitworktree.lukasz-zielinski.com](https://gitworktree.lukasz-zielinski.com/)

**To Reproduce**
Steps to reproduce the behaviour:
1. Start RubyMine. Observe the tab is opened.
2. Close the tab.
3. Quit RubyMine.
4. Start RubyMine. Observe the tab is reopened.

**Expected behaviour**
At most, the tab should appear **once** and, once closed, should not reappear again. ("Once" means "once _ever_", not "once per RubyMine session", "once per week", "once per RubyMine version", by the way!)

Ideally, the IDE I pay for and use for productive work should **never be hijacked by advertising unless I have explicitly consented to it** (and "explicitly consented" means I am not penalised for saying "no" by means such as disabling features).

There isn't even an option I can find in Settings > Version Control > GitToolBox to disable this.

**Plugin version**
500.2.3+233

**IDE version**
RubyMine 2024.1
Build #RM-241.14494.234, built on March 27, 2024
Licensed to REDACTED
Runtime version: 17.0.10+8-b1207.12 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.6.1
GC: G1 Young Generation, G1 Old Generation
Memory: 3072M
Cores: 10
Metal Rendering is ON
Registry:
  undo.documentUndoLimit=200
  ide.editor.tabs.interactive.pin.button=false
  ide.balloon.shadow.size=0
  ide.new.color.picker=false
  eslint.additional.file.extensions=svelte
Non-Bundled Plugins:
  com.jetbrains.plugins.ini4idea (241.14494.240)
  com.paperetto.dash (3.3)
  net.sjrx.intellij.plugins.systemdunitfiles (223.240127.136)
  org.toml.lang (241.14494.150)
  com.vecheslav.darculaSolidTheme (1.0.3)
  com.jetbrains.space (241.14494.150)
  com.myoutdesk.tailwind_formatter (2.0.10)
  com.intellij.ideolog (222.3.2.0)
  com.wix.sasslint (1.1.2)
  String Manipulation (9.12.0)
  ir.msdehghan.plugins.ansible (0.92)
  com.intellij.swagger (241.14494.150)
  net.seesharpsoft.intellij.plugins.csv (3.3.0-241)
  dev.blachut.svelte.lang (241.14494.140)
  me.mbolotov.cypress (1.6.2)
  zielu.gittoolbox (500.2.3+233)
  mobi.hsz.idea.gitignore (4.5.2)
  ru.adelf.idea.dotenv (2024.1)
  com.intellij.plugins.html.instantEditing (241.14494.140)

**Screenshots**
![image](https://github.com/zielu/GitToolBox/assets/139183/8f325461-c479-46e7-9e94-4167122483c4)

**Comment by zielu** [comment]
Hi, I'll look into it. Notification is implemented to be shown only once.

**Comment by zielu** [comment]
I pushed 500.2.4+233 to EAP channel that has new option to disable promotional information, as proper fix will take a bit longer.
https://gittoolbox.lukasz-zielinski.com/docs/eap-releases/ describes how to switch to EAP builds. 

I very rarely release exclusive EAP versions and always push regular releases there too, so there is little drawback if you stay on EAP in the future.

![image](https://github.com/zielu/GitToolBox/assets/464103/6b650f23-ec77-4b07-8c0f-05098a1f2463)

**Comment by unikitty37** [comment]
Brilliant — thanks!

Not sure if you want this issue left open in order to track the full fix; please feel free to close if you don't 🙂

**Comment by zielu** [comment]
Done in 500.2.5
