### ISSUE TITLE
Not working on MacOS - Sonoma version 14.4.1

### ISSUE THREAD

**Issue by alishanvr** [zielu/GitToolBox#553]
Hi, 

I recently updated my PHP Storm to 2024.1.1, and purchased and installed Git ToolBox. But, the plugin is not working. 

 

Following are some screenshots:

 

1. https://share.cleanshot.com/W2Z3SM5J

2. https://share.cleanshot.com/dwZmfjhl

3. https://share.cleanshot.com/JvZFDZXv

 

Thank You,

**Comment by zielu** [comment]
Hi, do you have directory mappings configured ? https://www.jetbrains.com/help/idea/settings-version-control-directory-mappings.html

Are there any exceptions in the logs?

**Comment by alishanvr** [comment]
The issue has been fixed after enabling VCS. 

See screenshot https://share.cleanshot.com/RXQHNf8j

**Comment by zielu** [comment]
Nice to hear that. I'll add info about this to troubleshooting docs.

**Comment by zielu** [comment]
Docs updated
