### ISSUE TITLE
[BUG] Unable to change `GitToolBox` to Premium on `macOS Sonoma 14.5`

### ISSUE THREAD

**Issue by abhisheikdeo** [zielu/GitToolBox#556]
**Describe the bug**
I've purchased `GitToolBox` and paid a yearly subscription. Now, am unable 

**To Reproduce**
1. Go to `Plugins` page
2. Click on `Installed` tab
3. Scroll down to `GitToolBox`
4. It still shows `Freemium`

**Expected behavior**
When I right click on a file then I should be able to see that the `PRO` features should be enabled.

**Plugin version**
Exact plugin version: `500.2.8+233`

**IDE version**
WebStorm 2024.1.3
Build #WS-241.17011.90, built on May 23, 2024
Licensed to Abhisheik Deo
Subscription is active until February 24, 2025.
Runtime version: 17.0.11+1-b1207.24 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.5
GC: G1 Young Generation, G1 Old Generation
Memory: 20480M
Cores: 12
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  AWSCloudFormation (241.14494.150)
  com.dequelabs.lsp (4.8.2)
  com.thvardhan.gradianto (5.5)
  com.jetbrains.space (241.17011.48)
  dev.meanmail.plugin.nginx-intellij-plugin (2024.2)
  com.tabnine.TabNine (1.90.0)
  com.intellij.mermaid (0.0.22+IJ.232)
  ru.adelf.idea.dotenv (2024.1)
  com.intellij.database (241.14494.180)
  com.mallowigi (97.0.0)
  zielu.gittoolbox (500.2.8+233)

**Screenshots**
![image](https://github.com/zielu/GitToolBox/assets/26565158/a4a713a4-0eb6-409d-a122-ae1e398c1c60)

**Comment by abhisheikdeo** [comment]
![image](https://github.com/zielu/GitToolBox/assets/26565158/2dd7aeb4-d824-46e6-922c-46022a308535)
I'm expecting the last 4 options with `(PRO)` should be available for me now.

**Comment by zielu** [comment]
Hi, options will become available when original issue is solved - the "No license". Can you go to `Help > Register...` and see how it looks there ? Afair there is an option there to active the license.

**Comment by abhisheikdeo** [comment]
`Help > Register`... worked correctly for me.
I'd purchased this license on a different account whilst my jetbrains account was associated to a different email id. Once I linked the email id to my jetbrains account, it worked well.
Thanks @zielu ! 

I'm closing this issue with this comment.
