### ISSUE TITLE
[BUG] Plugin explicitly marked as incompatible

### ISSUE THREAD

**Issue by jzakrzewski** [zielu/GitToolBox#559]
**Describe the bug**
Plugin not loaded, the following is displayed:
![image](https://github.com/zielu/GitToolBox/assets/4115327/068198b3-d25b-4573-88e4-6831336ba073)

**To Reproduce**
1. Install the newest Clion EAP

**Expected behavior**
Plugin loaded

**Plugin version**
500.2.9+233

**IDE version**
CLion 2024.2 EAP
Build #CL-242.16677.29, built on June 13, 2024
Licensed to CLion EAP user: Jakub Zakrzewski
Expiration date: July 13, 2024
Runtime version: 21.0.3+13-b480.1 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.X11.XToolkit
Linux 5.15.0-112-generic
.NET Core v8.0.4 x64 (Server GC)
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 4500M
Cores: 16
Current Desktop: MATE

**Comment by thorstenvogel** [comment]
Same problem here, but with IntelliJ 2024.2 EAP.

**Comment by zielu** [comment]
Hi, yesterday I got an email from JB that they "adjusted" compatiblity. It does not state reason for the change and I'm trying to sort it out with them.

**Comment by zielu** [comment]
Small update, plugin indeed fails verification with 242.18071.24 (eap 6), do I assume this is the reason JB made the adjustment. I'll fix it on Monday.

**Comment by zielu** [comment]
Done in 500.2.10+242
