### ISSUE TITLE
[BUG]“Show Blame Details ” doesn't work anymore

### ISSUE THREAD

**Issue by Liuyutong1021** [zielu/GitToolBox#562]
**Describe the bug**
In the current "IntelliJ IDEA Ultimate 2024.1.4" version, the "Show Blame Details" feature does not work properly

**To Reproduce**
Clicking on any line in the code does not display the commit information for this line

**Expected behavior**
The latest commit information for any selected row should be displayed

**Plugin version**
5002.12+233

**IDE version**
IntelliJ IDEA 2024.1.4 (Ultimate Edition)
Build #IU-241.18034.62, built on June 21, 2024
授权给 Tencent Technology (Shenzhen) Co., Ltd.

Runtime version: 17.0.11+1-b1207.24 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4068M
Cores: 16
Registry:
  documentation.show.toolbar=true
  ide.experimental.ui=true
Non-Bundled Plugins:
  Batch Scripts Support (1.0.13)
  com.intellij.zh (241.271)
  com.intellij.plugins.visualstudio2022keymap (241.14494.150)
  Rider UI Theme Pack (0.14.11)
  CMD Support (1.0.5)
  com.tang (1.4.13-IDEA241)
  ai.codegeex.plugin (2.12.1-223)
  zielu.gittoolbox (500.2.12+233)
Kotlin: 241.18034.62-IJ

**Comment by zielu** [comment]
Hi, what happens when you invoke it from line context menu ? GitToolBox > Show Blame Details. Are there any exceptions in the logs?

**Comment by Liuyutong1021** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Liuyutong1021** [comment]
> Hi, what happens when you invoke it from line context menu ? GitToolBox > Show Blame Details. Are there any exceptions in the logs?

Where can I see the log? I didn't see any abnormality when I switched this option, but this function didn't respond at all.

**Comment by zielu** [comment]
You can find the logs via two IDE actions: `Help > Show Log` or `Help > Open Log`

**Comment by Liuyutong1021** [comment]
[idea-logs-20240726-1415214363452899307761033.zip](https://github.com/user-attachments/files/16387303/idea-logs-20240726-1415214363452899307761033.zip)

**Comment by Liuyutong1021** [comment]
> [idea-logs-20240726-1415214363452899307761033.zip](https://github.com/user-attachments/files/16387303/idea-logs-20240726-1415214363452899307761033.zip)

This is the log I exported. Please help me see what happened.

**Comment by zielu** [comment]
Hi, I examined at the logs and it looks like there might be something wrong with the git repository based on amount of errors visible. I'd recommend cloning it anew.

**Comment by Liuyutong1021** [comment]
OK, thank you very much for your help! I will try to solve the problem according to your request.

**Comment by Liuyutong1021** [comment]
Thanks a lot for your help, after I recreated my workspace everything worked fine!
