### ISSUE TITLE
[BUG] Inline font size remains big after exiting presentation mode 

### ISSUE THREAD

**Issue by dm0dev** [zielu/GitToolBox#563]
**Describe the bug**
 Inline font size remains big after exiting presentation model. 

This behavior is kinda strange. Some Lines do reset the font size, other don't. I still don't know, why and when, but the size varies for name, date, commit message.

Sometimes it changes after moving the text cursor and sometimes it does not.

**To Reproduce**
1. Enter Presentation Mode
2. Exit Presentation Mode

**Expected behavior**
The Inline Git Information at the end of the cursor should return to it's original size.

**Plugin version**
500.2.10+233

**IDE version**
IntelliJ IDEA 2024.1.1 (Ultimate Edition)
Build #IU-241.15989.150, built on April 29, 2024
Licensed to XXXXXXXXXXXXX
Runtime version: 17.0.10+1-b1207.14 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 8
Registry:
  ide.experimental.ui=true
  terminal.new.ui=true
Non-Bundled Plugins:
  com.jetbrains.plugins.ini4idea (241.15989.113)
  org.jetbrains.plugins.go-template (241.14494.150)
  com.eclectide.intellij.whatthecommit (1.3)
  com.intellij.lang.puppet (241.14494.150)
  com.jetbrains.inin (0.2.2)
  lermitage.intellij.extratci (2024.3.1)
  Key Promoter X (2024.2.0)
  com.jetbrains.gerryPurpleTheme (2024.1.0724)
  org.jetbrains.plugins.ruby (241.15989.150)
  Intellij_GitHub_Dark_Theme (1.1.3)
  com.vecheslav.darculaSolidTheme (1.0.3)
  com.jetbrains.CyanTheme (1.3)
  com.github.lonre.gruvbox-intellij-theme (0.6.2)
  Pythonid (241.15989.194)
  com.taff.plugin.orchide (2023.1.5.1-2022.3)
  lermitage.intellij.ilovedevtoys (1.11.0)
  guru.ide.gitlab (2024.3.0.241)
  net.seesharpsoft.intellij.plugins.csv (3.3.0-241)
  com.intellij.ml.llm (241.15989.195)
  mobi.hsz.idea.gitignore (4.5.3)
  zielu.gittoolbox (500.2.12+233)
Kotlin: 241.15989.150-IJ

**Screenshots**

![2024-07-31_12h07_41](https://github.com/user-attachments/assets/f5cd521b-9d7f-4335-a924-0bd405225c6c)
![2024-07-31_12h08_03](https://github.com/user-attachments/assets/cc25badc-467a-4dac-824c-54e0e6d38f3c)

**Comment by zielu** [comment]
Hi, that looks horrible 🙂. I'll look into it over the weekend.

**Comment by zielu** [comment]
Done in 500.2.13
