### ISSUE TITLE
[BUG] Settings page does not scroll

### ISSUE THREAD

**Issue by keysmashes** [zielu/GitToolBox#564]
**Describe the bug**
The plugin settings page does not scroll when it does not fit on a single screen.

**To Reproduce**
1. Have a low screen resolution, large font size, or high zoom factor
2. Open the GitToolBox settings

**Expected behavior**
A scrollbar should be visible, perhaps

**Plugin version**
500.2.14+242

**IDE version**
PyCharm 2024.2 (Professional Edition)
Build #PY-242.20224.347, built on August 9, 2024
Runtime version: 21.0.3+13-b509.4 aarch64 (JCEF 122.1.9)
macOS 14.5

**Screenshots**
<img width="742" alt="image" src="https://github.com/user-attachments/assets/f6248efb-86e0-4db7-bdd8-0bc3abfe23e2">

**Comment by zielu** [comment]
Hi, it is disabled because some of settings tabs have their own scrolls and such "double scroll" behaved wierd. I'm trying to get rid of tabbed interface but it's going slow.
I'll check anyway - maybe after some recent changes that I've done it will behave better.

**Comment by zielu** [comment]
Done in 500.2.15
