### ISSUE TITLE
[BUG] Not compatible with WebStorm 2024.2

### ISSUE THREAD

**Issue by michaelwijnands** [zielu/GitToolBox#565]
**Describe the bug**
I recently updated WebStorm to version 2024.2 (public version, no EAP). However, I cannot update GitToolBox because it says it's incompatible with WS.

"Incompatible: requires IDE build 241.* or earlier".

**To Reproduce**
1. Open WebStorm 2024.2
2. Try to update the plugin

**Plugin version**
500.2.14+233 -> 500.2.14+242

**IDE version**
Build #WS-242.20224.342, built on August 9, 2024.

**Screenshots**
<img width="807" alt="image" src="https://github.com/user-attachments/assets/f4f503f9-4ade-4606-9210-5aa4e366b482">

**Comment by michaelwijnands** [comment]
I actually didn't try to update because it looked like the button is disabled because of my theme, but after updating it seems to work fine even though it did show the above 'incompatible' message.

**Comment by zielu** [comment]
Hi, I suspect that message was about currently (before update +233) version, because it's compatiblity range is until 241. For IDEs from 2024.2 series version has +242 at the end.
