### ISSUE TITLE
[BUG] Lost pop-up for create merge request / pull request in latest plugin version

### ISSUE THREAD

**Issue by pauliuspetronis** [zielu/GitToolBox#570]
**Describe the bug**
Before last version suggestion for create merge request on pushed branch. Latest version doesn't provide pop-up for that.

https://gittoolbox.lukasz-zielinski.com/docs/create-pr-links/

<img width="757" alt="image" src="https://github.com/user-attachments/assets/93c1e669-baa9-4d43-aabd-c24af9331497">

**Comment by zielu** [comment]
Hi, I'll look into it.

**Comment by zielu** [comment]
Indeed the popup is no longer there.

**Comment by zielu** [comment]
Done in 600.0.1

**Comment by pauliuspetronis** [comment]
> Done in 600.0.1

thanks
