### ISSUE TITLE
[Feature] Support 1password ssh agent

### ISSUE THREAD

**Issue by juherr** [zielu/GitToolBox#572]
I'm using [the 1password ssh agent](https://developer.1password.com/docs/ssh/agent/) 
This tool supports both JetBrains IDEs and git CLI:
https://developer.1password.com/docs/ssh/agent/compatibility#jetbrains-ide
https://developer.1password.com/docs/ssh/agent/compatibility#git-cli

But when the auto fetch is run in the background, it is always failing:

```
sign_and_send_pubkey: signing failed for ED25519 "/Users/juherr/.ssh/id_ed25519" from agent: communication with agent failed git@github.com: Permission denied (publickey). Could not read from remote repository.  Please make sure you have the correct access rights and the repository exists.
```

There is a specific section of documentation that explains how it works: https://developer.1password.com/docs/ssh/agent/security/#suppressing-background-requests

A possible solution could be to automatically disable auto fetch when the IDE is running in background.

**Comment by zielu** [comment]
Hi, indeed I can add an option to skip auto-fetch when IDE window is not active.

**Comment by zielu** [comment]
Done in 600.0.9

**Comment by zielu** [comment]
Done in 600.0.9
