### ISSUE TITLE
[BUG] Background tasks high CPU usage

### ISSUE THREAD

**Issue by olekszhel** [zielu/GitToolBox#573]
**Describe the bug**
After switch to the latest version of IntelliJ IDEA 2024.2.3 on Windows10 latest version of GitToolBox 600.0.2+242 started to cause IDEA hanging by its background processes (everything works like a charm without plugin). The only way to reanimate work is to kill idea process.

**To Reproduce**
1. Wait some time for background process to start
2. It hangs everything doing "Saving application settings"

**Expected behavior**
Working IDEA

**Plugin version**
600.0.2+242

**IDE version**
Edition	Windows 10 Pro
Version	22H2
Installed on	‎3/‎4/‎2022
OS build	19045.5011
Experience	Windows Feature Experience Pack 1000.19060.1000.0

**Screenshots**
![image](https://github.com/user-attachments/assets/6992c7f8-fbc9-44e9-b56d-fa448980d893)
![image](https://github.com/user-attachments/assets/287cce33-228b-423d-ae67-5a1795c09833)

**Comment by zielu** [comment]
Hi, I got similar report but without much details. I'm preparing a new test release which should address it. I'll let you know when it's up and how to get it.

**Comment by zielu** [comment]
I pushed [600.0.3+242 build to EAP channel](https://plugins.jetbrains.com/plugin/7499-gittoolbox/versions/eap/622528). How to switch is described here https://www.gittoolbox.com/docs/eap-releases/

Let me know if it's behaving better, I found an issue with auto-fetch (which is a background process) hopefully it was it.

**Comment by olekszhel** [comment]
> I pushed [600.0.3+242 build to EAP channel](https://plugins.jetbrains.com/plugin/7499-gittoolbox/versions/eap/622528). How to switch is described here https://www.gittoolbox.com/docs/eap-releases/
> 
> Let me know if it's behaving better, I found an issue with auto-fetch (which is a background process) hopefully it was it.

I updated to 600.0.3+242, but it didn't help.

![image](https://github.com/user-attachments/assets/a0423e5d-162f-4a0c-9eb5-939adfecb9c3)
![image](https://github.com/user-attachments/assets/f7dec829-dc13-42ca-831a-beb4b3a982f2)
![image](https://github.com/user-attachments/assets/15ed8f1e-a861-44fc-bb91-a3c149ce1e34)


So I believe it is related to "Saving application settings"

Also it could be related to the number of repos in project (I have 67 repos). But everything was fine till I upgraded to the latest version of IDEA and may be I also updated to the latest version of GitToolBox

**Comment by zielu** [comment]
How may repos do you have in that project? Also could you try to disable outdated branches cleanup ? (Settings > Version Control > GitToolBox > Branches > first 3 checkboxes)

**Comment by olekszhel** [comment]
> How may repos do you have in that project? Also could you try to disable outdated branches cleanup ? (Settings > Version Control > GitToolBox > Branches > first 3 checkboxes)

![image](https://github.com/user-attachments/assets/2cbab701-e75e-4704-97bf-b905eabd1d59)

unticked the first checkbox, the rest is inactive. 67 repos in project.

**Comment by olekszhel** [comment]
> How may repos do you have in that project? Also could you try to disable outdated branches cleanup ? (Settings > Version Control > GitToolBox > Branches > first 3 checkboxes)

Hangs again
![image](https://github.com/user-attachments/assets/061d3ebe-40fe-4fc2-a90f-5d2e8e98063b)

When I try to exit IDEA
![image](https://github.com/user-attachments/assets/26e72cf2-175d-4775-9d05-e5a90020ab1c)

**Comment by zielu** [comment]
I pushed 600.0.4+242 with some more changes, if it still hangs please take a thread dump and share it (Help > Diagnostic Tools > Dump Threads )

**Comment by olekszhel** [comment]
> I pushed 600.0.4+242 with some more changes, if it still hangs please take a thread dump and share it (Help > Diagnostic Tools > Dump Threads )

Everything is okay now, thanks! It works even with Auto Cleanup enabled with latest update (600.0.4+242)
