### ISSUE TITLE
[BUG] Auto fetch failed Cuz connection closed by UNKNOWN port 65535 Could not read from remote repository.  

### ISSUE THREAD

**Issue by morty6688** [zielu/GitToolBox#576]
**Describe the bug**
Auto fetch reports the error below:
Connection closed by UNKNOWN port 65535 Could not read from remote repository.  Please make sure you have the correct access rights and the repository exists.

But whether I use the command line(git fetch) or menu option(Update Project), I can fetch normally. 

**Plugin version**
600.0.5+242

**IDE version**
IntelliJ IDEA 2024.2.4 (Ultimate Edition)
Build #IU-242.23726.103, built on October 23, 2024
Licensed to Jian Li
Subscription is active until July 1, 2025.
Runtime version: 21.0.4+13-b509.26 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.windows.WToolkit
Windows 11.0
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 8192M
Cores: 32
Registry:
  debugger.new.tool.window.layout=true
  documentation.show.toolbar=true
  ide.experimental.ui=true
  i18n.locale=
  terminal.new.ui=true
  org.toml.json.schema=false
  editor.minimap.enabled=true
Non-Bundled Plugins:
  Batch Scripts Support (1.0.13)
  com.rmondjone.jsontotypescript (2023.1.2)
  lermitage.intellij.extratci (2024.5.3)
  org.jetbrains.plugins.go (242.23726.16)
  com.intellij.plugins.vscodekeymap (242.20224.385)
  com.intellij.notebooks.core (242.23726.16)
  intellij.jupyter (242.23726.16)
  leetcode-editor (8.14)
  name.kropp.intellij.makefile (242.23726.16)
  com.karateca.jstoolbox (1.10)
  PythonCore (242.23726.103)
  com.jetbrains.rust (242.23726.110)
  de.netnexus.camelcaseplugin (3.0.12)
  com.andrey4623.rainbowcsv (2.0.2)
  com.jetbrains.space (242.23726.16)
  com.intellij.drools (242.20224.159)
  GsonFormatPlus (1.6.1)
  org.jetbrains.plugins.go-template (242.20224.155)
  com.aegamesi.java_visualizer.plugin (2.2.1)
  de.kontext_e.idea.plugins.autofill (1.3.2)
  com.intellij.ideolog (242.23726.110)
  com.markskelton.one-dark-theme (5.12.0)
  nl.rubensten.texifyidea (0.9.7)
  com.intellij.guice (242.20224.159)
  ink.organics.pojo2json (2.1.0)
  Statistic (4.3.2)
  org.jetbrains.plugins.localization (242.20224.159)
  AceJump (3.8.20)
  zookeeper (0.0.14)
  Pythonid (242.23726.103)
  com.intellij.plugin.adernov.powershell (2.8.0)
  org.asciidoctor.intellij.asciidoc (0.43.1)
  MavenRunHelper (4.29.0-IJ2022.2)
  net.seesharpsoft.intellij.plugins.csv (4.0.0)
  cn.kt.better.mybatis.generator.id (1.5.5)
  com.intellij.bigdatatools.core (242.23726.103)
  com.intellij.bigdatatools.databricks (242.23726.103)
  com.intellij.bigdatatools.binary.files (242.20224.159)
  com.intellij.bigdatatools.rfs (242.23726.103)
  com.intellij.bigdatatools.metastore.core (242.20224.159)
  com.intellij.bigdatatools.flink (242.20224.159)
  com.intellij.bigdatatools.spark (242.20224.159)
  kotest-plugin-intellij (1.3.85-2024.2)
  com.bruce.intellijplugin.generatesetter (2.8.4)
  com.jetbrains.packagesearch.intellij-plugin (242.0.12)
  com.intellij.bigdatatools.zeppelin (242.22855.36)
  me.serce.solidity (2.4.5)
  org.intellij.prisma (242.23726.38)
  com.intellij.lang.jsgraphql (242.21829.3)
  io.plugin.tsnode (2024.08.16-1)
  com.github.dinbtechit.jetbrainsnestjs (0.0.2)
  com.jetbrains.php (242.23726.107)
  ru.adelf.idea.dotenv (2024.2.1)
  com.intellij.bigdatatools.kafka (242.20224.159)
  com.intellij.bigdatatools (242.22855.36)
  com.baomidou.plugin.idea.mybatisx (1.6.3)
  com.github.copilot (1.5.27.7265)
  izhangzhihao.rainbow.brackets (2024.2.6-241)
  zielu.gittoolbox (600.0.5+242)
Kotlin: 242.23726.103-IJ

**Comment by zielu** [comment]
Hi, do you have anything in Settings > Version Control > GitToolBox > GitToolBox Project > Auto fetch > Exclusions ?

**Comment by morty6688** [comment]
> Hi, do you have anything in Settings > Version Control > GitToolBox > GitToolBox Project > Auto fetch > Exclusions ?

nope, just like this:
![image](https://github.com/user-attachments/assets/d9464caf-a397-4698-b55a-81a687e9574b)

**Comment by zielu** [comment]
Hmm, what about ` git remote -v` ? That UNKNOWN 65535 is looking very strange.

**Comment by morty6688** [comment]
> Hmm, what about `git remote -v` ? That UNKNOWN 65535 is looking very strange.

`git remote -v` can work, too. Maybe the issue is cuz I added a vpn? is there a wrapped git using in GitToolBox?

**Comment by zielu** [comment]
My plugin is calling utility provided by Idea built-in git support to do the fetch, with some added filtering of excluded remotes. 
That Idea utility in turn calls git CLI, so in theory if IDE `Git > Fetch` action works, auto-fetch should also work.

**Comment by morty6688** [comment]
> My plugin is calling utility provided by Idea built-in git support to do the fetch, with some added filtering of excluded remotes. That Idea utility in turn calls git CLI, so in theory if IDE `Git > Fetch` action works, auto-fetch should also work.

Well, so this is actually a weird issue😂

**Comment by zielu** [comment]
Can you share output of `git remote -v` ?

**Comment by morty6688** [comment]
> Can you share output of `git remote -v` ?

![image](https://github.com/user-attachments/assets/36671e83-1c3a-445d-8037-c41168fff7ba)
Sure, cuz this is a public repo by others, so I blurred something

**Comment by zielu** [comment]
I pushed 600.0.6+242 to EAP channel which contains some changes to auto-fetch, hopefully it will help. Here is how to switch to get it https://www.gittoolbox.com/docs/eap-releases/

**Comment by morty6688** [comment]
> I pushed 600.0.6+242 to EAP channel which contains some changes to auto-fetch, hopefully it will help. Here is how to switch to get it https://www.gittoolbox.com/docs/eap-releases/


![image](https://github.com/user-attachments/assets/6d6ed193-09af-4486-afa3-4c3c31d8c33b)
HI, I finally solved this issue by adding the manual proxy like this......

**Comment by morty6688** [comment]
> I pushed 600.0.6+242 to EAP channel which contains some changes to auto-fetch, hopefully it will help. Here is how to switch to get it https://www.gittoolbox.com/docs/eap-releases/

![image](https://github.com/user-attachments/assets/a221edb1-7262-4fb5-90d4-43715a2b18d9)
Sorry but a new issue occurred. I added the channel as the way u given, but it can't be updated cuz "remote host terminated the handshake". However, other plugin can be updated normally like "github copilot"

**Comment by zielu** [comment]
This might be helpful https://intellij-support.jetbrains.com/hc/en-us/community/posts/360000024944/comments/360000034470

**Comment by morty6688** [comment]
> This might be helpful https://intellij-support.jetbrains.com/hc/en-us/community/posts/360000024944/comments/360000034470

very thx, but I didn't set this. However somehow the plugin was updated successfully just now, I'll test it in the coming time. Let's wait for a period, thank you again.

**Comment by morty6688** [comment]
Hi~after recent watch, I think the issue has been fixed(version 600.0.7+242), so we can close this issue, very thx!
