### ISSUE TITLE
[BUG] Unable to Install or Update plugin

### ISSUE THREAD

**Issue by Ridewarior** [zielu/GitToolBox#579]
**Describe the bug**
I've become unable to update or install GitToolBox due to another process accessing and locking the file at AppData\Local\Temp\plugin5198986387712658149\gittoolbox\lib\bcprov-jdk15on-1.65.jar

Steps I've taken so far:
- Launch IDEA as Admin
- Fresh restarts of the computer and IDEA
- Installing from different sources (i.e. the raw download from marketplace)
- Uninstalling the existing GitToolBox plugin
- Removing the directory from AppData

I was previously on version 600.0.2+233, and it seems I'm unable to also re-install that version. Other plugins don't seem to be affected, I've been able to update/reinstall them.

**To Reproduce**
1. Open IDEA Plugins tab and search for GitToolBox
2. Click Install Button
3. An error message appears displaying a failure

1. Download latest version of plugin from Jetbrains Marketplace
https://plugins.jetbrains.com/plugin/7499-gittoolbox/versions
2. In IDEA Plugins tab, click the gear icon
3. Click install plugin from disk
4. An error message appears, displaying a failure

**Expected behavior**
Plugin is able to be installed and or updated

**Plugin version**
Version 600.0.7+242

**IDE version**
JetBrains Rider 2024.2.7
Build #RD-242.23726.100, built on October 22, 2024
Licensed to Antonio Magallon
You have a perpetual fallback license for this version.
Subscription is active until September 17, 2025.
Runtime version: 21.0.4+13-b509.26 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.windows.WToolkit
Windows 10.0
.NET Core v8.0.4 x64 (Server GC)
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 8000M
Cores: 24
Registry:
  ide.experimental.ui=true
  i18n.locale=
  terminal.new.ui=true
Non-Bundled Plugins:
  AceJump (3.8.20)
  IdeaVIM (2.16.0)
  org.jetbrains.IdeaVim-EasyMotion (1.16)
  ca.alexgirard.HarpoonIJ (0.1.8)
  org.igu.plugins.bettercomments (1.0)
  com.chylex.intellij.inspectionlens (1.4.1)
  com.github.copilot (1.5.28.7313)
  io.jetclient (2024.3.14-242)
  org.sonarlint.idea (10.11.1.79663)
  com.microsoft.vso.idea (1.162.2)

**Screenshots**
![2024-11-06 07_38_38-Window](https://github.com/user-attachments/assets/02f7095a-87f3-4d55-8c26-6c0ce58a7ac4)

**Comment by zielu** [comment]
Hi, I would say this might be some antivirus software messing it up - this lib is present for some months already.

**Comment by Ridewarior** [comment]
That's definitely possible, this is a company machine, so it's likely that there's some antivirus running that I'm not seeing. If that's the case, I still find it a bit odd that it's decided to affect only this file, and it's only this extension. Is there a version of the extension available without this that I can test installing by chance?

**Comment by zielu** [comment]
It would have to be this one https://plugins.jetbrains.com/plugin/7499-gittoolbox/versions/stable/490653, but you need IDE 2024.1 for it.

**Comment by zielu** [comment]
I will try to build a current version without that library - it's related to having blame cache encrypted, but it should not be needed.

**Comment by Ridewarior** [comment]
Just wanted to update that installing that I was able to install that version after a fresh install of Rider 2024.1.6. Trying to update the plugin to the latest version available though (600.0.2+23) still fails for the same reason.

**Comment by zielu** [comment]
Ok, thanks for checking. I'll let you know when I have new build ready.

**Comment by zielu** [comment]
I pushed 600.0.8+242 to EAP update channel, here is how you can switch to it - https://www.gittoolbox.com/docs/eap-releases/

**Comment by Ridewarior** [comment]
Hey, I was able to successfully install the new version! Thanks a ton for building a whole new version for this. Can't live without my git blame and auto branch cleanups lol.

I also purchased a full license for this plugin as an extra way to show my thanks! Love the support, thanks again!
