### ISSUE TITLE
[Bug] Can't click "Open File Link"

### ISSUE THREAD

**Issue by yang17** [zielu/GitToolBox#580]
**Describe the bug**
"Open File Link" is disabled, and says it is feature for "pro".  I don't understand what dose it mean by "Pro", dose it require pro for PHP storm ? pro for github ? pro for GitToolBox ? How do I get this "Pro" ?

**Expected behavior**
Being able to use open flie click feature.

**Plugin version**
600.0.7+242

**IDE version**
PhpStorm 2024.2.4
Build #PS-242.23726.107, built on October 23, 2024
Licensed to Trial User
Subscription is active until December 11, 2024.
Runtime version: 21.0.4+13-b509.26 aarch64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.lwawt.macosx.LWCToolkit
macOS 15.1
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 4096M
Cores: 10
Metal Rendering is ON
Registry:
  ide.balloon.shadow.size=0
  run.processes.with.pty=TRUE
  ide.new.editor.tabs.vertical.borders=true
  ide.animate.toolwindows=true
  ide.experimental.ui=true
  ide.editor.tab.selection.animation=true
  i18n.locale=
Non-Bundled Plugins:
  com.intellij.ml.llm (242.23726.20)
  com.magento.idea.magento2plugin (5.3.1)
  com.chrisrm.idea.MaterialThemeUI (9.5.0)
  zielu.gittoolbox (600.0.7+242)

**Screenshots**
<img width="555" alt="Screenshot 2024-11-11 at 4 22 11 PM" src="https://github.com/user-attachments/assets/72e2cd5d-8780-4d13-9e02-23aa13a6a2b9">

**Comment by zielu** [comment]
Hi, all features marked PRO require purchasing plugin license.
