### ISSUE TITLE
[Question]how can I do not highlight inline-blame text color 

### ISSUE THREAD

**Issue by yang17** [zielu/GitToolBox#581]
**Describe the bug**
Hi there, is there anyway I can get rid of the highlight color for inline-blame ? 
I tried changed material theme, but all of them are colorful.
<img width="517" alt="Screenshot 2024-11-18 at 11 05 58 AM" src="https://github.com/user-attachments/assets/2dd317d0-7c46-4c20-88b7-79a90c69dad8">

**Expected behavior**
The inline-blame text should be dark grey color

**Comment by zielu** [comment]
Hi, you can adjust in Settings / Editor / Color Scheme / GitToolBox Colors
