### ISSUE TITLE
[BUG] Last commit preview in line editor on font size change

### ISSUE THREAD

**Issue by RemRem57** [zielu/GitToolBox#584]
**Describe the bug**
When placing the cursor on a code line, a preview of the last commit with author, date, name show up at the end of the line, and when you scale up/down the font size of your editor (Command + Wheel), the preview keep the previous font size.

Additionaly, the commit author stay on the defaut font size even by changing your cursor line.

**To Reproduce**
1. Make sure that "Change font size with Command Wheel" is enabled ('Settings / Editor / General / Mouse Control')
2. Place your cursor on a code line to show up the last commit preview
3. Change your font size with Command+Wheel
4. See the preview aren't rendered with the correct font size

**Expected behavior**
A new rendered Commit preview with the correct font size

**Plugin version**
GitToolBox 600.0.9+243

**IDE version**
Build #WS-243.21565.180, built on November 12, 2024

**Screenshots**
![image](https://github.com/user-attachments/assets/1d3d2766-f215-4a9b-9b36-8417d2e5822b)
![image](https://github.com/user-attachments/assets/f5385cc4-8433-4e9f-b97b-d95a280cb0c3)

**Comment by zielu** [comment]
Hi, I'll look into it, looks similar to some already fixed issue related to presentation mode.

**Comment by zielu** [comment]
Please check with 600.0.10+243

**Comment by RemRem57** [comment]
@zielu tested in .10, everything ok :)
Thank's for your contribution
