### ISSUE TITLE
? turn off auto fetch for a repo

### ISSUE THREAD

**Issue by bstout** [zielu/GitToolBox#59]
Is it possible to not fetch updates, or their merge for a particular repo?

It seems there are per-repo settings, but I do not know how to access/configure things for each repo

**Comment by zielu** [comment]
Hi, it's per-project only for now: Settings >Other Settings > Git ToolBox Project > Auto fetch

**Comment by bstout** [comment]
I have and work in a single project in IJ.  Within my project I have 26 modules - each with their own git repo.  One particular repo/module - I do not want it to fetch new code, as my other modules are "locked in" or compatible only up to a certain tag in the master branch.  As it is, the toolbox d/ls new code in master beyond what I'm supporting
