### ISSUE TITLE
Git Status Widget UTF-8 display problem

### ISSUE THREAD

**Issue by r1j0** [zielu/GitToolBox#6]
Using PHPStorm v9.0 and GitToolBox v13.3.0 the awesome new Git status widget does not display the arrows correctly, see attached screenshot.

![screenshot from 2015-07-20 10 50 24](https://cloud.githubusercontent.com/assets/460665/8772651/2fd9613e-2ece-11e5-8abb-ea215efa9ba6.png)

Ubuntu 14.04

**Comment by zielu** [comment]
It depends on font used by Ide (Settings / Appearance). Some do not display Utf8 correctly. Which font are you using?

**Comment by r1j0** [comment]
I'm using the default font. Guess it could be a Ubuntu font thing.

![screenshot from 2015-07-20 13 46 25](https://cloud.githubusercontent.com/assets/460665/8775168/c37b6448-2ee5-11e5-999a-5ea6fa546a17.png)

**Comment by zielu** [comment]
I've see some windows fonts that also do not render correctly. I'll add alternative presentation mode to work around this.

**Comment by r1j0** [comment]
Thank you
