### ISSUE TITLE
Fetch failed when auto fetch

### ISSUE THREAD

**Issue by gongzelong0718** [zielu/GitToolBox#63]
I got this message over and over again in Android studio Event log, every 15 minutes.

```
Fetch problems:
			/home/zelongg/Opera/mini/work: fetch failed
			/home/zelongg/Opera/mini/work/chromium/src: fetch failed
```

> Debug logging
> 
> Set following in Help > Debug Log Settings...
> 
> #zielu.gittoolbox
> 
> Performance logging
> 
> Set following in Help > Debug Log Settings...
> 
> #zielu.gittoolbox.perf:trace

I opened the log of debug and performance, any other advice to locate the reason of this issue?

I can manually `git fetch` to get the remote codes. So I think it must be related to the plugin.

**Comment by zielu** [comment]
Hi, you can see fetch output in VCS tool window in Console tab. 
You could run Fetch action from IDE and see if it works.

**Comment by gongzelong0718** [comment]
@zielu
I do not think I got you 100%.
Do you mean I should click `VCS->Git->Fetch`?
I did this, and in Event log tab of Android studio, 

下午2:55	Fetch problems:
					/home/zelongg/Opera/mini/work: fetch failed

下午2:57	Fetch failed: Could not read from remote repository.

**Comment by zielu** [comment]
If VCS->Git-Fetch fails and CLI works then there's general problem with IDE not directly related to plugin

**Comment by gongzelong0718** [comment]
@zielu Thanks for confirming that :)
