### ISSUE TITLE
No Settings / Other Settings / Git ToolBox Global

### ISSUE THREAD

**Issue by bstout** [zielu/GitToolBox#66]
Version: 173.2.0

![image](https://user-images.githubusercontent.com/742839/34884957-370d1b1a-f773-11e7-8760-b7a0b4328ef0.png)

Docs show sections: 
* Settings / Other Settings / Git ToolBox Global
* Settings / Other Settings / Git ToolBox Project

But I only see Project - no Global

**Comment by bstout** [comment]
IntelliJ IDEA 2017.3.3 (Ultimate Edition)
Build #IU-173.4301.14, built on January 9, 2018

JRE: 1.8.0_152-release-1024-b11 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13.2

**Comment by zielu** [comment]
I tried reproduce  #65 and this one on Mac OS but everything seems to work fine. 
Would you be willing to try dev build with additional logging to help me with pinpointing the issue ?

**Comment by bstout** [comment]
Sure - if you send me a private link to debug build I can use that temporarily

![image](https://user-images.githubusercontent.com/742839/34965304-e44961b2-fa07-11e7-99c1-cece1c5d0409.png)

**Comment by zielu** [comment]
Looks like you opened File > Settings > Default Settings and from what I see you cannot add repository roots there (#65) and you also cannot access global settings. 
My reasoning is I see `For default project` and it normally it says `For current project`.

**Comment by bstout** [comment]
Perfect.  Yes, in Preferences > Other Settings I see both Global and Project and here, on the project dialog I can add an exclusion.

"A picture is worth a thousand words" and my screenshot got to the problem of my misunderstanding - thanks
