### ISSUE TITLE
filter exclusion not working?

### ISSUE THREAD

**Issue by bstout** [zielu/GitToolBox#68]
I added an exclusion for a git repo:
![image](https://user-images.githubusercontent.com/742839/35010549-14e0e06a-fab8-11e7-87c9-6d8208815739.png)

Then in Event Log of IJ I see below after I click the 'update' link
![image](https://user-images.githubusercontent.com/742839/35010627-53a6e006-fab8-11e7-81da-948ca9241fbe.png)

So that repo it's complaining about is the one I intended to exclude.  I don't track remote changes as the branch is 'frozen' locally

**Comment by zielu** [comment]
Looks like I missed this use case. 
Right now exclusions only work for auto-fetch. 
What you could do is install Git Extender and set it in Git ToolBox Global > Update project action.
Git Extender is able to skip repositories without remote tracking branches.

**Comment by zielu** [comment]
Note to self:
- [] dedicated update action can be provided instead of built-in by using git4idea.update.GitUpdateProcess.
- can be extended to provide custom "Update all action" that skips repositories on branches without tracking

**Comment by zielu** [comment]
It is fixed in IntelliJ 2018.2 Git Integration
