### ISSUE TITLE
More visible notifications

### ISSUE THREAD

**Issue by henno** [zielu/GitToolBox#72]
Currently There is only very tiny green bubble at the bottom right corner and small numbers with arrows beside it when a new commit appears on remote tracking branch. 

People like me who deeply concentrate on task at hand don't notice such things and would appreciate nofitications like this one:

![A mockup](https://lh3.googleusercontent.com/mqzgD4G1vq3563bW2t1Cvb_jG_DK3OAznpgj-n4pogMV1GOM6T_L3KVARrMt3a_zdxxv1JEaxoX0jR8dnTqxTMyIOhUGL6UMUE1lbU6OhlC9Cjnt1Dga8dhVeAw3Wzg--t2N6fVO4Io=w434-h129-no)

**Comment by zielu** [comment]
Behind tracker shows following notification
![vcs_notification](https://user-images.githubusercontent.com/464103/35618109-3d456b02-067a-11e8-91ed-0e6f327bede7.png)

IDE hides it by itself after some time and there are project view annotations.

There could be an option to select type of notification.

**Comment by henno** [comment]
I have ran GitToolbox for 2 weeks and I have active team but I have never seen this green notification before. I checked and I have "Behind tracker" turned on.
On Wed, Jan 31, 2018 at 12:34, Łukasz Zieliński <notifications@github.com> wrote:
Behind tracker shows following notification
[https://user-images.githubusercontent.com/464103/35618109-3d456b02-067a-11e8-91ed-0e6f327bede7.png]

IDE hides it by itself after some time and there are project view annotations.

There could be an option to select type of notification.

**Comment by zielu** [comment]
I just noticed it can get "eaten" by other Git-related notifications like "Fetched successfully" - so you can find it in Event Log but otherwise it can be missed.

Right now this balloon reuses "Vcs Messages" group (Settings > Appearance & Behavior) so in connection with previous thought about ability to select type it makes sense to create GitToolBox group so that you can control notification behavior.

**Comment by zielu** [comment]
You can try modified notifications (they still need some slight adjustments) by installing plugin EAP build.
There are instructions in main [readme](https://github.com/zielu/GitToolBox) how to do it.

**Comment by zielu** [comment]
Implemented in 173.3.0
