### ISSUE TITLE
There is no GitToolBox menu

### ISSUE THREAD

**Issue by m-titov** [zielu/GitToolBox#73]
IntelliJ IDEA 2018.1 EAP (Ultimate Edition)
Build #IU-181.3263.15, built on January 31, 2018
IntelliJ IDEA EAP User
JRE: 1.8.0_152-release-1136-b5 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.2

![image](https://user-images.githubusercontent.com/25036750/35695574-970836b0-078d-11e8-9c20-a05b929605ad.png)

**Comment by zielu** [comment]
@m-titov Hi, looks like it did not install correctly. You can try checking in Help > Tail Log in Console - maybe there are some clues.

**Comment by m-titov** [comment]
my bad

**Comment by zielu** [comment]
@m-titov It may be you get an error while installing EAP - I removed old version and seems like it needs some time to propagate new one. As work-around you can install manually.
