### ISSUE TITLE
switch branch name completion in commit dialog off

### ISSUE THREAD

**Issue by musicformellons** [zielu/GitToolBox#75]
When writing commit messages in Pycharm when I type e.g. 'a', so quite often, or any other letter which is part of 'master' a suggestion popup suggest 'master' which is instantly selected when I type a space... This is not very welcome behavior: can I toggle 'Branch name completion in Commit dialog' off? Is this really how this is supposed to work?

**Comment by jruuttun** [comment]
I'm just about to uninstall this plugin for this annoying behavior.

**Comment by zielu** [comment]
It should and does not work this way at least in Idea (2017 and 2018).
What Pycharm version and OS are you using ?
You could also disable completion completely is project setrings.

**Comment by jruuttun** [comment]
![gittoolbox-annoyance](https://user-images.githubusercontent.com/219291/39349848-1652575c-4a05-11e8-9948-b856e30f0106.png)

This on:

> IntelliJ IDEA 2018.1 (Ultimate Edition)
> Build #IU-181.4203.550, built on March 26, 2018
> JRE: 1.8.0_152-release-1136-b20 amd64
> JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
> Linux 4.4.0-121-generic

Same issue with IDEA 2018.1 at Windows 7.

Fixed by unchecking Other Settings -> GitToolBox Project -> Commit dialog completion. Thanks!

**Comment by zielu** [comment]
@jruuttun 
Could you check if you have following setting enabled:
`Settings` > `Editor` > `General` > `Code Completion` > `Insert selected variant by typing dot, space, etc.`

**Comment by jruuttun** [comment]
@zielu Disabling `Auto-display code completion` just above `Insert selected variant by typing dot, space, etc.` does fix it, thanks! I had missed this option entirely.

This solution also allows me to auto-complete branch names with Ctrl+Space using the `branch name` completion formatter setting. Excellent. :+1:

**Comment by zielu** [comment]
Root cause was identified and completion works according to Code Completion configuration options.
Nothing to do more

**Comment by hardbyte** [comment]
Is this really fixed? I have the setting `Insert selected suggestion by pressing space, dot, or other context-dependent keys` disabled, but on pressing enter when typing a commit message I get the annoying `.master` appended to my sentence.

I've disabled this plugin due to this behavior as I do want to still "show suggestions as you type" to be enabled globally.
