### ISSUE TITLE
Support for IntelliJ 2018.1

### ISSUE THREAD

**Issue by diskostu** [zielu/GitToolBox#78]
Currently, there is a RC2 for IntelliJ 2018.1: https://blog.jetbrains.com/idea/2018/03/intellij-idea-2018-1-rc2-is-here/

Please add support for this new major version. Thanks :-)

**Comment by diskostu** [comment]
I added a pull request: https://github.com/zielu/GitToolBox/pull/79

**Comment by zielu** [comment]
It's already here in form of EAP plugin channel :) https://github.com/zielu/GitToolBox#eap-builds

**Comment by diskostu** [comment]
Ah... I did not read about that. Sorry! Should be the first thing, checking
the README.

Anyway, thanks for the hint. I updated the plugin and it's working.

Best regards
Denny

Łukasz Zieliński <notifications@github.com> schrieb am Fr., 23. März 2018
um 12:32 Uhr:
