### ISSUE TITLE
When disconnected from the origin for a while, screen fills with fetch error dialogs

### ISSUE THREAD

**Issue by Nedskib** [zielu/GitToolBox#8]
Would be better to just show a warning triangle on the Git Stat status instead of a popup.

**Comment by zielu** [comment]
I though about this problem, but it seems hat it caught up with me sooner than later. I must look at the code who exactly is displaying this popup - my code or IntelliJ and I'll address this in next update.

**Comment by zielu** [comment]
I changed notification to balloon instead of dialog so it should not be so intrusive.
