### ISSUE TITLE
Add optional text enclosing "git status" project decorations

### ISSUE THREAD

**Issue by shi-bmz** [zielu/GitToolBox#80]
Hi, thanks for this plugin!  Coming from Eclipse, I found this feature really lacking in stock PyCharm.

I'd like to be able to have my project decorations appear in parentheses, e.g.
instead of project_name **master**
I'd see project_name **[master]**

Of course, best would be to set it up in such a way that the user can choose what kind of parentheses or other characters should be used to "wrap" the project's git status.

Thanks!

**Comment by zielu** [comment]
Added in 182.3.0
