### ISSUE TITLE
git repository sub-folder name disappears when Project View decoration is on

### ISSUE THREAD

**Issue by shi-bmz** [zielu/GitToolBox#81]
Hi,
I have a project containing a sub-folder which is a git repository.  When Project View decoration is on, the folder's name disappears.

**Comment by zielu** [comment]
Hi, which IDE and plugin version are you using ? Could you make a screenshot of this ? I want to see structure of the view to see which intermediate nodes are there.

**Comment by shi-bmz** [comment]
IDE 2017.3.4, plugin v173.3.0
sample project with decoration:
![image](https://user-images.githubusercontent.com/12997812/37897422-ca9ec806-30ee-11e8-9c66-ee6fcb9bb2e7.png)

sample project without decoration:
![image](https://user-images.githubusercontent.com/12997812/37897452-dbe94a82-30ee-11e8-9840-e24b66184dda.png)

I added the sandbox project to demonstrate how everything looks fine when the repository is not in a sub-folder of the project.

**Comment by zielu** [comment]
Thanks !! This will be very helpful for fixing.

**Comment by zielu** [comment]
Could you also post Settings > Project > Project structure ? I'm having problems with setting-up project the    same way and reproducing this

**Comment by shi-bmz** [comment]
![image](https://user-images.githubusercontent.com/12997812/38776211-008e76ca-409c-11e8-82e8-e5476cd54460.png)
One thing that may not be apparent is that the package folder was a symbolic link to the current directory (i.e. "pkg_name -> .").  I tried changing that to a regular folder, but the results were the same.

**Comment by shi-bmz** [comment]
The extra .idea folder under sample_repo must have been created when I tried opening sample_repo as a project.  I deleted sample_repo/.idea but the buggy behaviour remains.

**Comment by zielu** [comment]
I finally managed to reproduce this and there is a workaround:
Disable everything under Git Toolbox Global > Decoration Customization. So now custom colors, bold or italics for now until I get to the bottom of this

**Comment by zielu** [comment]
Fixed in 173.3.1 and 181.0.4
