### ISSUE TITLE
Feature Request: Button to fetch,stash,rebase and stash pop in one go

### ISSUE THREAD

**Issue by Regiden** [zielu/GitToolBox#9]
Hey, great Plug-In!

A thing we do a lot here is to avoid using pull. I know you can use *git pull --rebase* to get a similar effect, however the problem is, that we often have uncommitted changes and want to avoid the merges. Our workflow is often to simply fetch -> stash changes -> rebase -> unstash changes via stash pop. 
Since you featured auto-fetch, I wonder if it would be possible to add a feature that basically does the flow I described.

Cheers!

**Comment by zielu** [comment]
This workflow is almost supported in IntelliJ (I also do it the same way at work and discovered this recently) - after fetch you do VCS / Update project... which supports stash/shelve -> rebase -> pop.

I saw comment in plugin repository (probably yours :)) and I'm testing new plugin version that shows link to Update project... action in popup message after repo changes. 

The idea is that auto-fetch / fetch is performed but actual update moment is user's decision. It also  provides better visibility to build-in feature and saves me lots of reimplementation :D .

I plan to release update during the weekend.

**Comment by Regiden** [comment]
Hey :D

yeah, that was my comment I guess. I couldn't see it so I thought it never arrived. Never knew about Update Project. Learning something new about this IDE every day, after using ti for 2 years. Awesome!

Some Link would be nice! Thanks a lot :)

**Comment by zielu** [comment]
New build uploaded

**Comment by Regiden** [comment]
Awesome! Thanks a lot :)
