### ISSUE TITLE
NPE when opening commit dialog

### ISSUE THREAD

**Issue by hosswald** [zielu/GitToolBox#91]
Since some of the last updates (IDEA EAP 2018.2), I can no longer open the commit dialog. The IDE reports the following stack trace:
![image](https://user-images.githubusercontent.com/32925139/40616493-9dbb3738-628b-11e8-8052-6c7e249abb84.png)

GitToolBox 181.0.5

IDEA 2018.2 EAP (Ultimate Edition)
Build #IU-182.2371.4, built on May 15, 2018
JRE: 1.8.0_152-release-1226-b7 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by zielu** [comment]
GitToolBox 181 does not work in 182. Please use EAP version for now: https://github.com/zielu/GitToolBox#eap-builds
