### ISSUE TITLE
Feature Request: option to disable autofetch by default on new project

### ISSUE THREAD

**Issue by mickaelperrin** [zielu/GitToolBox#97]
Hi,

Autofetch is activated by default. That would be cool to have an option in the "global" section to disable it by default.

Thanks !

**Comment by zielu** [comment]
@mickaelperrin There is way to do it right now but idk if this helps.
You can disable is default project settings. On Win it's in: File > Other settings > Settings for New Project

**Comment by mickaelperrin** [comment]
Awesome thanks !
