### ISSUE TITLE
Decoration does not update after repository update

### ISSUE THREAD

**Issue by Delagen** [zielu/GitToolBox#98]
Using Git Pull or via autofetch project is updated, but tag on head does not appear till restart IDE

**Comment by zielu** [comment]
Hi @Delagen, so steps look like this:

1. create remote tag
2. pull or fetch (also auto) & update project
3. tag is not displayed

**Comment by Delagen** [comment]
@zielu Yes. Tag pulled from remote. Displayed in repository log in WebStorm.
Also I can note that it is subrepo (not main)

**Comment by zielu** [comment]
By subrepo you mean submodule ?

**Comment by Delagen** [comment]
No. I mean repository placed inside project tree

**Comment by zielu** [comment]
Fixed in 182.3.0

**Comment by Delagen** [comment]
@zielu Seems not work
<img width="937" alt="annotation" src="https://user-images.githubusercontent.com/783335/45667246-07901c80-bb21-11e8-9c58-cf5d82f25eca.png">

**Comment by zielu** [comment]
Found another case - 
1. use checkout tag or revision to checkout tag1
2. decoration is updated correctly
3. checkout another tag
4. old tag stays

**Comment by Delagen** [comment]
Sorry. I am already installed 183.0

**Comment by zielu** [comment]
Great, released just you could check :smile:

**Comment by zielu** [comment]
Fixed in 183.0.1, 182.4.0
